// @ai:generated by=claude-opus-4-7 date=2026-06-19
package manifest

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/maoxiaoyue/hypgo/pkg/config"
)

// 一個極簡的測試 enricher：在 Summary 後附加識別字串，方便驗證有沒有跑到
type stubEnricher struct {
	tag string
}

func (e *stubEnricher) EnrichRoute(route RouteManifest) RouteManifest {
	route.Summary = route.Summary + " [" + e.tag + "]"
	return route
}

func TestAutoSync_NoLLMConfig_FallsBackToInference(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".hyp", "context.yaml")

	r := setupAutoSyncRouter()
	a := NewAutoSync(AutoSyncConfig{Enabled: true, Path: path}, r, nil, nil)

	if err := a.Sync(); err != nil {
		t.Fatalf("Sync failed: %v", err)
	}

	data, _ := os.ReadFile(path)
	if len(data) == 0 {
		t.Fatal("manifest empty")
	}
	// 沒有 .hyp/llm.yaml 時應該不會 panic、不會帶任何 LLM 痕跡
	if contains(string(data), "[llm]") {
		t.Error("should not have LLM-enriched content")
	}
}

func TestAutoSync_AutoDiscoversLLMConfig(t *testing.T) {
	dir := t.TempDir()
	hypDir := filepath.Join(dir, ".hyp")
	if err := os.MkdirAll(hypDir, 0755); err != nil {
		t.Fatal(err)
	}

	// 在輸出檔的同目錄放一份 mode=none 的 llm.yaml；
	// 重點是 AutoSync 應該找到並嘗試載入，不會因檔案存在而報錯
	llmYAML := "mode: none\n"
	if err := os.WriteFile(filepath.Join(hypDir, "llm.yaml"), []byte(llmYAML), 0644); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(hypDir, "context.yaml")
	r := setupAutoSyncRouter()
	a := NewAutoSync(AutoSyncConfig{Enabled: true, Path: path}, r, nil, nil)

	if err := a.Sync(); err != nil {
		t.Fatalf("Sync failed: %v", err)
	}

	if _, err := os.Stat(path); err != nil {
		t.Fatalf("context.yaml should exist: %v", err)
	}
}

func TestAutoSync_DisableLLMAutoDiscovery(t *testing.T) {
	dir := t.TempDir()
	hypDir := filepath.Join(dir, ".hyp")
	os.MkdirAll(hypDir, 0755)

	// 故意放一份格式錯誤的 llm.yaml：若有走自動探測會出現 warning（測試僅檢查不 panic）
	if err := os.WriteFile(filepath.Join(hypDir, "llm.yaml"), []byte("not: valid: yaml: ["), 0644); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(hypDir, "context.yaml")
	r := setupAutoSyncRouter()
	a := NewAutoSync(AutoSyncConfig{
		Enabled:                 true,
		Path:                    path,
		DisableLLMAutoDiscovery: true,
	}, r, nil, nil)

	if err := a.Sync(); err != nil {
		t.Fatalf("Sync with disabled auto-discovery should still succeed: %v", err)
	}
}

func TestAutoSync_ExplicitLLMConfigBeatsAutoDiscovery(t *testing.T) {
	dir := t.TempDir()
	hypDir := filepath.Join(dir, ".hyp")
	os.MkdirAll(hypDir, 0755)

	// 同目錄放一份 mode=none
	os.WriteFile(filepath.Join(hypDir, "llm.yaml"), []byte("mode: none\n"), 0644)

	// 但 AutoSyncConfig 明確提供另一份；應該優先用明確指定的
	explicit := &config.LLMConfig{Mode: config.LLMModeNone}
	explicit.ApplyDefaults()

	path := filepath.Join(hypDir, "context.yaml")
	r := setupAutoSyncRouter()
	a := NewAutoSync(AutoSyncConfig{
		Enabled:   true,
		Path:      path,
		LLMConfig: explicit,
	}, r, nil, nil)

	if err := a.Sync(); err != nil {
		t.Fatalf("Sync failed: %v", err)
	}
}

func TestAutoSync_LLMEnricher_AppliedToManifest(t *testing.T) {
	// 直接組裝一個 Collector + 自訂 enricher，驗證 LLMEnricher 確實會被呼叫
	// （AutoSync 走相同的 enrich 路徑，所以驗證 collector 已足夠）
	r := setupAutoSyncRouter()
	enrichCfg := DefaultEnrichConfig()
	enrichCfg.LLMEnricher = &stubEnricher{tag: "llm"}

	c := NewCollectorWithEnrich(r, nil, enrichCfg)
	m := c.Collect()

	found := false
	for _, route := range m.Routes {
		if contains(route.Summary, "[llm]") {
			found = true
			break
		}
	}
	if !found {
		t.Error("expected at least one route Summary to carry [llm] tag")
	}
}

func TestNewCollectorWithModelsAndLLM_NilLLM(t *testing.T) {
	r := setupAutoSyncRouter()
	c, err := NewCollectorWithModelsAndLLM(r, nil, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	if c == nil {
		t.Fatal("collector should not be nil")
	}
	if c.enrichCfg.LLMEnricher != nil {
		t.Error("LLM enricher should be nil when llmCfg is nil")
	}
}

func TestNewCollectorWithModelsAndLLM_ModeNone(t *testing.T) {
	r := setupAutoSyncRouter()
	cfg := &config.LLMConfig{Mode: config.LLMModeNone}
	c, err := NewCollectorWithModelsAndLLM(r, nil, nil, cfg)
	if err != nil {
		t.Fatal(err)
	}
	if c.enrichCfg.LLMEnricher != nil {
		t.Error("LLM enricher should be nil when mode=none")
	}
}

func contains(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}
