// @ai:generated by=claude-opus-4-6 date=2026-02-27
// @ai:modified by=claude-opus-4-7 date=2026-06-19 reason=AutoSync 自動探測 .hyp/llm.yaml 並啟用 LLM manifest 增強
package manifest

// autosync.go — .hyp/context.yaml 自動同步。
// 自 v0.8.9 由原 pkg/autosync 合併進 pkg/manifest，以收斂套件數量。
// 在 Server 啟動時自動生成專案 manifest，永遠與程式碼同步。

import (
	"os"
	"path/filepath"
	"sync/atomic"

	"github.com/maoxiaoyue/hypgo/pkg/config"
	"github.com/maoxiaoyue/hypgo/pkg/logger"
	"github.com/maoxiaoyue/hypgo/pkg/migrate"
	"github.com/maoxiaoyue/hypgo/pkg/router"
)

// maxEnricherErrorsReported AutoSync 在每次 Sync 中最多回報幾條 enricher 錯誤
// 超出後僅累積計數，最終一次 summary。避免大型專案 enricher 全部失敗時刷屏。
const maxEnricherErrorsReported = 5

// DefaultContextPath 預設的 context 檔案路徑
const DefaultContextPath = ".hyp/context.yaml"

// DefaultLLMConfigFilename LLM 設定檔在 .hyp/ 內的固定檔名
const DefaultLLMConfigFilename = "llm.yaml"

// AutoSyncConfig 配置 AutoSync 行為
type AutoSyncConfig struct {
	// Enabled 是否啟用自動同步（預設 true）
	Enabled bool

	// Path 輸出路徑（預設 .hyp/context.yaml）
	Path string

	// Format 輸出格式（"yaml" 或 "json"，預設 "yaml"）
	Format string

	// LLMConfig 選用：啟用 LLM 智慧增強，自動補完 Summary/Tags/Description。
	// 為 nil 時 AutoSync 會嘗試從輸出檔的同目錄載入 llm.yaml（預設 .hyp/llm.yaml）；
	// mode=none、檔案不存在、或載入失敗時退回純 Go 推斷。
	//
	// 注意：mode=api 時每條路由都會送一次請求，可能拖慢 Server 啟動或 genctx 執行；
	// 建議開發時用 mode=ollama 或關閉（mode=none）。
	LLMConfig *config.LLMConfig

	// DisableLLMAutoDiscovery 關閉自動探測（測試或想完全停用 LLM 增強時用）
	DisableLLMAutoDiscovery bool
}

// AutoSync 管理 .hyp/context.yaml 的自動同步
type AutoSync struct {
	config AutoSyncConfig
	router *router.Router
	appCfg *config.Config
	logger *logger.Logger
}

// NewAutoSync 建立新的 AutoSync 實例
func NewAutoSync(cfg AutoSyncConfig, r *router.Router, appCfg *config.Config, log *logger.Logger) *AutoSync {
	if cfg.Path == "" {
		cfg.Path = DefaultContextPath
	}
	if cfg.Format == "" {
		cfg.Format = "yaml"
	}

	return &AutoSync{
		config: cfg,
		router: r,
		appCfg: appCfg,
		logger: log,
	}
}

// Sync 立即同步 manifest 到檔案
// 安全考量：不包含敏感資訊（密碼、token、DSN）
// 使用原子寫入（temp file + rename）防止中途損壞
func (a *AutoSync) Sync() error {
	if !a.config.Enabled {
		return nil
	}

	// 確保目錄存在
	dir := filepath.Dir(a.config.Path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// 決定使用的 LLMConfig：明確指定 > 自動探測同目錄的 llm.yaml > nil
	llmCfg := a.resolveLLMConfig(dir)

	// 構建 collector：若 llmCfg 啟用，建立 enricher 並掛上錯誤回報 callback
	enrichCfg := DefaultEnrichConfig()
	var errCount int64

	if llmCfg != nil && llmCfg.IsEnabled() {
		reporter := a.buildErrorReporter(&errCount)
		enricher, err := NewLLMEnricherFromConfigWithReporter(llmCfg, reporter)
		if err != nil {
			if a.logger != nil {
				a.logger.Warningf("AutoSync: LLM enricher init failed (%v); using pure Go inference", err)
			}
		} else if enricher != nil {
			enrichCfg.LLMEnricher = enricher
			if a.logger != nil {
				detail := string(llmCfg.Mode)
				if llmCfg.Mode == config.LLMModeAPI {
					detail = "api/" + llmCfg.API.Provider + "/" + llmCfg.API.Model
				} else if llmCfg.Mode == config.LLMModeOllama {
					detail = "ollama/" + llmCfg.Ollama.Model
				}
				a.logger.Infof("AutoSync: LLM enrichment enabled (%s)", detail)
			}
		}
	}

	collector := NewCollectorWithModelsAndEnrich(a.router, a.appCfg, migrate.GlobalRegistry(), enrichCfg)
	m := collector.Collect()

	// 若 LLM 期間累積了錯誤，給一條 summary（避免使用者誤以為 LLM 有生效）
	if total := atomic.LoadInt64(&errCount); total > maxEnricherErrorsReported && a.logger != nil {
		a.logger.Warningf("AutoSync: %d enricher errors total (%d shown); manifest fell back to pure inference for those routes",
			total, int64(maxEnricherErrorsReported))
	}

	// Schema 完整度檢查：有缺漏時於啟動輸出建議（缺漏同時寫入 manifest 供 AI 補完）
	if a.logger != nil && m.Lint != nil && len(m.Lint.Warnings) > 0 {
		a.logger.Info(FormatLint(m.Lint))
	}

	// 原子寫入：先寫 temp file，再 rename
	// 防止寫入中途斷電或磁碟滿導致 context.yaml 損壞
	tmpPath := a.config.Path + ".tmp"
	if err := SaveToFile(tmpPath, m, a.config.Format); err != nil {
		os.Remove(tmpPath) // 清理失敗的 temp file
		return err
	}
	if err := os.Rename(tmpPath, a.config.Path); err != nil {
		os.Remove(tmpPath)
		return err
	}

	if a.logger != nil {
		a.logger.Infof("AutoSync: manifest saved to %s", a.config.Path)
	}

	return nil
}

// SyncSafe 同步但不 panic（用於非關鍵路徑）
func (a *AutoSync) SyncSafe() {
	if err := a.Sync(); err != nil {
		if a.logger != nil {
			a.logger.Warningf("AutoSync failed: %v", err)
		}
	}
}

// buildErrorReporter 回傳一個錯誤回報 callback：
// 前 N 條把錯誤完整寫進 logger.Warning；超出後僅累加 errCount，Sync 結束時統一報告數量。
func (a *AutoSync) buildErrorReporter(errCount *int64) EnricherErrorReporter {
	return func(routeKey string, err error) bool {
		n := atomic.AddInt64(errCount, 1)
		if a.logger != nil && n <= maxEnricherErrorsReported {
			a.logger.Warningf("AutoSync: LLM enrich %s: %v", routeKey, err)
		}
		return true // 繼續處理後續路由
	}
}

// resolveLLMConfig 解析 LLMConfig：優先用明確指定的；否則自動探測 dir/llm.yaml。
// 自動探測在 DisableLLMAutoDiscovery=true 或檔案不存在時靜默退回 nil。
func (a *AutoSync) resolveLLMConfig(dir string) *config.LLMConfig {
	if a.config.LLMConfig != nil {
		return a.config.LLMConfig
	}
	if a.config.DisableLLMAutoDiscovery {
		return nil
	}
	candidate := filepath.Join(dir, DefaultLLMConfigFilename)
	if _, err := os.Stat(candidate); err != nil {
		return nil
	}
	cfg, err := config.LoadLLMConfig(candidate)
	if err != nil {
		if a.logger != nil {
			a.logger.Warningf("AutoSync: failed to load %s: %v", candidate, err)
		}
		return nil
	}
	return cfg
}
