// @ai:generated by=claude-opus-4-7 date=2026-06-19
package manifest

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"

	"github.com/maoxiaoyue/hypgo/pkg/config"
)

// 模擬一個會回 500 的 OpenAI-compatible endpoint，驗證 reporter 收到錯誤
func TestAPIEnricher_ReportsHTTPError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(`{"error": "model not loaded"}`))
	}))
	defer srv.Close()

	var errs []error
	var mu sync.Mutex
	reporter := func(routeKey string, err error) bool {
		mu.Lock()
		defer mu.Unlock()
		errs = append(errs, err)
		return true
	}

	cfg := &config.LLMConfig{
		Mode: "api",
		API: config.APIConfig{
			Provider: "custom",
			BaseURL:  srv.URL,
			APIKey:   "test",
			Model:    "test-model",
			Timeout:  5,
		},
	}
	cfg.ApplyDefaults()

	enricher, err := NewLLMEnricherFromConfigWithReporter(cfg, reporter)
	if err != nil {
		t.Fatal(err)
	}
	if enricher == nil {
		t.Fatal("enricher should not be nil")
	}

	route := RouteManifest{Method: "POST", Path: "/api/users"}
	got := enricher.EnrichRoute(route)

	// 失敗時回原 route
	if got.Summary != route.Summary {
		t.Error("on failure, EnrichRoute should return original route unchanged")
	}

	mu.Lock()
	defer mu.Unlock()
	if len(errs) == 0 {
		t.Fatal("reporter should have been called on HTTP 500")
	}
	if !strings.Contains(errs[0].Error(), "500") {
		t.Errorf("error should mention status 500, got: %v", errs[0])
	}
	if !strings.Contains(errs[0].Error(), "model not loaded") {
		t.Errorf("error should include response body snippet, got: %v", errs[0])
	}
}

// reporter=nil 時應該完全沉默且不 panic（向後相容）
func TestAPIEnricher_NilReporterDoesNotPanic(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusBadGateway)
	}))
	defer srv.Close()

	cfg := &config.LLMConfig{
		Mode: "api",
		API: config.APIConfig{
			Provider: "custom",
			BaseURL:  srv.URL,
			APIKey:   "test",
			Model:    "test-model",
			Timeout:  5,
		},
	}
	cfg.ApplyDefaults()

	enricher, err := NewLLMEnricherFromConfig(cfg) // 沒傳 reporter
	if err != nil {
		t.Fatal(err)
	}

	route := RouteManifest{Method: "POST", Path: "/api/users"}
	got := enricher.EnrichRoute(route) // 不應 panic
	if got.Summary != route.Summary {
		t.Error("should return unchanged route on failure")
	}
}

// 驗證 routeKey 邏輯：REST、CLI、無 method 三種
func TestRouteKey(t *testing.T) {
	tests := []struct {
		r    RouteManifest
		want string
	}{
		{RouteManifest{Method: "POST", Path: "/api/x"}, "POST /api/x"},
		{RouteManifest{Protocol: "cli", Command: "build"}, "cli:build"},
		{RouteManifest{Protocol: "rest"}, "rest"},
	}
	for _, tt := range tests {
		if got := routeKey(tt.r); got != tt.want {
			t.Errorf("routeKey(%+v) = %q, want %q", tt.r, got, tt.want)
		}
	}
}

// AutoSync.buildErrorReporter 應該累加錯誤計數，即使 logger 為 nil 也不 panic
func TestAutoSync_ErrorReporterCounts(t *testing.T) {
	a := &AutoSync{} // logger=nil 不會 panic
	var count int64
	reporter := a.buildErrorReporter(&count)

	dummyErr := errStub("boom")
	for i := 0; i < 10; i++ {
		reporter("POST /api/x", dummyErr)
	}
	if count != 10 {
		t.Errorf("counted %d, want 10", count)
	}
}

type errStub string

func (e errStub) Error() string { return string(e) }
