// Package manifest — lint.go 提供 Schema 完整度檢查。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 在 go run .（Server.Start 的 AutoSync）時主動指出缺漏的 Schema，
//
//	讓「忘記寫 Schema」從靜默失敗變成每次啟動可見的回饋，並寫入 manifest 供 AI 自動補完
package manifest

import (
	"fmt"
	"sort"
	"strings"

	"github.com/maoxiaoyue/hypgo/pkg/router"
	"github.com/maoxiaoyue/hypgo/pkg/schema"
)

// defaultLintIgnore 預設忽略的路由前綴（本來就不需要 Schema，避免警告疲勞）
var defaultLintIgnore = []string{
	"/health",
	"/_debug",
	"/metrics",
	"/favicon.ico",
	"/ping",
}

// isLintIgnored 判斷路由是否在忽略清單中
func isLintIgnored(path string) bool {
	for _, p := range defaultLintIgnore {
		if path == p || strings.HasPrefix(path, p+"/") {
			return true
		}
	}
	return false
}

// isWritableMethod 判斷是否為通常帶請求 body 的方法
func isWritableMethod(method string) bool {
	switch method {
	case "POST", "PUT", "PATCH":
		return true
	default:
		return false
	}
}

// lintRoutes 掃描 REST 路由與 Schema Registry，回報宣告層面的缺漏。
// 僅檢查 REST 路由（非 REST 協議直接註冊於 registry，必有 schema）。
func lintRoutes(r *router.Router, reg *schema.Registry) *LintReport {
	if r == nil || reg == nil {
		return nil
	}

	rep := &LintReport{}
	seen := make(map[string]bool)

	for _, ri := range r.Routes() {
		if ri.Method == "HEAD" {
			continue // HEAD 自動回應，不需 schema
		}
		if isLintIgnored(ri.Path) {
			continue
		}
		key := ri.Method + " " + ri.Path
		if seen[key] {
			continue
		}
		seen[key] = true
		rep.Total++

		s, ok := reg.Get(ri.Method, ri.Path)
		if !ok {
			rep.Warnings = append(rep.Warnings, LintWarning{
				Route:   key,
				Kind:    "no_schema",
				Message: "路由未註冊 Schema，AI 無法理解其 Input/Output（建議改用 r.Schema(...).Handle(...)）",
			})
			continue
		}

		rep.WithSchema++

		if isWritableMethod(ri.Method) && s.InputName == "" {
			rep.Warnings = append(rep.Warnings, LintWarning{
				Route:   key,
				Kind:    "missing_input",
				Message: "可寫方法未宣告 Input，無法驗證請求 body",
			})
		}
		if ri.Method != "DELETE" && s.OutputName == "" {
			rep.Warnings = append(rep.Warnings, LintWarning{
				Route:   key,
				Kind:    "missing_output",
				Message: "未宣告 Output，Contract Testing 無法驗證回應",
			})
		}
		if s.Summary == "" {
			rep.Warnings = append(rep.Warnings, LintWarning{
				Route:   key,
				Kind:    "missing_summary",
				Message: "未填 Summary，manifest 中此路由沒有描述",
			})
		}
	}

	sort.Slice(rep.Warnings, func(i, j int) bool {
		if rep.Warnings[i].Route != rep.Warnings[j].Route {
			return rep.Warnings[i].Route < rep.Warnings[j].Route
		}
		return rep.Warnings[i].Kind < rep.Warnings[j].Kind
	})

	rep.Coverage = fmt.Sprintf("%d/%d", rep.WithSchema, rep.Total)
	return rep
}

// FormatLint 將 LintReport 格式化為可讀的多行報告（供 go run . 啟動時輸出）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 把 Schema 缺漏以人類可讀的方式呈現於終端，附帶覆蓋率正向指標而非單純羅列警告
// @ai:input LintReport（可為 nil）
// @ai:output 多行報告字串；nil 或全數通過時回傳精簡訊息
// @ai:sideeffect none
func FormatLint(rep *LintReport) string {
	if rep == nil {
		return ""
	}

	var b strings.Builder
	b.WriteString("Schema 完整度檢查\n")
	b.WriteString("─────────────────────────────────────────────\n")

	if len(rep.Warnings) == 0 {
		b.WriteString("✓ 所有可檢查路由皆已宣告完整 Schema\n")
	} else {
		for _, w := range rep.Warnings {
			icon := "⚠"
			if w.Kind == "missing_summary" {
				icon = "ℹ"
			}
			b.WriteString(fmt.Sprintf("  %s [%s] %s — %s\n", icon, w.Kind, w.Route, w.Message))
		}
	}

	b.WriteString(fmt.Sprintf("Schema 覆蓋率：%s", rep.Coverage))
	return b.String()
}
