// @ai:generated by=claude-opus-4-6 date=2026-02-27
package manifest

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/maoxiaoyue/hypgo/pkg/config"
)

// EnricherErrorReporter 在 enricher 內部錯誤發生時被呼叫
// （HTTP 失敗、回應 JSON 解析失敗、API 回傳 4xx/5xx 等）
// 為 nil 時錯誤靜默丟棄（向後相容）。
// 回傳 false 時表示「不要再回報後續錯誤」（用於限制日誌量）。
type EnricherErrorReporter func(routeKey string, err error) bool

// NewLLMEnricherFromConfig 根據 LLMConfig 建立對應的 LLMEnricher 實作
// mode=none 時回傳 nil（不使用 LLM）。錯誤訊息會被靜默丟棄；要看錯誤請用
// NewLLMEnricherFromConfigWithReporter。
func NewLLMEnricherFromConfig(cfg *config.LLMConfig) (LLMEnricher, error) {
	return NewLLMEnricherFromConfigWithReporter(cfg, nil)
}

// NewLLMEnricherFromConfigWithReporter 根據 LLMConfig 建立 enricher 並接受錯誤回報 callback
// （v0.8.11+）。AutoSync 透過 callback 把錯誤接到 logger，讓使用者看得到「LLM 為什麼沒生效」。
func NewLLMEnricherFromConfigWithReporter(cfg *config.LLMConfig, reporter EnricherErrorReporter) (LLMEnricher, error) {
	if cfg == nil || !cfg.IsEnabled() {
		return nil, nil
	}

	switch cfg.Mode {
	case "ollama":
		return newOllamaEnricher(&cfg.Ollama, reporter)
	case "api":
		return newAPIEnricher(&cfg.API, reporter)
	default:
		return nil, fmt.Errorf("unsupported LLM mode: %s", cfg.Mode)
	}
}

// reportErr 是給各 enricher 用的內部 helper：回報錯誤並依 reporter 回傳決定是否繼續
// （仍會回傳原 route，呼叫端要照樣 return route）
func reportErr(reporter EnricherErrorReporter, route RouteManifest, err error) {
	if reporter == nil || err == nil {
		return
	}
	reporter(routeKey(route), err)
}

func routeKey(r RouteManifest) string {
	if r.Method != "" && r.Path != "" {
		return r.Method + " " + r.Path
	}
	if r.Command != "" {
		return r.Protocol + ":" + r.Command
	}
	return r.Protocol
}

// --- Prompt Builder ---

// buildEnrichPrompt 將路由資訊組成給 LLM 的 prompt
func buildEnrichPrompt(route RouteManifest) string {
	var sb strings.Builder
	sb.WriteString("You are a technical API documentation writer. ")
	sb.WriteString("Based on the following route information, generate a concise summary and description. ")
	sb.WriteString("Respond in JSON format: {\"summary\": \"...\", \"description\": \"...\"}\n\n")

	sb.WriteString("Route:\n")

	proto := route.Protocol
	if proto == "" {
		proto = "rest"
	}
	sb.WriteString(fmt.Sprintf("  Protocol: %s\n", proto))

	if route.Method != "" {
		sb.WriteString(fmt.Sprintf("  Method: %s\n", route.Method))
	}
	if route.Path != "" {
		sb.WriteString(fmt.Sprintf("  Path: %s\n", route.Path))
	}
	if route.Command != "" {
		sb.WriteString(fmt.Sprintf("  Command: %s\n", route.Command))
	}
	if route.InputType != "" {
		sb.WriteString(fmt.Sprintf("  InputType: %s\n", route.InputType))
	}
	if route.OutputType != "" {
		sb.WriteString(fmt.Sprintf("  OutputType: %s\n", route.OutputType))
	}
	if len(route.HandlerNames) > 0 {
		sb.WriteString(fmt.Sprintf("  Handler: %s\n", route.HandlerNames[0]))
	}
	if len(route.Tags) > 0 {
		sb.WriteString(fmt.Sprintf("  Tags: %s\n", strings.Join(route.Tags, ", ")))
	}
	if route.Summary != "" {
		sb.WriteString(fmt.Sprintf("  CurrentSummary: %s\n", route.Summary))
	}

	return sb.String()
}

// llmResponse 是 LLM 回覆的 JSON 結構
type llmResponse struct {
	Summary     string `json:"summary"`
	Description string `json:"description"`
}

// parseEnrichResponse 解析 LLM 回覆並回填到 RouteManifest
func parseEnrichResponse(response string, route RouteManifest) RouteManifest {
	// 嘗試從回覆中提取 JSON
	jsonStr := extractJSON(response)
	if jsonStr == "" {
		return route
	}

	var resp llmResponse
	if err := json.Unmarshal([]byte(jsonStr), &resp); err != nil {
		return route
	}

	// 只在空白時回填
	if route.Summary == "" && resp.Summary != "" {
		route.Summary = sanitizeResponse(resp.Summary)
	}
	if route.Description == "" && resp.Description != "" {
		route.Description = sanitizeResponse(resp.Description)
	}

	return route
}

// extractJSON 從 LLM 回覆中提取 JSON 物件
func extractJSON(s string) string {
	start := strings.Index(s, "{")
	if start < 0 {
		return ""
	}
	end := strings.LastIndex(s, "}")
	if end < 0 || end <= start {
		return ""
	}
	return s[start : end+1]
}

// sanitizeResponse 清理 LLM 回覆，防止注入
func sanitizeResponse(s string) string {
	s = strings.TrimSpace(s)
	// 移除潛在的 HTML/script 標籤
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	// 限制長度
	if len(s) > 500 {
		s = s[:500]
	}
	return s
}

// ============================================================
// OllamaEnricher — 連接本地 Ollama
// ============================================================

type OllamaEnricher struct {
	url       string
	model     string
	timeout   time.Duration
	maxTokens int
	client    *http.Client
	reporter  EnricherErrorReporter
}

func newOllamaEnricher(cfg *config.OllamaConfig, reporter EnricherErrorReporter) (*OllamaEnricher, error) {
	if cfg.Model == "" {
		return nil, fmt.Errorf("ollama model is required")
	}
	timeout := time.Duration(cfg.Timeout) * time.Second
	if timeout == 0 {
		timeout = 30 * time.Second
	}
	return &OllamaEnricher{
		url:       cfg.URL,
		model:     cfg.Model,
		timeout:   timeout,
		maxTokens: cfg.MaxTokens,
		client:    &http.Client{Timeout: timeout},
		reporter:  reporter,
	}, nil
}

// ollamaRequest Ollama /api/generate 請求
type ollamaRequest struct {
	Model   string         `json:"model"`
	Prompt  string         `json:"prompt"`
	Stream  bool           `json:"stream"`
	Options map[string]int `json:"options,omitempty"`
}

// ollamaResponse Ollama /api/generate 回應
type ollamaResponse struct {
	Response string `json:"response"`
}

func (e *OllamaEnricher) EnrichRoute(route RouteManifest) RouteManifest {
	prompt := buildEnrichPrompt(route)

	reqBody := ollamaRequest{
		Model:  e.model,
		Prompt: prompt,
		Stream: false,
	}
	if e.maxTokens > 0 {
		reqBody.Options = map[string]int{"num_predict": e.maxTokens}
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("ollama: marshal request: %w", err))
		return route
	}

	resp, err := e.client.Post(e.url+"/api/generate", "application/json", bytes.NewReader(body))
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("ollama POST %s/api/generate: %w", e.url, err))
		return route
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		snippet, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
		reportErr(e.reporter, route, fmt.Errorf("ollama returned %d: %s", resp.StatusCode, strings.TrimSpace(string(snippet))))
		return route
	}

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20)) // 1MB limit
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("ollama read response: %w", err))
		return route
	}

	var ollamaResp ollamaResponse
	if err := json.Unmarshal(respBody, &ollamaResp); err != nil {
		reportErr(e.reporter, route, fmt.Errorf("ollama parse JSON: %w", err))
		return route
	}

	return parseEnrichResponse(ollamaResp.Response, route)
}

// ============================================================
// APIEnricher — 連接遠端 API（OpenAI / Anthropic / Gemini / Custom）
// ============================================================

type APIEnricher struct {
	provider  string
	baseURL   string
	apiKey    string
	model     string
	timeout   time.Duration
	maxTokens int
	client    *http.Client
	reporter  EnricherErrorReporter
}

func newAPIEnricher(cfg *config.APIConfig, reporter EnricherErrorReporter) (*APIEnricher, error) {
	if cfg.Model == "" {
		return nil, fmt.Errorf("api model is required")
	}
	apiKey := cfg.ResolvedAPIKey()
	if apiKey == "" {
		return nil, fmt.Errorf("api key is required")
	}
	timeout := time.Duration(cfg.Timeout) * time.Second
	if timeout == 0 {
		timeout = 30 * time.Second
	}
	return &APIEnricher{
		provider:  cfg.Provider,
		baseURL:   cfg.BaseURL,
		apiKey:    apiKey,
		model:     cfg.Model,
		timeout:   timeout,
		maxTokens: cfg.MaxTokens,
		client:    &http.Client{Timeout: timeout},
		reporter:  reporter,
	}, nil
}

func (e *APIEnricher) EnrichRoute(route RouteManifest) RouteManifest {
	prompt := buildEnrichPrompt(route)

	switch e.provider {
	case "anthropic":
		return e.enrichAnthropic(prompt, route)
	default:
		// OpenAI / Gemini / Custom 都用 OpenAI-compatible format
		return e.enrichOpenAI(prompt, route)
	}
}

// openAIChatRequest OpenAI chat completion 請求
type openAIChatRequest struct {
	Model       string          `json:"model"`
	Messages    []openAIMessage `json:"messages"`
	MaxTokens   int             `json:"max_tokens,omitempty"`
	Temperature float64         `json:"temperature"`
}

type openAIMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type openAIChatResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
}

func (e *APIEnricher) enrichOpenAI(prompt string, route RouteManifest) RouteManifest {
	reqBody := openAIChatRequest{
		Model: e.model,
		Messages: []openAIMessage{
			{Role: "user", Content: prompt},
		},
		MaxTokens:   e.maxTokens,
		Temperature: 0.3,
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("openai-compatible: marshal request: %w", err))
		return route
	}

	url := e.baseURL + "/chat/completions"
	req, err := http.NewRequest("POST", url, bytes.NewReader(body))
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("openai-compatible: build request: %w", err))
		return route
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+e.apiKey)

	resp, err := e.client.Do(req)
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("openai-compatible POST %s: %w", url, err))
		return route
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		snippet, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
		reportErr(e.reporter, route, fmt.Errorf("openai-compatible %s returned %d: %s", url, resp.StatusCode, strings.TrimSpace(string(snippet))))
		return route
	}

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("openai-compatible: read response: %w", err))
		return route
	}

	var chatResp openAIChatResponse
	if err := json.Unmarshal(respBody, &chatResp); err != nil {
		reportErr(e.reporter, route, fmt.Errorf("openai-compatible: parse JSON: %w (body: %.200s)", err, string(respBody)))
		return route
	}

	if len(chatResp.Choices) == 0 {
		reportErr(e.reporter, route, fmt.Errorf("openai-compatible: response has no choices (body: %.200s)", string(respBody)))
		return route
	}

	return parseEnrichResponse(chatResp.Choices[0].Message.Content, route)
}

// anthropicRequest Anthropic messages 請求
type anthropicRequest struct {
	Model     string         `json:"model"`
	Messages  []anthropicMsg `json:"messages"`
	MaxTokens int            `json:"max_tokens"`
}

type anthropicMsg struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type anthropicResponse struct {
	Content []struct {
		Text string `json:"text"`
	} `json:"content"`
}

func (e *APIEnricher) enrichAnthropic(prompt string, route RouteManifest) RouteManifest {
	reqBody := anthropicRequest{
		Model: e.model,
		Messages: []anthropicMsg{
			{Role: "user", Content: prompt},
		},
		MaxTokens: e.maxTokens,
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("anthropic: marshal request: %w", err))
		return route
	}

	url := e.baseURL + "/messages"
	req, err := http.NewRequest("POST", url, bytes.NewReader(body))
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("anthropic: build request: %w", err))
		return route
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", e.apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")

	resp, err := e.client.Do(req)
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("anthropic POST %s: %w", url, err))
		return route
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		snippet, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
		reportErr(e.reporter, route, fmt.Errorf("anthropic %s returned %d: %s", url, resp.StatusCode, strings.TrimSpace(string(snippet))))
		return route
	}

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		reportErr(e.reporter, route, fmt.Errorf("anthropic: read response: %w", err))
		return route
	}

	var anthropicResp anthropicResponse
	if err := json.Unmarshal(respBody, &anthropicResp); err != nil {
		reportErr(e.reporter, route, fmt.Errorf("anthropic: parse JSON: %w", err))
		return route
	}

	if len(anthropicResp.Content) == 0 {
		reportErr(e.reporter, route, fmt.Errorf("anthropic: response has no content"))
		return route
	}

	return parseEnrichResponse(anthropicResp.Content[0].Text, route)
}

