// @ai:generated by=claude-opus-4-6 date=2026-02-27
package hidb

import (
	"context"
	"database/sql"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"github.com/maoxiaoyue/hypgo/pkg/config"
	"github.com/uptrace/bun"
)

// 健康檢查參數（刻意不做成設定：保持零配置，數值為業界常見預設）
const (
	healthCheckInterval  = 5 * time.Second        // 探測週期
	healthPingTimeout    = 2 * time.Second        // 單次 ping 逾時
	healthFailThreshold  = 3                      // 連續失敗 N 次後摘除
)

// replicaHealth 單一副本的健康狀態
// 以指標共享：ReadReplica 以值複製進 copy-on-write slice，
// 狀態必須跨副本存活。down 用 atomic 供無鎖讀路徑判斷；
// fails 只由健康檢查 goroutine 單執行緒讀寫，不需同步
type replicaHealth struct {
	down  atomic.Bool
	fails int
}

// ReadReplica 讀取副本連接
type ReadReplica struct {
	sqlDB  *sql.DB
	hypDB  *bun.DB
	health *replicaHealth
}

// ReplicaPool 讀取副本連接池（支持輪詢負載均衡 + 被動健康剔除）
// GC 優化：讀路徑使用 atomic.Pointer 避免 RWMutex 競爭
// 寫操作（Add/Close）仍使用 Mutex 保護
//
// 健康剔除：StartHealthCheck 啟動背景探測，連續 ping 失敗達門檻的
// 副本被標記 down，Next/NextSQL 輪詢時跳過（一次成功即恢復）。
// 全部副本 down 時回傳 nil，呼叫端（ReadHypDB/ReadSQL）自然回退主庫。
// 未啟動健康檢查時行為與舊版相同（全部視為健康）
type ReplicaPool struct {
	replicas atomic.Pointer[[]ReadReplica] // GC 優化：讀路徑無鎖
	counter  atomic.Uint64
	mu       sync.Mutex // 僅保護寫操作
	stopOnce sync.Once
	stopCh   chan struct{} // nil = 健康檢查未啟動
}

// NewReplicaPool 創建讀取副本池
func NewReplicaPool() *ReplicaPool {
	rp := &ReplicaPool{}
	empty := make([]ReadReplica, 0)
	rp.replicas.Store(&empty)
	return rp
}

// Add 添加讀取副本
// 寫操作：使用 Mutex 保護，copy-on-write 更新 atomic.Pointer
func (rp *ReplicaPool) Add(replica ReadReplica) {
	rp.mu.Lock()
	defer rp.mu.Unlock()

	if replica.health == nil {
		replica.health = &replicaHealth{}
	}

	old := rp.replicas.Load()
	newSlice := make([]ReadReplica, len(*old)+1)
	copy(newSlice, *old)
	newSlice[len(*old)] = replica
	rp.replicas.Store(&newSlice)
}

// Next 獲取下一個健康的讀取副本 HypDB ORM 實例（輪詢，跳過 down 副本）
// GC 優化：讀路徑完全無鎖。全部不健康時回傳 nil（呼叫端回退主庫）
func (rp *ReplicaPool) Next() *bun.DB {
	replicas := *rp.replicas.Load()
	n := uint64(len(replicas))
	if n == 0 {
		return nil
	}
	start := rp.counter.Add(1) - 1
	for i := uint64(0); i < n; i++ {
		r := replicas[(start+i)%n]
		if !r.health.down.Load() {
			return r.hypDB
		}
	}
	return nil
}

// NextSQL 獲取下一個健康的讀取副本原始 SQL 連接（輪詢，跳過 down 副本）
// GC 優化：讀路徑完全無鎖。全部不健康時回傳 nil（呼叫端回退主庫）
func (rp *ReplicaPool) NextSQL() *sql.DB {
	replicas := *rp.replicas.Load()
	n := uint64(len(replicas))
	if n == 0 {
		return nil
	}
	start := rp.counter.Add(1) - 1
	for i := uint64(0); i < n; i++ {
		r := replicas[(start+i)%n]
		if !r.health.down.Load() {
			return r.sqlDB
		}
	}
	return nil
}

// StartHealthCheck 啟動背景健康探測 goroutine（冪等：重複呼叫無效果）。
// 停止方式：Close()。未呼叫本方法時，Pool 行為與無健康檢查的舊版相同
func (rp *ReplicaPool) StartHealthCheck() {
	rp.mu.Lock()
	defer rp.mu.Unlock()
	if rp.stopCh != nil {
		return
	}
	rp.stopCh = make(chan struct{})
	go rp.healthLoop(rp.stopCh)
}

// healthLoop 週期性探測所有副本直到 stop 訊號
func (rp *ReplicaPool) healthLoop(stop <-chan struct{}) {
	ticker := time.NewTicker(healthCheckInterval)
	defer ticker.Stop()
	for {
		select {
		case <-stop:
			return
		case <-ticker.C:
			rp.checkAll()
		}
	}
}

// checkAll 對所有副本做一輪 ping：連續失敗達門檻標記 down，一次成功即恢復。
// 只由 healthLoop 單一 goroutine 呼叫（fails 因此不需同步）
func (rp *ReplicaPool) checkAll() {
	for _, r := range *rp.replicas.Load() {
		if r.sqlDB == nil {
			continue
		}
		ctx, cancel := context.WithTimeout(context.Background(), healthPingTimeout)
		err := r.sqlDB.PingContext(ctx)
		cancel()

		if err != nil {
			r.health.fails++
			if r.health.fails >= healthFailThreshold {
				r.health.down.Store(true)
			}
		} else {
			r.health.fails = 0
			r.health.down.Store(false)
		}
	}
}

// HealthyCount 回傳目前健康（未被摘除）的副本數量
func (rp *ReplicaPool) HealthyCount() int {
	count := 0
	for _, r := range *rp.replicas.Load() {
		if !r.health.down.Load() {
			count++
		}
	}
	return count
}

// Len 返回副本數量
func (rp *ReplicaPool) Len() int {
	return len(*rp.replicas.Load())
}

// Close 關閉所有讀取副本連接（並停止健康檢查 goroutine）
func (rp *ReplicaPool) Close() []error {
	rp.mu.Lock()
	defer rp.mu.Unlock()

	if rp.stopCh != nil {
		rp.stopOnce.Do(func() { close(rp.stopCh) })
	}

	replicas := *rp.replicas.Load()
	var errs []error
	for i, replica := range replicas {
		if replica.hypDB != nil {
			if err := replica.hypDB.Close(); err != nil {
				errs = append(errs, fmt.Errorf("failed to close read replica %d: %w", i, err))
			}
		}
	}
	empty := make([]ReadReplica, 0)
	rp.replicas.Store(&empty)
	return errs
}

// PingAll 對所有讀取副本進行健康檢查
func (rp *ReplicaPool) PingAll() []error {
	replicas := *rp.replicas.Load()
	var errs []error
	for i, replica := range replicas {
		if replica.sqlDB != nil {
			if err := replica.sqlDB.Ping(); err != nil {
				errs = append(errs, fmt.Errorf("read replica %d unhealthy: %w", i, err))
			}
		}
	}
	return errs
}

// initReplica 初始化單個讀取副本（使用 Dialect）
func initReplica(dialect Dialect, replicaCfg config.ReplicaConfig) (ReadReplica, error) {
	if replicaCfg.DSN == "" {
		return ReadReplica{}, fmt.Errorf("replica DSN is required")
	}

	db, err := sql.Open(dialect.DriverName(), replicaCfg.DSN)
	if err != nil {
		return ReadReplica{}, fmt.Errorf("failed to open read replica: %w", err)
	}

	// 設置連接池參數
	if replicaCfg.MaxIdleConns > 0 {
		db.SetMaxIdleConns(replicaCfg.MaxIdleConns)
	}
	if replicaCfg.MaxOpenConns > 0 {
		db.SetMaxOpenConns(replicaCfg.MaxOpenConns)
	}

	// GC 優化：Replica 也設定 ConnMaxLifetime，防止長連線持有過期狀態
	db.SetConnMaxLifetime(30 * time.Minute)

	// 測試連接
	if err := db.Ping(); err != nil {
		db.Close()
		return ReadReplica{}, fmt.Errorf("failed to ping read replica: %w", err)
	}

	// 創建 HypDB ORM 實例
	hypDB := bun.NewDB(db, dialect.BunDialect())

	return ReadReplica{
		sqlDB: db,
		hypDB: hypDB,
	}, nil
}
