// Package lintdeep 提供 `hyp lint --deep` 的靜態（編譯期）Schema↔Handler 對齊檢查。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 把「handler 綁錯 / 未綁定 Schema 宣告的 Input」這個原本只有 runtime
//
//	BindInput reporter（需實際請求才觸發）能抓到的靜默失敗，提升為「不需啟動 server、
//	不需流量」即可在 CI 攔截的編譯期檢查。本套件刻意獨立於 pkg/manifest，避免讓
//	server 執行檔背上 go/packages 這套重型分析依賴（manifest 被 server import）。
package lintdeep

import (
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	// schemaPkgPath / contextPkgPath 用於以型別路徑精準辨識框架的 Route 與 Context
	schemaPkgPath  = "github.com/maoxiaoyue/hypgo/pkg/schema"
	contextPkgPath = "github.com/maoxiaoyue/hypgo/pkg/context"

	// KindInputMismatch handler 以 BindInput 綁定的型別與 Schema 宣告的 Input 不符
	KindInputMismatch = "deep:input_mismatch"
	// KindNoBindInput 可寫方法的 schema handler 完全未呼叫 BindInput
	KindNoBindInput = "deep:no_bindinput"
)

// Finding 單一深層檢查發現（視為 hard failure）。
type Finding struct {
	Route   string // "POST /api/users"
	Kind    string // KindInputMismatch | KindNoBindInput
	Message string
	Pos     string // file:line（Schema 宣告位置）
}

// Skipped 無法靜態解析的 Schema 路由（誠實揭露，不靜默計入「通過」）。
type Skipped struct {
	Route  string
	Reason string
	Pos    string
}

// Report 深層 lint 結果。
type Report struct {
	Analyzed   int       // 成功解析並檢查的 Schema 路由數
	Findings   []Finding // hard failures
	Skipped    []Skipped // 無法靜態解析者
	LoadErrors []string  // 套件載入/編譯錯誤（有錯時深層結果不可盡信）
}

// HasFindings 回報是否存在 hard failure（供 CLI 決定 exit code）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 讓 CI gate 以單一布林判斷是否該回非零 exit code
// @ai:input none
// @ai:output bool（true 表示至少一個 Finding）
// @ai:sideeffect none
func (r *Report) HasFindings() bool {
	return r != nil && len(r.Findings) > 0
}

// funcDef 記錄一個函式宣告與其所屬套件（供解析具名 handler 的本體與型別資訊）。
type funcDef struct {
	decl *ast.FuncDecl
	pkg  *packages.Package
}

// Analyze 對 patterns（預設 "./..."）做靜態 Schema↔Handler 對齊檢查。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 載入目標套件的完整型別資訊，找出所有 r.Schema(schema.Route{...}).Handle(h)，
//
//	靜態比對 handler 是否以 c.BindInput 綁定到 Schema 所宣告的 Input 型別，
//	藉此在編譯期攔截綁錯/未綁的靜默失敗
//
// @ai:input dir 為載入工作目錄（go module 內任一路徑）；patterns 為 go 套件樣式（如 "./..."）
// @ai:output *Report（findings / skipped / load errors）；套件載入失敗時回傳 error
// @ai:sideeffect 讀取檔案系統並驅動 go list（packages.Load 內部），無任何寫入
func Analyze(dir string, patterns ...string) (*Report, error) {
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}
	fset := token.NewFileSet()
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports | packages.NeedDeps,
		Dir:  dir,
		Fset: fset,
	}
	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		return nil, fmt.Errorf("load packages: %w", err)
	}

	rep := &Report{}
	packages.Visit(pkgs, nil, func(p *packages.Package) {
		for _, e := range p.Errors {
			rep.LoadErrors = append(rep.LoadErrors, e.Error())
		}
	})

	idx := buildFuncIndex(pkgs)

	for _, p := range pkgs {
		if p.TypesInfo == nil {
			continue
		}
		for _, file := range p.Syntax {
			analyzeFile(file, p, idx, rep)
		}
	}

	sort.Slice(rep.Findings, func(i, j int) bool {
		if rep.Findings[i].Route != rep.Findings[j].Route {
			return rep.Findings[i].Route < rep.Findings[j].Route
		}
		return rep.Findings[i].Kind < rep.Findings[j].Kind
	})
	sort.Slice(rep.Skipped, func(i, j int) bool {
		return rep.Skipped[i].Route < rep.Skipped[j].Route
	})
	return rep, nil
}

// buildFuncIndex 建立 函式物件 → 宣告 的索引，供解析具名 handler 的函式本體。
// 跨已載入套件共享同一 types.Object 實例，因此可解析「Schema 與 handler 不同檔/不同套件」的情形。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func buildFuncIndex(pkgs []*packages.Package) map[types.Object]funcDef {
	idx := map[types.Object]funcDef{}
	packages.Visit(pkgs, nil, func(p *packages.Package) {
		if p.TypesInfo == nil || len(p.Syntax) == 0 {
			return
		}
		for _, file := range p.Syntax {
			for _, decl := range file.Decls {
				fd, ok := decl.(*ast.FuncDecl)
				if !ok || fd.Body == nil {
					continue
				}
				if obj := p.TypesInfo.Defs[fd.Name]; obj != nil {
					idx[obj] = funcDef{decl: fd, pkg: p}
				}
			}
		}
	})
	return idx
}

// analyzeFile 掃描單一檔案，找出 r.Schema(schema.Route{...}).Handle(h) 呼叫並交由 inspectSchemaRoute 檢查。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func analyzeFile(file *ast.File, p *packages.Package, idx map[types.Object]funcDef, rep *Report) {
	ast.Inspect(file, func(n ast.Node) bool {
		handleCall, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := handleCall.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "Handle" {
			return true
		}
		schemaCall, ok := sel.X.(*ast.CallExpr)
		if !ok {
			return true
		}
		schemaSel, ok := schemaCall.Fun.(*ast.SelectorExpr)
		if !ok || schemaSel.Sel.Name != "Schema" || len(schemaCall.Args) != 1 {
			return true
		}
		lit, ok := schemaCall.Args[0].(*ast.CompositeLit)
		if !ok {
			return true
		}
		if !isSchemaRoute(p.TypesInfo.TypeOf(lit)) {
			return true
		}
		inspectSchemaRoute(lit, handleCall, p, idx, rep)
		return true
	})
}

// inspectSchemaRoute 從 schema.Route literal 取出 Method/Path/Input，解析終端 handler 並比對綁定。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func inspectSchemaRoute(lit *ast.CompositeLit, handleCall *ast.CallExpr, p *packages.Package, idx map[types.Object]funcDef, rep *Report) {
	var method, path string
	var inputExpr ast.Expr
	for _, el := range lit.Elts {
		kv, ok := el.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		switch key.Name {
		case "Method":
			method = stringLit(kv.Value)
		case "Path":
			path = stringLit(kv.Value)
		case "Input":
			inputExpr = kv.Value
		}
	}

	pos := p.Fset.Position(lit.Pos()).String()
	route := strings.TrimSpace(strings.ToUpper(method) + " " + path)
	if route == "" {
		route = "(non-literal route @ " + pos + ")"
	}

	// 沒宣告 Input 的路由由 shallow lint 的 missing_input 負責，深層不重複檢查
	if inputExpr == nil {
		return
	}
	inputType := derefNamed(p.TypesInfo.TypeOf(inputExpr))
	if inputType == nil {
		rep.Skipped = append(rep.Skipped, Skipped{Route: route, Reason: "Input 型別無法解析為具名型別", Pos: pos})
		return
	}

	if len(handleCall.Args) == 0 {
		rep.Skipped = append(rep.Skipped, Skipped{Route: route, Reason: "Handle 未提供 handler", Pos: pos})
		return
	}
	if handleCall.Ellipsis.IsValid() {
		rep.Skipped = append(rep.Skipped, Skipped{Route: route, Reason: "handler 以 slice 展開傳入，無法靜態定位終端 handler", Pos: pos})
		return
	}
	handlerExpr := handleCall.Args[len(handleCall.Args)-1]

	body, hpkg, ok := resolveHandlerBody(handlerExpr, p, idx)
	if !ok {
		rep.Skipped = append(rep.Skipped, Skipped{Route: route, Reason: "handler 非具名函式/inline 函式，或定義於未分析的套件", Pos: pos})
		return
	}

	rep.Analyzed++
	boundTypes := collectBindInputArgTypes(body, hpkg)

	if len(boundTypes) == 0 {
		if isWritable(strings.ToUpper(method)) {
			rep.Findings = append(rep.Findings, Finding{
				Route:   route,
				Kind:    KindNoBindInput,
				Message: fmt.Sprintf("handler 未呼叫 c.BindInput，宣告的 Input(%s) 不會被解析或驗證（Contract Testing 抓不到此缺口）", typeName(inputType)),
				Pos:     pos,
			})
		}
		return
	}

	for _, bt := range boundTypes {
		if types.Identical(bt, inputType) {
			return // 至少一個 BindInput 綁到宣告型別 → 通過
		}
	}

	got := make([]string, 0, len(boundTypes))
	for _, bt := range boundTypes {
		got = append(got, typeName(bt))
	}
	rep.Findings = append(rep.Findings, Finding{
		Route:   route,
		Kind:    KindInputMismatch,
		Message: fmt.Sprintf("Schema 宣告 Input=%s，但 handler 以 c.BindInput 綁定 %s（型別不符，請求 body 會靜默綁錯）", typeName(inputType), strings.Join(got, ", ")),
		Pos:     pos,
	})
}

// resolveHandlerBody 將 handler 運算式解析為函式本體（支援 inline func literal、同/跨套件具名函式與 method value）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func resolveHandlerBody(expr ast.Expr, p *packages.Package, idx map[types.Object]funcDef) (*ast.BlockStmt, *packages.Package, bool) {
	switch h := expr.(type) {
	case *ast.FuncLit:
		return h.Body, p, true
	case *ast.Ident:
		if obj := p.TypesInfo.Uses[h]; obj != nil {
			if fd, ok := idx[obj]; ok {
				return fd.decl.Body, fd.pkg, true
			}
		}
	case *ast.SelectorExpr:
		if obj := p.TypesInfo.Uses[h.Sel]; obj != nil {
			if fd, ok := idx[obj]; ok {
				return fd.decl.Body, fd.pkg, true
			}
		}
	}
	return nil, nil, false
}

// collectBindInputArgTypes 掃描函式本體，回傳所有 c.BindInput(arg) 的 arg 去指標後具名型別。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func collectBindInputArgTypes(body *ast.BlockStmt, p *packages.Package) []*types.Named {
	var out []*types.Named
	ast.Inspect(body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok || len(call.Args) != 1 {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "BindInput" {
			return true
		}
		if !isContextBindInput(sel, p) {
			return true
		}
		if t := derefNamed(p.TypesInfo.TypeOf(call.Args[0])); t != nil {
			out = append(out, t)
		}
		return true
	})
	return out
}

// isContextBindInput 確認 selector 指向的是 pkg/context.Context 的 BindInput method（排除同名巧合）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func isContextBindInput(sel *ast.SelectorExpr, p *packages.Package) bool {
	fn, ok := p.TypesInfo.Uses[sel.Sel].(*types.Func)
	if !ok {
		return false
	}
	sig, ok := fn.Type().(*types.Signature)
	if !ok || sig.Recv() == nil {
		return false
	}
	recv := derefNamed(sig.Recv().Type())
	if recv == nil || recv.Obj() == nil || recv.Obj().Pkg() == nil {
		return false
	}
	return recv.Obj().Name() == "Context" && recv.Obj().Pkg().Path() == contextPkgPath
}

// isSchemaRoute 判斷型別是否為 pkg/schema.Route。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func isSchemaRoute(t types.Type) bool {
	named, ok := t.(*types.Named)
	if !ok || named.Obj() == nil || named.Obj().Pkg() == nil {
		return false
	}
	return named.Obj().Name() == "Route" && named.Obj().Pkg().Path() == schemaPkgPath
}

// derefNamed 去除指標層後回傳具名型別（非具名則回 nil）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func derefNamed(t types.Type) *types.Named {
	if t == nil {
		return nil
	}
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}
	named, _ := t.(*types.Named)
	return named
}

// stringLit 取出字串字面值（非字串字面值回空字串）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func stringLit(e ast.Expr) string {
	bl, ok := e.(*ast.BasicLit)
	if !ok || bl.Kind != token.STRING {
		return ""
	}
	s, err := strconv.Unquote(bl.Value)
	if err != nil {
		return strings.Trim(bl.Value, "\"`")
	}
	return s
}

// isWritable 判斷是否為通常帶請求 body 的方法（與 pkg/manifest 的 shallow lint 一致）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func isWritable(method string) bool {
	switch method {
	case "POST", "PUT", "PATCH":
		return true
	default:
		return false
	}
}

// typeName 產生 套件.型別 形式的可讀名稱。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func typeName(t types.Type) string {
	named, ok := t.(*types.Named)
	if !ok || named.Obj() == nil {
		return t.String()
	}
	if named.Obj().Pkg() != nil {
		return named.Obj().Pkg().Name() + "." + named.Obj().Name()
	}
	return named.Obj().Name()
}

// Format 將 Report 格式化為人類可讀的多行報告（供 CLI 輸出）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 以正向指標（已分析數）＋ 明列略過項，呈現深層檢查結果，避免「綠燈＝全覆蓋」的假象
// @ai:input *Report（可為 nil）
// @ai:output 多行報告字串
// @ai:sideeffect none
func Format(rep *Report) string {
	if rep == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("深層 Schema↔Handler 檢查（--deep）\n")
	b.WriteString("─────────────────────────────────────────────\n")

	if len(rep.LoadErrors) > 0 {
		b.WriteString(fmt.Sprintf("⚠ 套件載入有 %d 個錯誤（深層結果可能不完整）：\n", len(rep.LoadErrors)))
		for _, e := range rep.LoadErrors {
			b.WriteString("    " + e + "\n")
		}
	}

	if len(rep.Findings) == 0 {
		b.WriteString(fmt.Sprintf("✓ 已分析 %d 條 Schema 路由，handler 綁定皆對齊宣告\n", rep.Analyzed))
	} else {
		for _, f := range rep.Findings {
			b.WriteString(fmt.Sprintf("  ⚠ [%s] %s — %s\n      ↳ %s\n", f.Kind, f.Route, f.Message, f.Pos))
		}
	}

	if len(rep.Skipped) > 0 {
		b.WriteString(fmt.Sprintf("略過（無法靜態解析，未計入通過）：%d 條\n", len(rep.Skipped)))
		for _, s := range rep.Skipped {
			b.WriteString(fmt.Sprintf("  - %s：%s（%s）\n", s.Route, s.Reason, s.Pos))
		}
	}

	b.WriteString(fmt.Sprintf("深層檢查：分析 %d 條、問題 %d 個、略過 %d 條", rep.Analyzed, len(rep.Findings), len(rep.Skipped)))
	return b.String()
}
