package lintdeep

import "testing"

// @ai:generated by=claude-opus-4-8 date=2026-06-15
func TestAnalyzeDetectsMismatchAndMissingBind(t *testing.T) {
	rep, err := Analyze("testdata/sample", ".")
	if err != nil {
		t.Fatalf("Analyze error: %v", err)
	}
	if len(rep.LoadErrors) > 0 {
		t.Fatalf("unexpected load errors: %v", rep.LoadErrors)
	}

	// good / bad / nobind / inline 四條皆應可靜態解析
	if rep.Analyzed != 4 {
		t.Errorf("Analyzed = %d, want 4 (skipped: %+v)", rep.Analyzed, rep.Skipped)
	}
	if len(rep.Skipped) != 0 {
		t.Errorf("Skipped = %+v, want none", rep.Skipped)
	}

	byKind := map[string]int{}
	byRoute := map[string]string{}
	for _, f := range rep.Findings {
		byKind[f.Kind]++
		byRoute[f.Route] = f.Kind
	}

	if byKind[KindInputMismatch] != 1 {
		t.Errorf("input_mismatch count = %d, want 1 (findings: %+v)", byKind[KindInputMismatch], rep.Findings)
	}
	if byKind[KindNoBindInput] != 1 {
		t.Errorf("no_bindinput count = %d, want 1 (findings: %+v)", byKind[KindNoBindInput], rep.Findings)
	}
	if byRoute["POST /bad"] != KindInputMismatch {
		t.Errorf("POST /bad should be input_mismatch, got %q", byRoute["POST /bad"])
	}
	if byRoute["POST /nobind"] != KindNoBindInput {
		t.Errorf("POST /nobind should be no_bindinput, got %q", byRoute["POST /nobind"])
	}
	// 具名正確 + inline 正確的兩條都不該出現在 findings
	if k, ok := byRoute["POST /good"]; ok {
		t.Errorf("POST /good should pass, but got finding %q", k)
	}
	if k, ok := byRoute["PUT /inline"]; ok {
		t.Errorf("PUT /inline should pass, but got finding %q", k)
	}

	if !rep.HasFindings() {
		t.Error("HasFindings() = false, want true (有 bad/nobind)")
	}
}
