// Package context — BindInput 提供 Schema-first 路由的標準化請求綁定入口。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 收斂「解析 + 驗證 + 對齊 Schema 宣告 + 錯誤格式」為單一慣例，
//
//	補上 Contract Testing 結構上抓不到的「handler 綁錯 struct 靜默失敗」缺口
package context

import (
	stderrors "errors"
	"net/http"
	"reflect"

	"github.com/go-playground/validator/v10"
	hypvalidate "github.com/maoxiaoyue/hypgo/pkg/validate"
)

// BindInputReporter 在 handler 綁定的型別與 Schema 宣告不符時被呼叫。
// 以 hook 形式提供，讓 server/app 可接到 logger，而 pkg/context 不需依賴 pkg/logger（避免循環依賴）。
type BindInputReporter func(routeKey, declared, bound string)

var bindInputReporter BindInputReporter

// SetBindInputReporter 設定型別不符的回報函式。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 讓上層（server）注入 logger 回報，維持 context 對 logger 零依賴
// @ai:input 回報函式，參數為 routeKey、宣告型別名、實際綁定型別名
// @ai:output none
// @ai:sideeffect 設定套件層級變數（應於程式啟動階段呼叫，非並行安全）
func SetBindInputReporter(fn BindInputReporter) {
	bindInputReporter = fn
}

// SetSchemaInput 記錄當前路由宣告的 Input 型別，供 BindInput 對齊比對。
// 由 router 在註冊 schema 路由時，以一個前置 handler 在每次請求設定。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 將 Schema 宣告的 Input 型別帶入請求上下文，使 BindInput 能在執行期偵測綁錯型別
// @ai:input schema RouteKey 字串、該路由宣告的 Input 零值實例
// @ai:output none
// @ai:sideeffect 設定 Context 內部欄位
func (c *Context) SetSchemaInput(routeKey string, input interface{}) {
	c.schemaRouteKey = routeKey
	c.schemaInput = input
}

// BindInputCalled 回報本請求是否呼叫過 BindInput。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 供啟動 lint 的 runtime 偵測（機制 B）確認 schema 路由的 handler 是否使用了 BindInput
// @ai:input none
// @ai:output bool（true 表示本請求已呼叫 BindInput）
// @ai:sideeffect none
func (c *Context) BindInputCalled() bool {
	return c.bindInputCalled
}

// BindInput 解析請求 body 到 obj、執行 validate tag 驗證，並對齊 Schema 宣告型別。
//
// 失敗時自動以 Error Catalog 形狀的 JSON 中斷請求並回傳 false：
//   - 解析失敗 → 400 {"code":"E0002","message":"Bad request"}
//   - 驗證失敗 → 422 {"code":"E1001","message":"Validation failed","details":{欄位:訊息}}
//
// 成功回傳 true，呼叫端可直接使用 obj。典型用法：
//
//	var req CreateUserReq
//	if !c.BindInput(&req) { return }
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 提供 Schema-first 路由的標準綁定入口，收斂 AI/人各自手寫 unmarshal+驗證+錯誤處理的歧異
// @ai:input 指向目標 struct 的指標（obj）
// @ai:output bool（true=成功並已填入 obj；false=已中斷請求並寫出錯誤回應）
// @ai:sideeffect 讀取 Request body；失敗時寫出 HTTP 4xx JSON 並中止 middleware 鏈；型別不符時觸發 reporter
// @ai:security 驗證使用全框架共用 validator，與 pkg/json 規則一致；錯誤訊息不洩漏內部結構
func (c *Context) BindInput(obj interface{}) bool {
	c.bindInputCalled = true

	// 1. 對齊 Schema 宣告型別：偵測 handler 綁錯 struct 的靜默失敗
	//    （Go 的 json.Unmarshal 綁錯型別不會報錯，這是整條工具鏈唯一能攔截之處）
	if c.schemaInput != nil && bindInputReporter != nil {
		declared := derefType(reflect.TypeOf(c.schemaInput))
		bound := derefType(reflect.TypeOf(obj))
		if declared != nil && bound != nil && declared != bound {
			bindInputReporter(c.schemaRouteKey, declared.String(), bound.String())
		}
	}

	// 2. 依 Content-Type 解析（JSON / form / query 等）
	if err := c.ShouldBind(obj); err != nil {
		c.abortBindError(http.StatusBadRequest, "E0002", "Bad request",
			map[string]interface{}{"reason": err.Error()})
		return false
	}

	// 3. 執行 validate tag 驗證（共用 registry，與 pkg/json 同步生效）
	if err := hypvalidate.Struct(obj); err != nil {
		c.abortBindError(http.StatusUnprocessableEntity, "E1001", "Validation failed",
			validationDetails(err))
		return false
	}

	return true
}

// derefType 解開指標層，回傳底層型別
func derefType(t reflect.Type) reflect.Type {
	for t != nil && t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	return t
}

// abortBindError 以 Error Catalog 形狀輸出錯誤 JSON。
// 直接組裝 map 而不 import pkg/errors，避免 context ← errors 的循環依賴。
func (c *Context) abortBindError(status int, code, message string, details map[string]interface{}) {
	body := map[string]interface{}{
		"code":    code,
		"message": message,
	}
	if len(details) > 0 {
		body["details"] = details
	}
	c.AbortWithStatusJSON(status, body)
}

// validationDetails 將 validator 錯誤轉為 欄位 → 可讀訊息 的細節 map
func validationDetails(err error) map[string]interface{} {
	details := map[string]interface{}{}
	var verrs validator.ValidationErrors
	if stderrors.As(err, &verrs) {
		for _, fe := range verrs {
			details[fe.Field()] = validationMessage(fe)
		}
	} else {
		details["error"] = err.Error()
	}
	return details
}

// validationMessage 依驗證規則產生可讀訊息（對齊 pkg/json 的訊息風格）
func validationMessage(fe validator.FieldError) string {
	field := fe.Field()
	switch fe.Tag() {
	case "required":
		return field + " is required"
	case "email":
		return field + " must be a valid email address"
	case "min":
		return field + " must be at least " + fe.Param()
	case "max":
		return field + " must not exceed " + fe.Param()
	case "oneof":
		return field + " must be one of [" + fe.Param() + "]"
	case "gte":
		return field + " must be >= " + fe.Param()
	case "lte":
		return field + " must be <= " + fe.Param()
	case "gt":
		return field + " must be > " + fe.Param()
	case "lt":
		return field + " must be < " + fe.Param()
	default:
		return field + " failed " + fe.Tag() + " validation"
	}
}
