// @ai:generated by=claude-opus-4-6 date=2026-02-27
// @ai:modified by=claude-opus-4-8 date=2026-06-17 reason=新增 RegisterDesktop（Protocol "desktop"）供桌面專案註冊視圖
package schema

// RegisterGRPC 註冊 gRPC 服務方法的 schema
// command 格式："ServiceName/MethodName"
func RegisterGRPC(command, summary string, input, output interface{}) {
	route := Route{
		Protocol: "grpc",
		Command:  command,
		Summary:  summary,
		Input:    input,
		Output:   output,
	}
	if input != nil {
		route.InputName = TypeName(input)
	}
	if output != nil {
		route.OutputName = TypeName(output)
	}
	Global().Register(route)
}

// RegisterCLI 註冊 CLI 子命令的 schema
func RegisterCLI(command, summary string, input, output interface{}) {
	route := Route{
		Protocol: "cli",
		Command:  command,
		Summary:  summary,
		Input:    input,
		Output:   output,
	}
	if input != nil {
		route.InputName = TypeName(input)
	}
	if output != nil {
		route.OutputName = TypeName(output)
	}
	Global().Register(route)
}

// RegisterDesktop 註冊桌面（GUI）視圖的 schema
// command 慣例："view/<name>"，例如 "view/main"、"view/settings"
func RegisterDesktop(command, summary string, input, output interface{}) {
	route := Route{
		Protocol: "desktop",
		Command:  command,
		Summary:  summary,
		Input:    input,
		Output:   output,
	}
	if input != nil {
		route.InputName = TypeName(input)
	}
	if output != nil {
		route.OutputName = TypeName(output)
	}
	Global().Register(route)
}
