// Package hypgo 提供 HypGo 框架的一行式啟動入口（facade）。
//
// 它把「載入設定 → 套用預設值 → 初始化 logger → 建立 server」收斂為單一呼叫，
// 並嵌入 Router 讓 App 直接擁有 GET/POST/Use/NewGroup/Schema/Static 等方法：
//
//	app := hypgo.New()
//	app.GET("/ping", func(c *hypcontext.Context) { c.String(200, "pong") })
//	app.Run()
//
// 進階場景仍可直接使用 pkg/config、pkg/logger、pkg/server 取得完整控制權。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 降低正確起步的摩擦（原本 5 步驟且易漏呼叫 ApplyDefaults），提供零配置可跑的 facade
package hypgo

import (
	"os"

	"github.com/maoxiaoyue/hypgo/pkg/config"
	"github.com/maoxiaoyue/hypgo/pkg/logger"
	"github.com/maoxiaoyue/hypgo/pkg/router"
	"github.com/maoxiaoyue/hypgo/pkg/server"
)

// defaultConfigPaths 是 New() 在未指定路徑時依序探測的設定檔位置
var defaultConfigPaths = []string{
	"config.yaml",
	"config/config.yaml",
	"app/config/config.yaml",
	".hyp/config.yaml",
}

// App 是 HypGo 應用的一行式 facade。
// 嵌入 *router.Router，因此 app.GET / app.Use / app.NewGroup / app.Schema 等
// 路由方法可直接使用，且作用於 server 實際服務的同一個 router。
type App struct {
	*router.Router
	server *server.Server
	config *config.Config
	logger *logger.Logger
}

// Option 客製化 App 建構行為
type Option func(*options)

type options struct {
	configPath string
	logger     *logger.Logger
	jsonLogs   bool
}

// WithConfigPath 指定設定檔路徑（取代預設探測）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 讓 New() 使用指定設定檔；找不到時仍回退預設值（不報錯）
// @ai:input 設定檔路徑
// @ai:output Option
// @ai:sideeffect none
func WithConfigPath(path string) Option {
	return func(o *options) { o.configPath = path }
}

// WithLogger 注入自訂 logger（取代依設定自動建立的 logger）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 允許呼叫端提供預先配置好的 logger（如已設好輪轉/輸出）
// @ai:input *logger.Logger
// @ai:output Option
// @ai:sideeffect none
func WithLogger(l *logger.Logger) Option {
	return func(o *options) { o.logger = l }
}

// WithJSONLogs 啟用 slog 結構化 JSON 日誌輸出。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 一行切換到適合日誌聚合器（Loki/Datadog）的 JSON 輸出
// @ai:input none
// @ai:output Option
// @ai:sideeffect none
func WithJSONLogs() Option {
	return func(o *options) { o.jsonLogs = true }
}

// New 以零配置方式建立 App：依序探測 config.yaml，找不到則使用內建預設值（永不報錯）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 提供最簡起步路徑，沒有設定檔也能在 :8080 啟動；預設值與 logger 都自動就緒
// @ai:input 可選的 Option（WithConfigPath / WithLogger / WithJSONLogs）
// @ai:output 已就緒的 *App（Router / Config / Logger / Server 均非 nil）
// @ai:sideeffect 讀取設定檔（若存在）
func New(opts ...Option) *App {
	o := buildOptions(opts)
	cfg := resolveConfig(o.configPath)
	log := o.logger
	if log == nil {
		log = buildLogger(cfg, o.jsonLogs)
	}
	return assemble(cfg, log)
}

// NewWithConfig 以指定設定檔建立 App；檔案不存在或無效時回傳 error。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 需要嚴格設定（生產環境）時使用，設定問題以 error 明確回報而非靜默回退
// @ai:input 設定檔路徑、可選的 Option
// @ai:output (*App, error)
// @ai:sideeffect 讀取設定檔
func NewWithConfig(path string, opts ...Option) (*App, error) {
	o := buildOptions(opts)
	cfg, err := config.LoadConfig(path)
	if err != nil {
		return nil, err
	}
	log := o.logger
	if log == nil {
		log = buildLogger(cfg, o.jsonLogs)
	}
	return assemble(cfg, log), nil
}

// Run 啟動伺服器（阻塞直到收到關閉訊號）。
// 啟動時 AutoSync 會寫入 .hyp/context.yaml 並輸出 Schema 完整度檢查。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 等同 server.Start()，作為 facade 的收尾呼叫
// @ai:input none
// @ai:output error（伺服器啟動或執行期錯誤）
// @ai:sideeffect 監聽連接埠、寫入 PID 檔與 .hyp/context.yaml、阻塞執行
func (a *App) Run() error {
	return a.server.Start()
}

// Server 回傳底層 *server.Server（進階控制用）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 暴露底層 server 以使用 facade 未轉發的進階功能（如 Manifest、自訂 Shutdown）
// @ai:input none
// @ai:output *server.Server
// @ai:sideeffect none
func (a *App) Server() *server.Server { return a.server }

// Logger 回傳 App 使用的 logger。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 讓呼叫端取得與 server 共用的 logger 實例
// @ai:input none
// @ai:output *logger.Logger
// @ai:sideeffect none
func (a *App) Logger() *logger.Logger { return a.logger }

// Config 回傳已套用預設值的設定。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-11
// @ai:purpose 讓呼叫端讀取最終生效的設定（含預設值）
// @ai:input none
// @ai:output *config.Config
// @ai:sideeffect none
func (a *App) Config() *config.Config { return a.config }

// buildOptions 套用所有 Option
func buildOptions(opts []Option) options {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return o
}

// assemble 以設定與 logger 組裝 App，並讓嵌入的 Router 指向 server 實際服務的 router
func assemble(cfg *config.Config, log *logger.Logger) *App {
	srv := server.New(cfg, log)
	return &App{
		Router: srv.Router(),
		server: srv,
		config: cfg,
		logger: log,
	}
}

// resolveConfig 探測並載入設定檔；找不到或載入失敗時回退到內建預設值（永不報錯）
func resolveConfig(explicit string) *config.Config {
	paths := defaultConfigPaths
	if explicit != "" {
		paths = []string{explicit}
	}
	for _, p := range paths {
		if _, err := os.Stat(p); err != nil {
			continue
		}
		if cfg, err := config.LoadConfig(p); err == nil {
			return cfg
		}
	}
	// 找不到或載入失敗 → 使用預設值（零配置開發體驗）
	cfg := &config.Config{}
	cfg.ApplyDefaults()
	cfg.Logger.Colors = true // 零配置時預設彩色終端輸出
	return cfg
}

// buildLogger 依設定建立可用的 logger（永不回傳 nil）。
// Output 為檔案路徑時接上 Rotation writer（依 config 的 rotation 區段自動輪轉）；
// 開檔失敗時退回 stdout 並告警，不讓啟動失敗。
func buildLogger(cfg *config.Config, jsonLogs bool) *logger.Logger {
	output := cfg.Logger.Output
	if output == "" {
		output = "stdout"
	}

	var log *logger.Logger
	if output != "stdout" && output != "stderr" {
		rc := &logger.RotationConfig{
			MaxSize:    cfg.Logger.Rotation.MaxSize,
			MaxAge:     cfg.Logger.Rotation.MaxAge,
			MaxBackups: cfg.Logger.Rotation.MaxBackups,
			Compress:   cfg.Logger.Rotation.Compress,
		}
		var err error
		log, err = logger.NewWithRotation(cfg.Logger.Level, output, rc, cfg.Logger.Colors)
		if err != nil {
			log, _ = logger.New(cfg.Logger.Level, "stdout", nil, cfg.Logger.Colors)
			log.Warningf("logger: 無法開啟日誌檔 %s（%v），改輸出到 stdout", output, err)
		}
	} else {
		log, _ = logger.New(cfg.Logger.Level, output, nil, cfg.Logger.Colors)
	}

	if jsonLogs {
		log.SetFormat("json")
	}
	return log
}
