//go:build !windows

// @ai:generated by=claude-fable-5 date=2026-06-23
package server

import "syscall"

// fdIsListeningSocket 回報 fd 是否為「正在 listening」的 socket（SO_ACCEPTCONN == 1）。
// getInheritedListener 以此驗證 FD 3 確實是 parent 在 graceful restart 時刻意
// 傳入的 listener；shell 湊巧留在 FD 3 的已連線 socket 或一般檔案會在這裡被擋下，
// 避免誤繼承後 Accept 爆出 accept4: invalid argument（見 bugs.md #1）。
func fdIsListeningSocket(fd int) bool {
	v, err := syscall.GetsockoptInt(fd, syscall.SOL_SOCKET, syscall.SO_ACCEPTCONN)
	return err == nil && v == 1
}
