// Package airules 自動生成跨 AI 工具的配置檔
// 支援 AGENTS.md、GEMINI.md、GitHub Copilot、Cursor、Windsurf
package airules

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/maoxiaoyue/hypgo/pkg/manifest"
)

const autoGenMarker = "<!-- auto-generated by hyp ai-rules -->"

// Target 描述一個 AI 工具配置檔目標
type Target struct {
	Name     string // 顯示名稱（如 "AGENTS.md"）
	RelPath  string // 相對於專案根目錄的路徑
	Generate func(m *manifest.Manifest) string
}

// AllTargets 回傳所有支援的 AI 工具配置檔目標
func AllTargets() []Target {
	return []Target{
		{Name: "agents", RelPath: "AGENTS.md", Generate: generateAgentsMD},
		{Name: "gemini", RelPath: "GEMINI.md", Generate: generateGeminiMD},
		{Name: "copilot", RelPath: filepath.Join(".github", "copilot-instructions.md"), Generate: generateCopilotMD},
		{Name: "cursor", RelPath: filepath.Join(".cursor", "rules", "hypgo.mdc"), Generate: generateCursorMDC},
		{Name: "windsurf", RelPath: filepath.Join(".windsurf", "rules", "hypgo.md"), Generate: generateWindsurfMD},
	}
}

// FilterTargets 根據名稱過濾目標
// names 為逗號分隔的名稱清單，空字串表示全部
func FilterTargets(targets []Target, names string) []Target {
	if names == "" {
		return targets
	}
	wanted := make(map[string]bool)
	for _, n := range strings.Split(names, ",") {
		wanted[strings.TrimSpace(n)] = true
	}
	var result []Target
	for _, t := range targets {
		if wanted[t.Name] {
			result = append(result, t)
		}
	}
	return result
}

// GenerateAll 在指定目錄下生成所有配置檔
// 如果檔案已存在且沒有 auto-gen 標記，則跳過（保護手動修改的版本）
func GenerateAll(dir string, targets []Target, m *manifest.Manifest, dryRun bool) ([]Result, error) {
	var results []Result
	for _, t := range targets {
		path := filepath.Join(dir, t.RelPath)
		content := t.Generate(m)

		// 檢查是否已存在且非自動生成
		if !canOverwrite(path) {
			results = append(results, Result{
				Path:    path,
				Status:  StatusSkipped,
				Message: "file exists without auto-gen marker, skipping",
			})
			continue
		}

		if dryRun {
			results = append(results, Result{
				Path:    path,
				Status:  StatusDryRun,
				Content: content,
			})
			continue
		}

		if err := writeFile(path, content); err != nil {
			results = append(results, Result{
				Path:    path,
				Status:  StatusError,
				Message: err.Error(),
			})
			continue
		}

		results = append(results, Result{
			Path:   path,
			Status: StatusCreated,
		})
	}
	return results, nil
}

// Result 描述單一檔案的生成結果
type Result struct {
	Path    string
	Status  Status
	Message string
	Content string // dry-run 時填入
}

// Status 生成結果狀態
type Status int

const (
	StatusCreated Status = iota
	StatusSkipped
	StatusDryRun
	StatusError
)

func (s Status) String() string {
	switch s {
	case StatusCreated:
		return "created"
	case StatusSkipped:
		return "skipped"
	case StatusDryRun:
		return "dry-run"
	case StatusError:
		return "error"
	default:
		return "unknown"
	}
}

// canOverwrite 檢查檔案是否可被覆蓋
// 不存在 → 可以；存在且有 auto-gen 標記 → 可以；否則不行
func canOverwrite(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return true // 檔案不存在
	}
	return strings.Contains(string(data), autoGenMarker)
}

func writeFile(path string, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	return os.WriteFile(path, []byte(content), 0644)
}
