// @ai:generated by=claude-opus-4-6 date=2026-02-27
// @ai:modified by=claude-opus-4-7 date=2026-06-15 reason=新增 CLAUDE/ChatGPT/Trae/通義靈碼/DeepSeek 等模板
// @ai:modified by=claude-opus-4-8 date=2026-06-17 reason=模板強化嚴格規範：MVC 分層、contract/Test 強制、forbidden 清單與 lint gate
// @ai:modified by=claude-opus-4-8 date=2026-06-21 reason=新增「所有 err 須經 logger 記錄、logger 行為完全依 .hyp/config.yaml」規範；@ai:think 範例精簡為單一語言
package airules

import (
	"fmt"
	"strings"

	"github.com/maoxiaoyue/hypgo/pkg/manifest"
)

// effectiveComment 回傳 opts.Comment 或預設值
func effectiveComment(opts Options) CommentToggles {
	c := opts.Comment
	// 全部關閉時視為「未設定」→ 回退預設（避免全空時生成出意義不明的規則檔）
	if !c.NormalComment && !c.AIComment && !c.ThinkComment {
		return DefaultCommentToggles()
	}
	return c
}

func coreContent(m *manifest.Manifest, opts Options) string {
	var sb strings.Builder
	cm := effectiveComment(opts)

	sb.WriteString(`## Framework

- **HypGo**: Modern Go web framework (HTTP/1.1 + HTTP/2 + HTTP/3 QUIC)
- Go 1.24+, Bun ORM, Radix Tree router, WebSocket multi-protocol
- Module: github.com/maoxiaoyue/hypgo

## Project Structure

`)
	sb.WriteString("```\n")
	sb.WriteString("app/models/        Bun ORM models + Req/Resp DTO structs (CreateXxxReq, XxxResp)\n")
	sb.WriteString("app/services/      Business logic + Error Catalog (errors.Define) + CRUD methods\n")
	sb.WriteString("app/controllers/   HTTP handlers — thin: parse input, call service, write response\n")
	sb.WriteString("app/routers/       Schema-first route registration + Setup() + middleware\n")
	sb.WriteString("app/views/         Templates / desktop (Fyne) views\n")
	sb.WriteString("app/config/        Application configuration (config.yaml)\n")
	sb.WriteString(".hyp/              Auto-generated project context (manifest + lint report)\n")
	sb.WriteString("```\n")

	sb.WriteString("\n## Architecture — MVC (MUST follow)\n\n")
	sb.WriteString("HypGo projects MUST use the layered MVC structure. Keep controllers thin; ALL business logic lives in services. Generate layers with `hyp generate model|service|controller <name>` — do not hand-roll the structure.\n\n")
	sb.WriteString("- **Model** (`app/models/`, pkg/hidb): Bun ORM struct + its Req/Resp DTOs (CreateXxxReq, UpdateXxxReq, XxxResp).\n")
	sb.WriteString("- **Service** (`app/services/`, pkg/errors): business logic, DB access, Error Catalog.\n")
	sb.WriteString("- **Controller** (`app/controllers/`, pkg/context): parse input → call service → write response. NO business logic, NO direct DB access.\n")
	sb.WriteString("- **Router** (`app/routers/`, pkg/router + pkg/schema): Schema-first registration + Setup() + middleware only.\n")

	sb.WriteString("\n## Key Conventions (STRICT — no exceptions)\n\n")
	sb.WriteString("1. **Schema-first routes** (MANDATORY, pkg/schema): every API route MUST be registered with type metadata via `r.Schema(...)`. NEVER call `r.GET/POST(...)` directly for API routes.\n")
	sb.WriteString("   ```go\n")
	sb.WriteString("   r.Schema(schema.Route{\n")
	sb.WriteString("       Method: \"POST\", Path: \"/api/users\",\n")
	sb.WriteString("       Summary: \"Create user\",\n")
	sb.WriteString("       Input: CreateUserReq{}, Output: UserResp{},\n")
	sb.WriteString("       Responses: map[int]schema.ResponseSchema{201: {Description: \"created\"}},\n")
	sb.WriteString("   }).Handle(handler)\n")
	sb.WriteString("   ```\n\n")

	sb.WriteString("2. **BindInput** (MANDATORY, pkg/context): handlers MUST bind input via `c.BindInput(&req)` (parse + validate + schema type-align; auto 400/422 on failure). NEVER hand-roll JSON decoding.\n")
	sb.WriteString("   ```go\n")
	sb.WriteString("   var req CreateUserReq\n")
	sb.WriteString("   if !c.BindInput(&req) { return }\n")
	sb.WriteString("   ```\n\n")

	sb.WriteString("3. **Typed errors + always log** (MANDATORY, pkg/errors + pkg/logger): use the Error Catalog; NEVER `c.JSON(500, ...)`. EVERY error MUST be logged via `pkg/logger` (`log.Error`) before aborting. Logger config (level/output/rotation/format) comes ONLY from `.hyp/config.yaml` — never hardcode.\n")
	sb.WriteString("   ```go\n")
	sb.WriteString("   var ErrNotFound = errors.Define(\"E1001\", 404, \"Not found\", \"general\")\n")
	sb.WriteString("   log.Error(\"load user failed\", \"id\", id, \"err\", err) // log EVERY error\n")
	sb.WriteString("   errors.AbortWithAppError(c, ErrNotFound.With(\"id\", id))\n")
	sb.WriteString("   ```\n\n")

	sb.WriteString("4. **Contract tests** (MANDATORY, pkg/contract): every schema route MUST have a `_test.go` covering happy path, boundary, and at least one error case. Use the fixture builder (`contract.Request`) for explicit cases.\n")
	sb.WriteString("   ```go\n")
	sb.WriteString("   func TestContracts(t *testing.T) {\n")
	sb.WriteString("       contract.TestAll(t, setupRouter()) // validates all schema-registered routes\n")
	sb.WriteString("   }\n")
	sb.WriteString("   ```\n\n")

	// 規範編號連續：依 toggles 動態決定是否寫入 §5（普通註釋）、§6（@ai）、§7（@ai:think）
	ruleNum := 5

	if cm.NormalComment {
		sb.WriteString(fmt.Sprintf("%d. **Comments** (REQUIRED): every exported func, type, and package MUST have a Go doc comment. Comments explain **why**, not **what** (the name covers what). Keep them concise; prefer one tight sentence over a paragraph. Verify with `go vet ./...` (missing exported-name docs surface in `golint`-style checks).\n\n", ruleNum))
		ruleNum++
	}

	if cm.AIComment {
		sb.WriteString(fmt.Sprintf("%d. **@ai annotations** (MANDATORY): every exported func/struct MUST carry a full `@ai` block (generated / purpose / input / output / sideeffect). Dates use `YYYY-MM-DD`; model names use official ids (e.g. `claude-opus-4-8`). Verify with `hyp chkcomment <file>`.\n\n", ruleNum))
		ruleNum++
	}

	if cm.ThinkComment {
		sb.WriteString(fmt.Sprintf("%d. **@ai:think** (MANDATORY): every func body MUST begin with a `//@ai:think` comment explaining:\n", ruleNum))
		sb.WriteString("   - **Intent**: why AI wrote this func / what problem it solves\n")
		sb.WriteString("   - **Special notes**: non-obvious design choices, edge-case handling, or workarounds inside the func\n")
		sb.WriteString("   ```go\n")
		sb.WriteString("   func CreateUser(ctx context.Context, req CreateUserReq) (*UserResp, error) {\n")
		sb.WriteString("       //@ai:think intent=create user; verify email uniqueness first model=claude-opus-4-8\n")
		sb.WriteString("       //@ai:think special=upsert (not insert) to avoid concurrent unique conflict model=claude-opus-4-8\n")
		sb.WriteString("       // ... implementation\n")
		sb.WriteString("   }\n")
		sb.WriteString("   ```\n")
		sb.WriteString("   This applies to ALL funcs (exported and unexported). Omitting `@ai:think` is a lint violation. Auto-fix with `hyp chkcomment --fixintent --llm .hyp/llm.yaml <file>`.\n")
		_ = ruleNum // 最後一條規範不再需要編號
	}

	// 註釋開關來源（always emitted）— 即使某些規範因 toggle 關閉而沒寫進此文件，
	// AI 在每次生成程式碼前仍應重讀 .hyp/comment.yaml 確認當下設定。
	sb.WriteString("\n### Comment Generation Toggle (source of truth: `.hyp/comment.yaml`)\n\n")
	sb.WriteString("Before generating ANY code, read `.hyp/comment.yaml` to confirm which comment types to write. Only emit a comment type whose toggle is `true`. If the file is missing or unreadable, fall back to defaults:\n\n")
	sb.WriteString("| Toggle | Default | What it controls |\n")
	sb.WriteString("|--------|---------|------------------|\n")
	sb.WriteString("| `normal_comment` | **true** | Standard Go doc comments on exported funcs/types/packages |\n")
	sb.WriteString("| `ai_comment` | **false** | `@ai:generated` / `@ai:purpose` / `@ai:input` / `@ai:output` / `@ai:sideeffect` |\n")
	sb.WriteString("| `think_comment` | **false** | `//@ai:think intent=… / special=… / model=…` inside func bodies |\n\n")
	sb.WriteString("Rules above marked MANDATORY/REQUIRED apply ONLY when their toggle is on. The toggle file overrides any rule shown here — re-read it on every session start; do NOT cache.\n")
	sb.WriteString("Fallback behaviour (missing/unreadable file): write `normal_comment` only — do NOT add `@ai` or `@ai:think` lines.\n")

	sb.WriteString("\n## Database access (pkg/hidb)\n\n")
	sb.WriteString("- Reads → `hidb.ReadHypDB()` (replica)\n")
	sb.WriteString("- Writes → `hidb.WriteHypDB()` (master)\n")
	sb.WriteString("- Transactions → `hidb.HypDBTransaction(ctx, fn)`\n")

	sb.WriteString("\n## Forbidden\n\n")
	sb.WriteString("- No `panic()` in request handlers (init phase only)\n")
	sb.WriteString("- No `fmt.Println` for logging — use `pkg/logger`; configure ONLY via `.hyp/config.yaml`\n")
	sb.WriteString("- No swallowed errors — log every `err != nil` via `pkg/logger` before returning/aborting\n")
	sb.WriteString("- No `math/rand` for tokens / session ids — use `crypto/rand`\n")
	sb.WriteString("- No `time.Sleep` inside handlers\n")
	sb.WriteString("- No hardcoded DSN / API key / secret — read from config (pkg/config)\n")

	sb.WriteString(`
## Build & Test

`)
	sb.WriteString("```bash\n")
	sb.WriteString("go build ./...\ngo test ./... -v\ngo vet ./...\n")
	sb.WriteString("hyp lint              # Schema completeness CI gate (non-zero exit on gaps)\n")
	sb.WriteString("hyp chkcomment ./...  # @ai annotation completeness\n")
	sb.WriteString("```\n")

	sb.WriteString(`
## AI Collaboration

- **Start here**: Read ` + "`.hyp/context.yaml`" + ` — all routes, types, config in ~500 tokens
- **Authoritative rules**: ` + "`.hyp/AI_CODING_RULES.md`" + ` is the single source of truth — read it before generating code
- **Before modifying shared packages**: Run ` + "`hyp impact <file>`" + `
- **After writing code**: Run ` + "`hyp chkcomment <file>`" + ` then ` + "`hyp lint`" + ` (CI gate; non-zero exit blocks merge)
- **Generate manifest**: ` + "`hyp context -o .hyp/manifest.yaml`" + `
- **Error codes**: Pattern E{category}{number} (e.g., E1001, E2001)
- **All schema routes have Input/Output types** — use them for code generation
`)

	// 條件性加入 diff-log 指令（開啟時才寫入，關閉時省 token）
	if opts.DiffLogEnabled {
		sb.WriteString("- **After making changes**: Run " + "`hyp diff-log`" + " to log your changes to logs/ai.diff_YYYYMMDD.log\n")
	}

	if m != nil && len(m.Routes) > 0 {
		sb.WriteString("\n## Current Routes\n\n")
		sb.WriteString("| Method | Path | Summary |\n")
		sb.WriteString("|--------|------|--------|\n")
		for _, r := range m.Routes {
			summary := r.Summary
			if summary == "" {
				summary = "-"
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", r.Method, r.Path, summary))
		}
	}

	return sb.String()
}

// plainMD 通用純 markdown 模板（多數 AI 工具規範檔皆為此格式）
func plainMD(title string, m *manifest.Manifest, opts Options) string {
	return autoGenMarker + "\n# " + title + "\n\n" + coreContent(m, opts)
}

// --- 預設集（"all" 模式包含的 7 個） ---

func generateChatGPTMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — ChatGPT Instructions", m, opts)
}

func generateClaudeMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — Claude Code Instructions", m, opts)
}

func generateTraeMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — Trae Project Rules", m, opts)
}

// 通義靈碼（Tongyi Lingma）
func generateTongyiMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — 通義靈碼專案規範", m, opts)
}

func generateDeepSeekMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — DeepSeek Instructions", m, opts)
}

func generateGeminiMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo Framework Instructions", m, opts)
}

func generateCursorMDC(m *manifest.Manifest, opts Options) string {
	var sb strings.Builder
	sb.WriteString(autoGenMarker + "\n")
	sb.WriteString("---\n")
	sb.WriteString("description: HypGo framework conventions and AI collaboration rules\n")
	sb.WriteString("globs: \"**/*.go\"\n")
	sb.WriteString("alwaysApply: true\n")
	sb.WriteString("---\n\n")
	sb.WriteString("# HypGo Framework Instructions\n\n")
	sb.WriteString(coreContent(m, opts))
	return sb.String()
}

// --- 擴充集（僅在 --only 明確列出時生成） ---

func generateAgentsMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo Framework Instructions", m, opts)
}

func generateCopilotMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo Framework Instructions", m, opts)
}

func generateWindsurfMD(m *manifest.Manifest, opts Options) string {
	var sb strings.Builder
	sb.WriteString(autoGenMarker + "\n")
	sb.WriteString("# HypGo Framework Instructions\n\n")
	content := coreContent(m, opts)
	if len(content) > 5800 {
		if idx := strings.Index(content, "\n## Current Routes"); idx > 0 {
			content = content[:idx]
		}
	}
	sb.WriteString(content)
	return sb.String()
}

func generateClineMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — Cline Rules", m, opts)
}

func generateContinueMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — Continue Rules", m, opts)
}

func generateAiderMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — Aider Conventions", m, opts)
}

func generateRooMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — Roo Code Rules", m, opts)
}

func generateCodeBuddyMD(m *manifest.Manifest, opts Options) string {
	return plainMD("HypGo — CodeBuddy Rules", m, opts)
}
