// @ai:generated by=claude-opus-4-7 date=2026-06-18
package airules

import (
	"strings"
	"testing"
)

func TestCoreContent_DefaultCommentToggles(t *testing.T) {
	// 預設值：只開普通註釋
	out := coreContent(nil, Options{Comment: DefaultCommentToggles()})
	if !strings.Contains(out, "**Comments** (REQUIRED)") {
		t.Error("default should include Comments section")
	}
	if strings.Contains(out, "**@ai annotations**") {
		t.Error("default should NOT include @ai annotations section")
	}
	if strings.Contains(out, "**@ai:think**") {
		t.Error("default should NOT include @ai:think section")
	}
}

func TestCoreContent_AllToggles(t *testing.T) {
	out := coreContent(nil, Options{Comment: CommentToggles{
		NormalComment: true, AIComment: true, ThinkComment: true,
	}})
	if !strings.Contains(out, "**Comments** (REQUIRED)") {
		t.Error("missing Comments section")
	}
	if !strings.Contains(out, "**@ai annotations** (MANDATORY)") {
		t.Error("missing @ai annotations section")
	}
	if !strings.Contains(out, "**@ai:think** (MANDATORY)") {
		t.Error("missing @ai:think section")
	}
}

func TestCoreContent_AIOnly(t *testing.T) {
	out := coreContent(nil, Options{Comment: CommentToggles{
		NormalComment: false, AIComment: true, ThinkComment: false,
	}})
	if strings.Contains(out, "**Comments** (REQUIRED)") {
		t.Error("Comments section should be off")
	}
	if !strings.Contains(out, "**@ai annotations**") {
		t.Error("@ai annotations should be on")
	}
	if strings.Contains(out, "**@ai:think**") {
		t.Error("@ai:think should be off")
	}
}

func TestCoreContent_ThinkOnly(t *testing.T) {
	out := coreContent(nil, Options{Comment: CommentToggles{
		NormalComment: false, AIComment: false, ThinkComment: true,
	}})
	if strings.Contains(out, "**Comments** (REQUIRED)") {
		t.Error("Comments section should be off")
	}
	if strings.Contains(out, "**@ai annotations**") {
		t.Error("@ai annotations should be off")
	}
	if !strings.Contains(out, "**@ai:think**") {
		t.Error("@ai:think should be on")
	}
}

func TestCoreContent_AllOff_FallsBackToDefault(t *testing.T) {
	// 全關 → 視為「未設定」→ 退回預設（只開 normal_comment）
	out := coreContent(nil, Options{Comment: CommentToggles{}})
	if !strings.Contains(out, "**Comments** (REQUIRED)") {
		t.Error("all-off should fall back to defaults (Comments on)")
	}
	if strings.Contains(out, "**@ai annotations**") {
		t.Error("all-off fallback should NOT include @ai annotations")
	}
}

func TestCoreContent_RuleNumbering(t *testing.T) {
	// 規範編號要連續：開了 AI+Think 但關 Normal → 5. @ai / 6. @ai:think
	out := coreContent(nil, Options{Comment: CommentToggles{
		NormalComment: false, AIComment: true, ThinkComment: true,
	}})
	if !strings.Contains(out, "5. **@ai annotations**") {
		t.Errorf("expected '5. **@ai annotations**' when normal_comment off")
	}
	if !strings.Contains(out, "6. **@ai:think**") {
		t.Errorf("expected '6. **@ai:think**'")
	}
}

func TestCoreContent_RuleNumbering_NormalThink(t *testing.T) {
	// 開了 Normal+Think 但關 AI → 5. Comments / 6. @ai:think（跳過 @ai）
	out := coreContent(nil, Options{Comment: CommentToggles{
		NormalComment: true, AIComment: false, ThinkComment: true,
	}})
	if !strings.Contains(out, "5. **Comments**") {
		t.Errorf("expected '5. **Comments**'")
	}
	if !strings.Contains(out, "6. **@ai:think**") {
		t.Errorf("expected '6. **@ai:think**' when AI off")
	}
}

func TestDefaultCommentToggles(t *testing.T) {
	d := DefaultCommentToggles()
	if !d.NormalComment || d.AIComment || d.ThinkComment {
		t.Errorf("expected only NormalComment on, got %+v", d)
	}
}

func TestCoreContent_TogglesSourceNote_AlwaysEmitted(t *testing.T) {
	// Toggle source-of-truth note must appear regardless of toggle state,
	// so AI re-reads .hyp/comment.yaml even if the rules markdown is stale.
	combos := []CommentToggles{
		{NormalComment: true, AIComment: false, ThinkComment: false},
		{NormalComment: true, AIComment: true, ThinkComment: true},
		{NormalComment: false, AIComment: true, ThinkComment: false},
		{NormalComment: false, AIComment: false, ThinkComment: true},
		{},
	}
	for _, c := range combos {
		out := coreContent(nil, Options{Comment: c})
		if !strings.Contains(out, "Comment Generation Toggle") {
			t.Errorf("toggle source note missing for %+v", c)
		}
		if !strings.Contains(out, ".hyp/comment.yaml") {
			t.Errorf(".hyp/comment.yaml reference missing for %+v", c)
		}
		if !strings.Contains(out, "Fallback behaviour") {
			t.Errorf("fallback rule missing for %+v", c)
		}
	}
}
