// Package sample 是 lintdeep 的測試夾具：刻意包含正確與錯誤的 Schema↔handler 綁定。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 提供 deeplint 單元測試的可編譯目標，涵蓋 good / mismatch / no-bindinput / inline 四種案例
package sample

import (
	hypcontext "github.com/maoxiaoyue/hypgo/pkg/context"
	"github.com/maoxiaoyue/hypgo/pkg/router"
	"github.com/maoxiaoyue/hypgo/pkg/schema"
)

// GoodReq 正確綁定案例的輸入。
type GoodReq struct {
	Name string `json:"name"`
}

// BadReq mismatch 案例宣告的輸入。
type BadReq struct {
	Title string `json:"title"`
}

// OtherReq mismatch 案例中 handler 誤綁的型別。
type OtherReq struct {
	Other string `json:"other"`
}

// NoBindReq no-bindinput 案例宣告的輸入。
type NoBindReq struct {
	Field string `json:"field"`
}

// Register 註冊四條測試路由：good（具名正確）、bad（綁錯型別）、nobind（未綁）、inline（func literal 正確）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func Register(r *router.Router) {
	r.Schema(schema.Route{Method: "POST", Path: "/good", Input: GoodReq{}, Output: GoodReq{}}).Handle(goodHandler)
	r.Schema(schema.Route{Method: "POST", Path: "/bad", Input: BadReq{}, Output: BadReq{}}).Handle(badHandler)
	r.Schema(schema.Route{Method: "POST", Path: "/nobind", Input: NoBindReq{}, Output: NoBindReq{}}).Handle(noBindHandler)
	r.Schema(schema.Route{Method: "PUT", Path: "/inline", Input: GoodReq{}, Output: GoodReq{}}).Handle(func(c *hypcontext.Context) {
		var req GoodReq
		if !c.BindInput(&req) {
			return
		}
		c.JSON(200, req)
	})
}

// goodHandler 正確綁定宣告型別 GoodReq。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func goodHandler(c *hypcontext.Context) {
	var req GoodReq
	if !c.BindInput(&req) {
		return
	}
	c.JSON(200, req)
}

// badHandler 綁錯型別：宣告 BadReq 卻綁定 OtherReq。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func badHandler(c *hypcontext.Context) {
	var req OtherReq
	if !c.BindInput(&req) {
		return
	}
	c.JSON(200, req)
}

// noBindHandler 完全未呼叫 BindInput，宣告的 Input 不會被解析或驗證。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func noBindHandler(c *hypcontext.Context) {
	c.JSON(200, map[string]string{"ok": "true"})
}
