// Package resource 提供跨套件共用的「資源使用」計數器（DB / Redis / Cassandra）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 以全域 atomic 計數器累計各類外部資源的存取次數，讓 contract observe 等
//
//	診斷工具能在執行一段程式碼前後做快照差分，得知該段是否動用了哪些資源、各幾次。
//	刻意零依賴，避免任何 import cycle（hidb 與 contract 皆可 import）。
package resource

import "sync/atomic"

var (
	dbCount        atomic.Int64
	redisCount     atomic.Int64
	redisKeyCount  atomic.Int64
	cassandraCount atomic.Int64
)

// MarkDB 在關聯式資料庫（bun ORM / SQL）被存取時計數一次。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 由 hidb 的讀/寫/交易存取點呼叫，標記本段程式有觸及關聯式 DB
// @ai:input none
// @ai:output none
// @ai:sideeffect 原子遞增全域 DB 計數器（並行安全）
func MarkDB() { dbCount.Add(1) }

// MarkRedis 記錄一次 Redis 操作，keys 為該操作觸及的 key 數量（無法得知時傳 0）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:modified by=claude-opus-4-8 date=2026-06-15 reason=改由 go-redis hook 對每條命令計數，新增 key 數量參數
// @ai:purpose 由掛在 redis client 上的 hook 對每條命令呼叫，累計 Redis 操作數與觸及的 key 數量
// @ai:input keys 該次操作觸及的 key 數量（0 表示無 key 或無法得知）
// @ai:output none
// @ai:sideeffect 原子遞增全域 Redis 操作計數與 key 計數（並行安全）
func MarkRedis(keys int) {
	redisCount.Add(1)
	if keys > 0 {
		redisKeyCount.Add(int64(keys))
	}
}

// MarkCassandra 在 Cassandra 被存取時計數一次。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 由 cassandra 外掛的 Session 取得點呼叫，標記本段程式有觸及 Cassandra
// @ai:input none
// @ai:output none
// @ai:sideeffect 原子遞增全域 Cassandra 計數器（並行安全）
func MarkCassandra() { cassandraCount.Add(1) }

// Stats 為某一時刻各資源累計存取次數的快照。
type Stats struct {
	DB        int64 `json:"db" yaml:"db"`
	Redis     int64 `json:"redis" yaml:"redis"`           // Redis 操作（命令）數
	RedisKeys int64 `json:"redis_keys" yaml:"redis_keys"` // Redis 觸及的 key 數量（累計，含重複）
	Cassandra int64 `json:"cassandra" yaml:"cassandra"`
}

// Snapshot 讀取目前各資源的累計存取次數。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 取得當下計數，供量測前後兩次取樣再以 Sub 求差
// @ai:input none
// @ai:output 當下各資源累計次數的 Stats
// @ai:sideeffect none（僅原子讀取）
func Snapshot() Stats {
	return Stats{
		DB:        dbCount.Load(),
		Redis:     redisCount.Load(),
		RedisKeys: redisKeyCount.Load(),
		Cassandra: cassandraCount.Load(),
	}
}

// Sub 回傳 s 相對 base 的差值（s - base），即兩次快照之間的資源使用量。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 求一段程式執行期間實際動用的資源次數
// @ai:input base 較早的快照
// @ai:output 各資源於這段期間的存取次數差
// @ai:sideeffect none
func (s Stats) Sub(base Stats) Stats {
	return Stats{
		DB:        s.DB - base.DB,
		Redis:     s.Redis - base.Redis,
		RedisKeys: s.RedisKeys - base.RedisKeys,
		Cassandra: s.Cassandra - base.Cassandra,
	}
}

// Any 回傳是否動用了任何受追蹤資源。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 供報告以單一布林快速標記「有/無使用外部資源」
// @ai:input none
// @ai:output bool（任一資源次數 > 0 即為 true）
// @ai:sideeffect none
func (s Stats) Any() bool { return s.DB > 0 || s.Redis > 0 || s.Cassandra > 0 }

// UsesStorage 回傳是否動用了任何資料儲存資源（關聯式 DB、Cassandra 或 Redis）。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-15
// @ai:purpose 對應報告的「使用資料儲存」欄位；DB、Cassandra、Redis 皆計入（Redis 亦視為資料儲存）
// @ai:input none
// @ai:output bool（DB / Cassandra / Redis 任一次數 > 0 即為 true）
// @ai:sideeffect none
func (s Stats) UsesStorage() bool { return s.DB > 0 || s.Cassandra > 0 || s.Redis > 0 }
