// @ai:generated by=claude-opus-4-7 date=2026-06-21
// @ai:purpose 為 Go 原始檔自動產生缺少的 *_test.go 骨架
// Package testgen 掃描 Go 原始檔的 exported func / method，找出尚未存在的 Test*，
// 並生成對應的測試骨架檔案（或追加到既有 *_test.go）。
//
// 設計原則：
//   - 不覆蓋既有 Test*（即使是空殼也保留）
//   - 不假裝有測試 → 骨架預設 t.Skip("auto-generated stub")，CI 看得到
//   - 純 AST 分析，不執行程式碼
//   - 跳過明確標記 //hyp:notest 的函式
package testgen

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Report 描述單一檔案的處理結果
type Report struct {
	SourceFile string   // 原始 .go 檔案
	TestFile   string   // 對應的 *_test.go
	Created    bool     // 是否第一次建立 test 檔
	Added      []string // 新加入的 Test 函式名稱
	Skipped    []string // 已存在的 Test 名稱（被跳過）
	NoTestNeed []string // 標記 //hyp:notest 而被略過的函式
}

// Options 控制產生行為
type Options struct {
	// IncludeUnexported 是否也為 unexported func / method 產生測試
	// 預設 false：只為 exported（首字母大寫）函式產生測試。
	IncludeUnexported bool

	// DryRun 為 true 時只回報會做什麼，不寫入任何檔案
	DryRun bool

	// Comment 寫在 t.Skip 訊息裡的提示文字，預設 "auto-generated stub; replace with real assertions"
	StubMessage string
}

// DefaultOptions 回傳預設 Options
func DefaultOptions() Options {
	return Options{
		IncludeUnexported: false,
		DryRun:            false,
		StubMessage:       "auto-generated stub; replace with real assertions",
	}
}

// GenerateForFile 為單一 .go 檔生成缺少的測試骨架
// 已存在的 Test* 不會被覆蓋。
func GenerateForFile(filename string, opts Options) (*Report, error) {
	if !strings.HasSuffix(filename, ".go") {
		return nil, fmt.Errorf("not a .go file: %s", filename)
	}
	if strings.HasSuffix(filename, "_test.go") {
		return nil, fmt.Errorf("cannot process *_test.go directly: %s", filename)
	}

	srcContent, err := os.ReadFile(filename)
	if err != nil {
		return nil, fmt.Errorf("read source: %w", err)
	}

	fset := token.NewFileSet()
	srcAST, err := parser.ParseFile(fset, filename, srcContent, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse source: %w", err)
	}

	pkgName := srcAST.Name.Name

	// 收集本檔案中需要被測試的函式
	candidates := collectCandidates(srcAST, srcContent, fset, opts)

	// 推導 test 檔案路徑：foo.go → foo_test.go（同目錄）
	testPath := strings.TrimSuffix(filename, ".go") + "_test.go"
	report := &Report{SourceFile: filename, TestFile: testPath}

	// 把標記 notest 的函式也記錄
	for _, c := range candidates {
		if c.skipNoTest {
			report.NoTestNeed = append(report.NoTestNeed, c.testName)
		}
	}
	candidates = filterNoTest(candidates)
	if len(candidates) == 0 {
		return report, nil
	}

	existingTests, testFileExists, err := loadExistingTestNames(testPath)
	if err != nil {
		return nil, err
	}
	report.Created = !testFileExists

	var toAdd []candidate
	for _, c := range candidates {
		if existingTests[c.testName] {
			report.Skipped = append(report.Skipped, c.testName)
			continue
		}
		toAdd = append(toAdd, c)
		report.Added = append(report.Added, c.testName)
	}

	if len(toAdd) == 0 {
		return report, nil
	}
	if opts.DryRun {
		return report, nil
	}

	if err := writeTestFile(testPath, pkgName, testFileExists, toAdd, opts); err != nil {
		return nil, fmt.Errorf("write %s: %w", testPath, err)
	}
	return report, nil
}

// GenerateForDir 遞迴處理 rootDir 下的所有 .go 檔（跳過 vendor / .git / node_modules / .hyp / testdata）
func GenerateForDir(rootDir string, opts Options) ([]Report, error) {
	var reports []Report
	err := filepath.WalkDir(rootDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if name == "vendor" || name == ".git" || name == "node_modules" ||
				name == ".hyp" || name == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		rep, genErr := GenerateForFile(path, opts)
		if genErr != nil {
			fmt.Fprintf(os.Stderr, "  ! %s: %v\n", path, genErr)
			return nil
		}
		if rep != nil && (len(rep.Added) > 0 || len(rep.Skipped) > 0 || len(rep.NoTestNeed) > 0) {
			reports = append(reports, *rep)
		}
		return nil
	})
	return reports, err
}

// --- internal ---

type candidate struct {
	funcName    string // 原始函式名（含 receiver 樣式：Svc_DoThing）
	testName    string // 對應的 Test 名稱
	isMethod    bool
	receiverStr string // 用於 method（例：*Svc）
	skipNoTest  bool   // 是否標記 //hyp:notest
}

// collectCandidates 從 AST 抽出所有要產測試的 func / method
func collectCandidates(f *ast.File, src []byte, fset *token.FileSet, opts Options) []candidate {
	var out []candidate

	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Body == nil {
			continue
		}
		name := fd.Name.Name
		// 跳過已經是 Test/Benchmark/Example/Fuzz 前綴的（雖然這檔不該是 _test.go，仍保險過濾）
		if isReservedTestPrefix(name) {
			continue
		}
		if !opts.IncludeUnexported && !ast.IsExported(name) {
			continue
		}

		c := candidate{funcName: name}
		if fd.Recv != nil && len(fd.Recv.List) > 0 {
			c.isMethod = true
			c.receiverStr = exprString(fd.Recv.List[0].Type)
			recvBase := strings.TrimPrefix(c.receiverStr, "*")
			c.testName = "Test" + recvBase + "_" + name
		} else {
			c.testName = "Test" + name
		}

		// 檢查 doc comment 是否含 //hyp:notest
		if fd.Doc != nil {
			for _, cm := range fd.Doc.List {
				if strings.Contains(cm.Text, "//hyp:notest") || strings.Contains(cm.Text, "// hyp:notest") {
					c.skipNoTest = true
					break
				}
			}
		}

		out = append(out, c)
	}
	_ = fset
	_ = src
	return out
}

func filterNoTest(in []candidate) []candidate {
	var out []candidate
	for _, c := range in {
		if !c.skipNoTest {
			out = append(out, c)
		}
	}
	return out
}

func isReservedTestPrefix(name string) bool {
	for _, prefix := range []string{"Test", "Benchmark", "Example", "Fuzz"} {
		if strings.HasPrefix(name, prefix) && len(name) > len(prefix) {
			next := name[len(prefix)]
			if next >= 'A' && next <= 'Z' || next == '_' {
				return true
			}
		}
	}
	return false
}

func exprString(e ast.Expr) string {
	switch v := e.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.StarExpr:
		return "*" + exprString(v.X)
	case *ast.SelectorExpr:
		return exprString(v.X) + "." + v.Sel.Name
	default:
		return fmt.Sprintf("%T", e)
	}
}

// loadExistingTestNames 從目標 _test.go（若存在）抽出已定義的 Test* 名稱
// 回傳：testName→true 對照表、檔案是否存在、錯誤
func loadExistingTestNames(testPath string) (map[string]bool, bool, error) {
	out := map[string]bool{}
	info, err := os.Stat(testPath)
	if os.IsNotExist(err) {
		return out, false, nil
	}
	if err != nil {
		return out, false, fmt.Errorf("stat test file: %w", err)
	}
	if info.IsDir() {
		return out, false, fmt.Errorf("%s is a directory", testPath)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, testPath, nil, parser.SkipObjectResolution)
	if err != nil {
		// 既有檔案語法錯誤 → 視為「不知道有什麼」並警告呼叫端
		return out, true, fmt.Errorf("parse existing test file %s: %w", testPath, err)
	}
	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if strings.HasPrefix(fd.Name.Name, "Test") {
			out[fd.Name.Name] = true
		}
	}
	return out, true, nil
}

// writeTestFile 把新測試骨架寫進 testPath。
// fileExists=true 時用 append；否則寫入完整新檔。
func writeTestFile(testPath, pkgName string, fileExists bool, items []candidate, opts Options) error {
	if fileExists {
		// 用 append 模式：產生只含新 Test 區塊的片段
		f, err := os.OpenFile(testPath, os.O_APPEND|os.O_WRONLY, 0644)
		if err != nil {
			return err
		}
		defer f.Close()
		bw := bufio.NewWriter(f)
		bw.WriteString("\n")
		for _, c := range items {
			bw.WriteString(renderTestStub(c, opts) + "\n")
		}
		return bw.Flush()
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// Code generated by hyp testgen. Replace stubs with real assertions.\n"))
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	sb.WriteString("import \"testing\"\n\n")
	for i, c := range items {
		if i > 0 {
			sb.WriteString("\n")
		}
		sb.WriteString(renderTestStub(c, opts))
	}
	return os.WriteFile(testPath, []byte(sb.String()), 0644)
}

// renderTestStub 產生單一 Test 函式骨架
func renderTestStub(c candidate, opts Options) string {
	msg := opts.StubMessage
	if msg == "" {
		msg = "auto-generated stub"
	}
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// %s — auto-generated stub for %s\n", c.testName, c.funcName))
	if c.isMethod {
		sb.WriteString(fmt.Sprintf("// Target: (%s).%s\n", c.receiverStr, c.funcName))
	} else {
		sb.WriteString(fmt.Sprintf("// Target: %s\n", c.funcName))
	}
	sb.WriteString(fmt.Sprintf("func %s(t *testing.T) {\n", c.testName))
	sb.WriteString(fmt.Sprintf("\tt.Skip(%q)\n", msg))
	sb.WriteString("}\n")
	return sb.String()
}

// FormatReports 把 GenerateForDir 的結果整理成終端可讀的報告
func FormatReports(reports []Report) string {
	var sb strings.Builder
	created, added, skipped, notest := 0, 0, 0, 0
	for _, r := range reports {
		if len(r.Added) == 0 && len(r.Skipped) == 0 && len(r.NoTestNeed) == 0 {
			continue
		}
		mark := "~"
		if r.Created {
			mark = "+"
			created++
		}
		sb.WriteString(fmt.Sprintf("  %s %s → %s\n", mark, r.SourceFile, r.TestFile))
		if len(r.Added) > 0 {
			added += len(r.Added)
			sb.WriteString(fmt.Sprintf("      added:    %s\n", strings.Join(r.Added, ", ")))
		}
		if len(r.Skipped) > 0 {
			skipped += len(r.Skipped)
			sb.WriteString(fmt.Sprintf("      kept:     %s\n", strings.Join(r.Skipped, ", ")))
		}
		if len(r.NoTestNeed) > 0 {
			notest += len(r.NoTestNeed)
			sb.WriteString(fmt.Sprintf("      notest:   %s\n", strings.Join(r.NoTestNeed, ", ")))
		}
	}
	sb.WriteString(fmt.Sprintf("\nSummary: %d files (created=%d), %d Test stubs added, %d kept, %d marked //hyp:notest\n",
		len(reports), created, added, skipped, notest))
	return sb.String()
}
