// @ai:generated by=claude-opus-4-7 date=2026-06-18
package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDefaultCommentConfig(t *testing.T) {
	cfg := DefaultCommentConfig()
	if !cfg.NormalComment {
		t.Error("NormalComment should default to true")
	}
	if cfg.AIComment {
		t.Error("AIComment should default to false")
	}
	if cfg.ThinkComment {
		t.Error("ThinkComment should default to false")
	}
}

func TestLoadCommentConfig_Empty(t *testing.T) {
	cfg, err := LoadCommentConfig("")
	if err != nil {
		t.Fatal(err)
	}
	if !cfg.NormalComment || cfg.AIComment || cfg.ThinkComment {
		t.Errorf("expected defaults, got %+v", cfg)
	}
}

func TestLoadCommentConfig_Missing(t *testing.T) {
	cfg, err := LoadCommentConfig("/nonexistent/comment.yaml")
	if err != nil {
		t.Fatal(err)
	}
	if !cfg.NormalComment {
		t.Error("missing file should return defaults")
	}
}

func TestLoadCommentConfig_AllOn(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "comment.yaml")
	yaml := "normal_comment: true\nai_comment: true\nthink_comment: true\n"
	if err := os.WriteFile(path, []byte(yaml), 0644); err != nil {
		t.Fatal(err)
	}
	cfg, err := LoadCommentConfig(path)
	if err != nil {
		t.Fatal(err)
	}
	if !cfg.NormalComment || !cfg.AIComment || !cfg.ThinkComment {
		t.Errorf("expected all true, got %+v", cfg)
	}
}

func TestLoadCommentConfig_AIOnly(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "comment.yaml")
	yaml := "normal_comment: false\nai_comment: true\nthink_comment: false\n"
	if err := os.WriteFile(path, []byte(yaml), 0644); err != nil {
		t.Fatal(err)
	}
	cfg, err := LoadCommentConfig(path)
	if err != nil {
		t.Fatal(err)
	}
	if cfg.NormalComment || !cfg.AIComment || cfg.ThinkComment {
		t.Errorf("got %+v", cfg)
	}
}

func TestLoadCommentConfig_Malformed(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "comment.yaml")
	if err := os.WriteFile(path, []byte("not: valid: yaml: ["), 0644); err != nil {
		t.Fatal(err)
	}
	_, err := LoadCommentConfig(path)
	if err == nil {
		t.Error("expected error on malformed yaml")
	}
}
