// @ai:generated by=claude-opus-4-7 date=2026-06-18
// @ai:purpose 載入 .hyp/comment.yaml 註釋開關設定，控制 ai-rules 生成的規則內容
package config

import (
	"fmt"
	"os"
)

// CommentConfig 控制 ai-rules 模板要寫入哪些註釋類型的規範。
// 每個欄位代表「AI 在生成程式碼時是否需要寫這類註釋」。
type CommentConfig struct {
	// NormalComment 控制是否生成普通註釋（如 godoc、函式說明）。預設 true。
	NormalComment bool `mapstructure:"normal_comment" yaml:"normal_comment"`

	// AIComment 控制是否生成 @ai 系列註釋（@ai:generated、@ai:purpose、
	// @ai:input、@ai:output、@ai:sideeffect 等）。不包含 @ai:think。預設 false。
	AIComment bool `mapstructure:"ai_comment" yaml:"ai_comment"`

	// ThinkComment 控制是否生成 @ai:think 函式體內意圖註釋。預設 false。
	ThinkComment bool `mapstructure:"think_comment" yaml:"think_comment"`
}

// DefaultCommentConfig 回傳預設值：只開啟普通註釋。
func DefaultCommentConfig() *CommentConfig {
	return &CommentConfig{
		NormalComment: true,
		AIComment:     false,
		ThinkComment:  false,
	}
}

// LoadCommentConfig 從指定路徑載入 CommentConfig；檔案不存在時回傳預設值。
// @ai:input path = .hyp/comment.yaml 路徑（可空）
// @ai:output *CommentConfig + error
// @ai:sideeffect 讀取檔案
func LoadCommentConfig(path string) (*CommentConfig, error) {
	cfg := DefaultCommentConfig()

	if path == "" {
		return cfg, nil
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		return cfg, nil
	}

	// 先以「不存在 = 預設」處理，再嘗試載入；載入失敗回 error 讓使用者察覺格式問題
	if err := LoadYAML(path, cfg); err != nil {
		return nil, fmt.Errorf("failed to load comment config from %s: %w", path, err)
	}

	return cfg, nil
}

// DefaultCommentYAML 為 hyp new / hyp api 寫入 .hyp/comment.yaml 的初始內容。
// 含完整註解說明，方便使用者理解每個開關的影響。
const DefaultCommentYAML = `# HypGo 註釋開關設定
# 放置於 .hyp/comment.yaml
#
# 這三個開關控制 hyp ai-rules 生成的規則檔（AGENTS.md/CLAUDE.md/CURSOR…）
# 會要求 AI 寫哪些類型的註釋。打開 = 規則檔包含該規範；關閉 = 該規範不出現。
#
# 預設只啟用「普通註釋」，符合最低噪音原則；
# 想開啟完整 AI 協作鏈時把另外兩個改為 true，再重新 hyp ai-rules 即可。

# 普通註釋（godoc、函式說明）。預設 true。
normal_comment: true

# @ai 系列註釋（@ai:generated / @ai:purpose / @ai:input / @ai:output / @ai:sideeffect）
# 不含 @ai:think。預設 false。
ai_comment: false

# @ai:think 函式體內意圖註釋（intent / special / model）。預設 false。
think_comment: false
`
