// @ai:generated by=claude-opus-4-7 date=2026-06-19
package config

import (
	"strings"
	"testing"
)

// 任意 provider 名稱（含中文、版本號等）只要有 base_url 都應通過
func TestLLMConfig_Validate_AcceptsAnyProviderWithBaseURL(t *testing.T) {
	t.Setenv("FAKE_KEY", "x")
	tests := []struct {
		provider string
	}{
		{"Qwen3.6"},
		{"llama-cpp"},
		{"deepseek-r1"},
		{"my-internal-proxy"},
		{"custom"},
		{"openai"}, // 既有名稱仍可用，base_url 用內建預設
	}
	for _, tt := range tests {
		cfg := &LLMConfig{
			Mode: "api",
			API: APIConfig{
				Provider: tt.provider,
				Model:    "any-model",
				APIKey:   "${FAKE_KEY}",
			},
		}
		// openai/anthropic/gemini 不需要設 base_url（ApplyDefaults 會填）
		if !hasBuiltinBaseURL(tt.provider) {
			cfg.API.BaseURL = "http://localhost:18080"
		}
		cfg.ApplyDefaults()
		if err := cfg.Validate(); err != nil {
			t.Errorf("provider=%q expected to pass, got: %v", tt.provider, err)
		}
	}
}

// provider 不在白名單 + 沒有 base_url 應該回特定錯誤
func TestLLMConfig_Validate_RejectsUnknownProviderWithoutBaseURL(t *testing.T) {
	t.Setenv("FAKE_KEY", "x")
	cfg := &LLMConfig{
		Mode: "api",
		API: APIConfig{
			Provider: "Qwen3.6",
			Model:    "any",
			APIKey:   "${FAKE_KEY}",
			// 故意不填 BaseURL
		},
	}
	cfg.ApplyDefaults()
	err := cfg.Validate()
	if err == nil {
		t.Fatal("expected error when unknown provider has no base_url")
	}
	if !strings.Contains(err.Error(), "base_url is required") {
		t.Errorf("error should mention base_url: %v", err)
	}
}

func TestHasBuiltinBaseURL(t *testing.T) {
	if !hasBuiltinBaseURL("openai") {
		t.Error("openai should have builtin base url")
	}
	if !hasBuiltinBaseURL("anthropic") {
		t.Error("anthropic should have builtin base url")
	}
	if !hasBuiltinBaseURL("gemini") {
		t.Error("gemini should have builtin base url")
	}
	if hasBuiltinBaseURL("custom") {
		t.Error("custom should NOT have builtin")
	}
	if hasBuiltinBaseURL("Qwen3.6") {
		t.Error("Qwen3.6 should NOT have builtin")
	}
}
