// Package grpc 提供 gRPC Server 封裝
// 統一管理 listener、interceptor、reflection、health check、graceful shutdown
//
// @ai:generated by=claude-opus-4-6 date=2026-02-27
package grpc

import (
	"crypto/tls"
	"fmt"
	"net"
	"sync/atomic"
	"time"

	"github.com/maoxiaoyue/hypgo/pkg/logger"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/health"
	healthpb "google.golang.org/grpc/health/grpc_health_v1"
	"google.golang.org/grpc/keepalive"
	"google.golang.org/grpc/reflection"
)

// Config gRPC Server 配置
type Config struct {
	// Addr 監聽地址（如 ":9090"）
	Addr string

	// TLS 配置（nil 表示不使用 TLS）
	TLS *TLSConfig

	// EnableReflection 是否啟用 gRPC reflection（方便 grpcurl 偵錯）
	EnableReflection bool

	// EnableHealthCheck 是否啟用 gRPC 健康檢查服務
	EnableHealthCheck bool

	// MaxRecvMsgSize 最大接收訊息大小（bytes，預設 4MB）
	MaxRecvMsgSize int

	// MaxSendMsgSize 最大發送訊息大小（bytes，預設 4MB）
	MaxSendMsgSize int

	// ===== 連線與吞吐調校（零值 = 沿用 grpc-go 預設） =====

	// MaxConnectionIdle 連線閒置多久後送 GOAWAY 關閉。
	// grpc-go 預設無限——NAT/LB 後的死連線只有寫入失敗才被發現，
	// 閒置連線永久佔用 framer goroutine 與緩衝。建議 15m
	MaxConnectionIdle time.Duration

	// KeepaliveTime 多久沒活動就對客戶端發 ping（建議 2h）
	KeepaliveTime time.Duration

	// KeepaliveTimeout ping 後等多久沒回應即判定連線死亡（建議 20s）
	KeepaliveTimeout time.Duration

	// InitialWindowSize 每個 stream 的初始流量窗口（bytes）。
	// grpc-go 從 64KB 起由 BDP 探測自動放大；已知高吞吐 × 高延遲
	// 的部署可直接給大窗口，省掉大型串流回應的爬升期
	InitialWindowSize int32

	// InitialConnWindowSize 整條連線的初始流量窗口（bytes）
	InitialConnWindowSize int32

	// NumStreamWorkers 處理 stream 的固定 worker 數。
	// 預設 0 = 每個 RPC 起一個新 goroutine；高 QPS 下是持續的
	// goroutine 建立/銷毀與棧配置成本。建議 runtime.GOMAXPROCS(0)
	NumStreamWorkers uint32

	// MaxConcurrentStreams 單連線併發 stream 上限。
	// 預設無上限——單一失控客戶端可無限堆積併發 handler
	MaxConcurrentStreams uint32
}

// TLSConfig TLS 配置
type TLSConfig struct {
	CertFile string
	KeyFile  string
}

// Server gRPC 伺服器封裝
type Server struct {
	config     Config
	grpcServer *grpc.Server
	logger     *logger.Logger
	// listener 用 atomic.Value：Start() 通常跑在自己的 goroutine，
	// 而 Addr() 由呼叫端（測試、健康檢查、註冊服務探測）從另一個 goroutine 讀，
	// 裸欄位會是資料競態（go test -race 可穩定重現）
	listener     atomic.Value
	healthServer *health.Server
	shuttingDown atomic.Bool
}

// getListener 取得目前已發布的 listener（尚未 Start 時為 nil）
func (s *Server) getListener() net.Listener {
	v := s.listener.Load()
	if v == nil {
		return nil
	}
	return v.(net.Listener)
}

// New 建立新的 gRPC Server
func New(cfg Config, log *logger.Logger, opts ...grpc.ServerOption) *Server {
	s := &Server{
		config: cfg,
		logger: log,
	}

	// 預設值
	if s.config.Addr == "" {
		s.config.Addr = ":9090"
	}

	// 組裝 server options
	serverOpts := make([]grpc.ServerOption, 0, len(opts)+4)

	// TLS
	if cfg.TLS != nil && cfg.TLS.CertFile != "" {
		cert, err := tls.LoadX509KeyPair(cfg.TLS.CertFile, cfg.TLS.KeyFile)
		if err != nil {
			log.Errorf("Failed to load TLS certificate: %v", err)
		} else {
			tlsConfig := &tls.Config{
				Certificates: []tls.Certificate{cert},
				MinVersion:   tls.VersionTLS12,
			}
			serverOpts = append(serverOpts, grpc.Creds(credentials.NewTLS(tlsConfig)))
		}
	}

	// 訊息大小限制
	if cfg.MaxRecvMsgSize > 0 {
		serverOpts = append(serverOpts, grpc.MaxRecvMsgSize(cfg.MaxRecvMsgSize))
	}
	if cfg.MaxSendMsgSize > 0 {
		serverOpts = append(serverOpts, grpc.MaxSendMsgSize(cfg.MaxSendMsgSize))
	}

	// 連線與吞吐調校（只在有設定時附加，零值沿用 grpc-go 預設）
	if cfg.MaxConnectionIdle > 0 || cfg.KeepaliveTime > 0 || cfg.KeepaliveTimeout > 0 {
		serverOpts = append(serverOpts, grpc.KeepaliveParams(keepalive.ServerParameters{
			MaxConnectionIdle: cfg.MaxConnectionIdle,
			Time:              cfg.KeepaliveTime,
			Timeout:           cfg.KeepaliveTimeout,
		}))
	}
	if cfg.InitialWindowSize > 0 {
		serverOpts = append(serverOpts, grpc.InitialWindowSize(cfg.InitialWindowSize))
	}
	if cfg.InitialConnWindowSize > 0 {
		serverOpts = append(serverOpts, grpc.InitialConnWindowSize(cfg.InitialConnWindowSize))
	}
	if cfg.NumStreamWorkers > 0 {
		serverOpts = append(serverOpts, grpc.NumStreamWorkers(cfg.NumStreamWorkers))
	}
	if cfg.MaxConcurrentStreams > 0 {
		serverOpts = append(serverOpts, grpc.MaxConcurrentStreams(cfg.MaxConcurrentStreams))
	}

	// 使用者自訂 options（interceptor 等）
	serverOpts = append(serverOpts, opts...)

	s.grpcServer = grpc.NewServer(serverOpts...)

	// Reflection（grpcurl 偵錯用）
	if cfg.EnableReflection {
		reflection.Register(s.grpcServer)
	}

	// Health check
	if cfg.EnableHealthCheck {
		s.healthServer = health.NewServer()
		healthpb.RegisterHealthServer(s.grpcServer, s.healthServer)
	}

	return s
}

// GRPCServer 返回底層 grpc.Server（用於註冊服務）
func (s *Server) GRPCServer() *grpc.Server {
	return s.grpcServer
}

// SetServingStatus 設定服務健康狀態（需啟用 EnableHealthCheck）
func (s *Server) SetServingStatus(service string, status healthpb.HealthCheckResponse_ServingStatus) {
	if s.healthServer != nil {
		s.healthServer.SetServingStatus(service, status)
	}
}

// Start 啟動 gRPC Server（阻塞）
func (s *Server) Start() error {
	lis, err := net.Listen("tcp", s.config.Addr)
	if err != nil {
		return fmt.Errorf("grpc: failed to listen on %s: %w", s.config.Addr, err)
	}
	s.listener.Store(lis)

	if s.logger != nil {
		protocol := "plaintext"
		if s.config.TLS != nil {
			protocol = "TLS"
		}
		s.logger.Infof("gRPC server listening on %s (%s)", s.config.Addr, protocol)
	}

	// 標記所有服務為 SERVING
	if s.healthServer != nil {
		s.healthServer.SetServingStatus("", healthpb.HealthCheckResponse_SERVING)
	}

	return s.grpcServer.Serve(lis)
}

// GracefulStop 優雅關閉（等待進行中的 RPC 完成）
func (s *Server) GracefulStop() {
	if s.shuttingDown.Swap(true) {
		return // 已在關閉中
	}

	if s.logger != nil {
		s.logger.Info("gRPC server shutting down gracefully...")
	}

	// 標記為 NOT_SERVING
	if s.healthServer != nil {
		s.healthServer.SetServingStatus("", healthpb.HealthCheckResponse_NOT_SERVING)
	}

	s.grpcServer.GracefulStop()

	if s.logger != nil {
		s.logger.Info("gRPC server stopped")
	}
}

// Stop 立即停止（不等待）
func (s *Server) Stop() {
	s.shuttingDown.Store(true)
	s.grpcServer.Stop()
}

// IsShuttingDown 是否正在關閉
func (s *Server) IsShuttingDown() bool {
	return s.shuttingDown.Load()
}

// Addr 返回實際監聽地址（Start 後有效）
func (s *Server) Addr() string {
	if lis := s.getListener(); lis != nil {
		return lis.Addr().String()
	}
	return s.config.Addr
}
