package cassandra

import (
	"context"
	"crypto/tls"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/gocql/gocql"
)

// TLSConfig holds optional TLS settings for the CQL connection.
type TLSConfig struct {
	Enabled            bool   `mapstructure:"enabled" yaml:"enabled"`
	CertFile           string `mapstructure:"cert_file" yaml:"cert_file"`
	KeyFile            string `mapstructure:"key_file" yaml:"key_file"`
	CaFile             string `mapstructure:"ca_file" yaml:"ca_file"`
	ServerName         string `mapstructure:"server_name" yaml:"server_name"`
	InsecureSkipVerify bool   `mapstructure:"insecure_skip_verify" yaml:"insecure_skip_verify"`
	// Config, when set, overrides CertFile/KeyFile/CaFile and is passed
	// directly to gocql via SslOptions.Config.
	Config *tls.Config `mapstructure:"-" yaml:"-"`
}

// Config Cassandra 配置
type Config struct {
	Hosts            []string      `mapstructure:"hosts" yaml:"hosts"`
	Keyspace         string        `mapstructure:"keyspace" yaml:"keyspace"`
	Consistency      string        `mapstructure:"consistency" yaml:"consistency"` // "one", "quorum", "all", "local_quorum" 等
	Port             int           `mapstructure:"port" yaml:"port"`               // 預設 9042
	Username         string        `mapstructure:"username" yaml:"username"`
	Password         string        `mapstructure:"password" yaml:"password"`
	ConnectTimeout   time.Duration `mapstructure:"connect_timeout" yaml:"connect_timeout"` // 預設 5s
	Timeout          time.Duration `mapstructure:"timeout" yaml:"timeout"`                 // 預設 10s
	NumConns         int           `mapstructure:"num_conns" yaml:"num_conns"`             // 每個主機的連接數
	MaxPreparedStmts int           `mapstructure:"max_prepared_stmts" yaml:"max_prepared_stmts"`
	ProtoVersion     int           `mapstructure:"proto_version" yaml:"proto_version"` // 預設 4

	// Retry / Reconnect — 預設 production-friendly。設為負值關閉。
	NumRetries        int           `mapstructure:"num_retries" yaml:"num_retries"`               // 預設 3
	RetryMinDelay     time.Duration `mapstructure:"retry_min_delay" yaml:"retry_min_delay"`       // 預設 100ms
	RetryMaxDelay     time.Duration `mapstructure:"retry_max_delay" yaml:"retry_max_delay"`       // 預設 10s
	ReconnectInterval time.Duration `mapstructure:"reconnect_interval" yaml:"reconnect_interval"` // 預設 1s
	ReconnectMax      int           `mapstructure:"reconnect_max" yaml:"reconnect_max"`           // 預設 10

	// TLS 連線設定（dev 環境留空即可）
	TLS TLSConfig `mapstructure:"tls" yaml:"tls"`

	// QueryObserver 注入點，提供 latency / error / pool metrics（gocql QueryObserver）。
	// 注意：此欄位不從 YAML 解析，僅供程式碼直接設定。
	QueryObserver gocql.QueryObserver `mapstructure:"-" yaml:"-"`

	// StrictConsistency=true 時，Consistency 字串無法解析會直接回 error。
	// 預設 false → 無法解析時 fallback 為 LocalOne（並非 Quorum，更利於單節點 dev）。
	StrictConsistency bool `mapstructure:"strict_consistency" yaml:"strict_consistency"`
}

// CassandraDB Cassandra 數據庫管理器
type CassandraDB struct {
	cluster *gocql.ClusterConfig
	session *gocql.Session
	config  Config

	mu     sync.Mutex
	closed bool
}

// New 創建 Cassandra 實例並建立連接。
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 一步完成 cluster 設定 + session 建立，呼叫端拿到即可使用
// @ai:input Config（必填 Hosts；其餘有預設值）
// @ai:output 已連線的 *CassandraDB 或設定 / 連線錯誤
// @ai:sideeffect 建立 gocql Session（TCP 連線到 Cassandra cluster）
func New(cfg Config) (*CassandraDB, error) {
	c := &CassandraDB{
		config: cfg,
	}

	if err := c.init(); err != nil {
		return nil, err
	}

	if err := c.Connect(); err != nil {
		return nil, err
	}

	return c, nil
}

// NewWithoutConnect 創建 Cassandra 實例但不立即連接。
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 用於需要延遲連線的情境（測試 / DDL 預組）
// @ai:input Config
// @ai:output *CassandraDB（未連線）或設定錯誤
// @ai:sideeffect none
func NewWithoutConnect(cfg Config) (*CassandraDB, error) {
	c := &CassandraDB{
		config: cfg,
	}

	if err := c.init(); err != nil {
		return nil, err
	}

	return c, nil
}

// init 初始化 cluster 配置。
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
func (c *CassandraDB) init() error {
	if len(c.config.Hosts) == 0 {
		return fmt.Errorf("cassandra: at least one host is required")
	}

	cluster := gocql.NewCluster(c.config.Hosts...)

	// Keyspace
	if c.config.Keyspace != "" {
		cluster.Keyspace = c.config.Keyspace
	}

	// Consistency — 嚴格模式下拼錯直接 error，非嚴格 fallback 至 LocalOne
	cl, err := parseConsistencyStrict(c.config.Consistency)
	if err != nil {
		if c.config.StrictConsistency {
			return err
		}
		cl = gocql.LocalOne
	}
	cluster.Consistency = cl

	// Port
	if c.config.Port > 0 {
		cluster.Port = c.config.Port
	}

	// 認證
	if c.config.Username != "" {
		cluster.Authenticator = gocql.PasswordAuthenticator{
			Username: c.config.Username,
			Password: c.config.Password,
		}
	}

	// 超時設置
	if c.config.ConnectTimeout > 0 {
		cluster.ConnectTimeout = c.config.ConnectTimeout
	} else {
		cluster.ConnectTimeout = 5 * time.Second
	}

	if c.config.Timeout > 0 {
		cluster.Timeout = c.config.Timeout
	} else {
		cluster.Timeout = 10 * time.Second
	}

	// 連接池
	if c.config.NumConns > 0 {
		cluster.NumConns = c.config.NumConns
	}

	if c.config.MaxPreparedStmts > 0 {
		cluster.MaxPreparedStmts = c.config.MaxPreparedStmts
	}

	// 協議版本
	if c.config.ProtoVersion > 0 {
		cluster.ProtoVersion = c.config.ProtoVersion
	} else {
		cluster.ProtoVersion = 4
	}

	// Retry policy（NumRetries < 0 表示停用）
	if c.config.NumRetries >= 0 {
		retries := c.config.NumRetries
		if retries == 0 {
			retries = 3
		}
		minD := c.config.RetryMinDelay
		if minD <= 0 {
			minD = 100 * time.Millisecond
		}
		maxD := c.config.RetryMaxDelay
		if maxD <= 0 {
			maxD = 10 * time.Second
		}
		cluster.RetryPolicy = &gocql.ExponentialBackoffRetryPolicy{
			NumRetries: retries,
			Min:        minD,
			Max:        maxD,
		}
	}

	// Reconnection policy
	// ReconnectMax < 0 → 明確停用（覆寫 gocql 預設為 nil）
	// ReconnectMax = 0 → 使用 hidb 預設 (10 retries, 1s interval)
	// ReconnectMax > 0 → 使用使用者指定值
	if c.config.ReconnectMax < 0 {
		cluster.ReconnectionPolicy = nil
	} else {
		maxR := c.config.ReconnectMax
		if maxR == 0 {
			maxR = 10
		}
		intv := c.config.ReconnectInterval
		if intv <= 0 {
			intv = 1 * time.Second
		}
		cluster.ReconnectionPolicy = &gocql.ConstantReconnectionPolicy{
			MaxRetries: maxR,
			Interval:   intv,
		}
	}

	// TLS
	if c.config.TLS.Enabled {
		ssl, err := buildSslOptions(c.config.TLS)
		if err != nil {
			return fmt.Errorf("cassandra: tls config: %w", err)
		}
		cluster.SslOpts = ssl
	}

	// QueryObserver
	if c.config.QueryObserver != nil {
		cluster.QueryObserver = c.config.QueryObserver
	}

	c.cluster = cluster
	return nil
}

// buildSslOptions translates TLSConfig into gocql.SslOptions.
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
func buildSslOptions(t TLSConfig) (*gocql.SslOptions, error) {
	opts := &gocql.SslOptions{
		EnableHostVerification: !t.InsecureSkipVerify,
	}
	if t.Config != nil {
		opts.Config = t.Config
		return opts, nil
	}
	if t.CertFile != "" && t.KeyFile == "" {
		return nil, fmt.Errorf("cert_file set but key_file is empty")
	}
	opts.CertPath = t.CertFile
	opts.KeyPath = t.KeyFile
	opts.CaPath = t.CaFile
	if t.ServerName != "" {
		opts.Config = &tls.Config{ServerName: t.ServerName}
	}
	return opts, nil
}

// Connect 建立 Cassandra 連接（idempotent）。
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 安全建立或重建 session — 已連線時 no-op，重連時關閉舊 session 不洩漏
// @ai:input none
// @ai:output 連線錯誤或 nil
// @ai:sideeffect 建立 gocql.Session；重連時關閉舊 session
func (c *CassandraDB) Connect() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.closed {
		return fmt.Errorf("cassandra: cannot connect on closed instance")
	}
	if c.cluster == nil {
		return fmt.Errorf("cassandra: cluster config not initialized")
	}
	// 已有有效 session 則 no-op；舊 session 已關閉則先丟棄
	if c.session != nil {
		if !c.session.Closed() {
			return nil
		}
		c.session.Close()
		c.session = nil
	}

	session, err := c.cluster.CreateSession()
	if err != nil {
		return fmt.Errorf("cassandra: failed to create session: %w", err)
	}
	c.session = session
	return nil
}

// Session 獲取 gocql.Session（用戶直接操作 CQL）
func (c *CassandraDB) Session() *gocql.Session {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.session
}

// Close 關閉 Cassandra 連接（thread-safe，可重複呼叫）。
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 安全關閉 session — 多 goroutine 同時 / 重複呼叫不會 panic 或 double-close
// @ai:input none
// @ai:output nil（保留介面相容）
// @ai:sideeffect 關閉底層 gocql Session
func (c *CassandraDB) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.closed {
		return nil
	}
	if c.session != nil {
		c.session.Close()
		c.session = nil
	}
	c.closed = true
	return nil
}

// Ping 健康檢查。
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
func (c *CassandraDB) Ping(ctx context.Context) error {
	sess := c.Session()
	if sess == nil {
		return fmt.Errorf("cassandra: session not connected")
	}

	iter := sess.Query("SELECT now() FROM system.local").WithContext(ctx).Iter()
	if err := iter.Close(); err != nil {
		return fmt.Errorf("cassandra: ping failed: %w", err)
	}
	return nil
}

// IsConnected 檢查是否已連接。
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
func (c *CassandraDB) IsConnected() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.session == nil {
		return false
	}
	return !c.session.Closed()
}

// ===== DatabasePlugin 介面實現 =====

// Name 返回插件名稱。
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
func (c *CassandraDB) Name() string {
	return "cassandra"
}

// Init 從 map 配置初始化（用於插件系統動態加載）。
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 支援 hidb plugin 從 YAML/map 載入時所有欄位都能被解析（不只 hosts/auth）
// @ai:input map[string]interface{}（YAML decode 結果，hosts 可能為 []interface{}）
// @ai:output 設定 / 驗證錯誤或 nil
// @ai:sideeffect 重設 c.config 並重建 cluster 配置（不重連）
func (c *CassandraDB) Init(config map[string]interface{}) error {
	// hosts: 同時接受 []string 與 []interface{}（YAML decode 的型別）
	switch v := config["hosts"].(type) {
	case []string:
		c.config.Hosts = v
	case []interface{}:
		hosts := make([]string, 0, len(v))
		for _, h := range v {
			if s, ok := h.(string); ok {
				hosts = append(hosts, s)
			}
		}
		c.config.Hosts = hosts
	}

	if v, ok := config["keyspace"].(string); ok {
		c.config.Keyspace = v
	}
	if v, ok := config["consistency"].(string); ok {
		c.config.Consistency = v
	}
	if v, ok := config["port"].(int); ok {
		c.config.Port = v
	}
	if v, ok := config["username"].(string); ok {
		c.config.Username = v
	}
	if v, ok := config["password"].(string); ok {
		c.config.Password = v
	}
	if v, ok := asDuration(config["connect_timeout"]); ok {
		c.config.ConnectTimeout = v
	}
	if v, ok := asDuration(config["timeout"]); ok {
		c.config.Timeout = v
	}
	if v, ok := config["num_conns"].(int); ok {
		c.config.NumConns = v
	}
	if v, ok := config["max_prepared_stmts"].(int); ok {
		c.config.MaxPreparedStmts = v
	}
	if v, ok := config["proto_version"].(int); ok {
		c.config.ProtoVersion = v
	}
	if v, ok := config["num_retries"].(int); ok {
		c.config.NumRetries = v
	}
	if v, ok := asDuration(config["retry_min_delay"]); ok {
		c.config.RetryMinDelay = v
	}
	if v, ok := asDuration(config["retry_max_delay"]); ok {
		c.config.RetryMaxDelay = v
	}
	if v, ok := asDuration(config["reconnect_interval"]); ok {
		c.config.ReconnectInterval = v
	}
	if v, ok := config["reconnect_max"].(int); ok {
		c.config.ReconnectMax = v
	}
	if v, ok := config["strict_consistency"].(bool); ok {
		c.config.StrictConsistency = v
	}

	// nested tls block
	if tlsRaw, ok := config["tls"].(map[string]interface{}); ok {
		var t TLSConfig
		if v, ok := tlsRaw["enabled"].(bool); ok {
			t.Enabled = v
		}
		if v, ok := tlsRaw["cert_file"].(string); ok {
			t.CertFile = v
		}
		if v, ok := tlsRaw["key_file"].(string); ok {
			t.KeyFile = v
		}
		if v, ok := tlsRaw["ca_file"].(string); ok {
			t.CaFile = v
		}
		if v, ok := tlsRaw["server_name"].(string); ok {
			t.ServerName = v
		}
		if v, ok := tlsRaw["insecure_skip_verify"].(bool); ok {
			t.InsecureSkipVerify = v
		}
		c.config.TLS = t
	}

	return c.init()
}

// asDuration 接受 time.Duration、string（"5s"）或 int / int64（奈秒）。
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
func asDuration(v interface{}) (time.Duration, bool) {
	switch x := v.(type) {
	case time.Duration:
		return x, true
	case string:
		d, err := time.ParseDuration(x)
		return d, err == nil
	case int:
		return time.Duration(x), true
	case int64:
		return time.Duration(x), true
	default:
		return 0, false
	}
}

// ===== Cassandra 特殊功能 =====

// Query 執行 CQL 查詢（便捷方法）
func (c *CassandraDB) Query(stmt string, values ...interface{}) *gocql.Query {
	return c.session.Query(stmt, values...)
}

// QueryContext 執行帶 context 的 CQL 查詢
func (c *CassandraDB) QueryContext(ctx context.Context, stmt string, values ...interface{}) *gocql.Query {
	return c.session.Query(stmt, values...).WithContext(ctx)
}

// Exec executes a single CQL statement (DDL or DML) without returning rows.
// The statement may be terminated with a trailing ';', which is stripped
// before dispatch. For multi-statement scripts or parameterised CQL, use
// ExecScript or QueryContext respectively.
func (c *CassandraDB) Exec(ctx context.Context, stmt string) error {
	if c.session == nil {
		return fmt.Errorf("cassandra: session not connected")
	}
	stmt = strings.TrimSpace(stmt)
	stmt = strings.TrimRight(stmt, ";")
	stmt = strings.TrimRight(stmt, " \t\r\n")
	if stmt == "" {
		return nil
	}
	return c.session.Query(stmt).WithContext(ctx).Exec()
}

// ExecScript executes a multi-statement CQL script, ignoring empty segments.
// Bind args are not supported; use separate Exec calls for parameterised CQL.
func (c *CassandraDB) ExecScript(ctx context.Context, script string) error {
	for i, p := range splitStatements(script) {
		if err := c.session.Query(p).WithContext(ctx).Exec(); err != nil {
			return fmt.Errorf("cassandra: stmt %d failed: %w", i+1, err)
		}
	}
	return nil
}

// splitStatements splits a CQL script on top-level semicolons (ignoring those
// inside single-quoted literals and $$-delimited function bodies).
func splitStatements(src string) []string {
	var out []string
	var cur strings.Builder
	inSingle := false
	inDollar := false
	for i := 0; i < len(src); i++ {
		ch := src[i]
		switch {
		case !inSingle && !inDollar && ch == '\'':
			inSingle = true
			cur.WriteByte(ch)
		case inSingle && ch == '\'':
			inSingle = false
			cur.WriteByte(ch)
		case !inSingle && ch == '$' && i+1 < len(src) && src[i+1] == '$':
			inDollar = !inDollar
			cur.WriteByte(ch)
			cur.WriteByte(src[i+1])
			i++
		case !inSingle && !inDollar && ch == ';':
			s := strings.TrimSpace(cur.String())
			if s != "" {
				out = append(out, s)
			}
			cur.Reset()
		default:
			cur.WriteByte(ch)
		}
	}
	if s := strings.TrimSpace(cur.String()); s != "" {
		out = append(out, s)
	}
	return out
}

// Batch 創建批次操作（gocql 原生介面）
func (c *CassandraDB) Batch(batchType gocql.BatchType) *gocql.Batch {
	return c.session.NewBatch(batchType)
}

// ExecuteBatch 執行批次操作（gocql 原生介面）
func (c *CassandraDB) ExecuteBatch(batch *gocql.Batch) error {
	return c.session.ExecuteBatch(batch)
}

// KeyspaceName returns the current session keyspace (from config).
func (c *CassandraDB) KeyspaceName() string {
	return c.config.Keyspace
}

// parseConsistency 將字串轉換為 gocql.Consistency。
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 解析使用者設定字串；保留向後相容（不回 error），未知值 fallback 為 LocalOne
// @ai:input consistency 字串（"any" / "one" / "quorum" / "local_one" 等；大小寫不敏感）
// @ai:output gocql.Consistency；未知值 → LocalOne（不再像舊版 fallback 為 Quorum）
// @ai:sideeffect none
func parseConsistency(s string) gocql.Consistency {
	cl, err := parseConsistencyStrict(s)
	if err != nil {
		return gocql.LocalOne
	}
	return cl
}

// parseConsistencyStrict 嚴格解析；未知 / 拼錯回 error 而非 silent fallback。
// 空字串視為「未指定」，回傳 LocalOne 與 nil error。
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 阻止「設定拼錯但悄悄變 Quorum 害 dev 卡死」這個歷史 bug
// @ai:input consistency 字串
// @ai:output gocql.Consistency 或 error（不認得的值）
// @ai:sideeffect none
func parseConsistencyStrict(s string) (gocql.Consistency, error) {
	norm := strings.ReplaceAll(strings.TrimSpace(strings.ToLower(s)), "-", "_")
	switch norm {
	case "":
		return gocql.LocalOne, nil
	case "any":
		return gocql.Any, nil
	case "one":
		return gocql.One, nil
	case "two":
		return gocql.Two, nil
	case "three":
		return gocql.Three, nil
	case "quorum":
		return gocql.Quorum, nil
	case "all":
		return gocql.All, nil
	case "local_quorum", "localquorum":
		return gocql.LocalQuorum, nil
	case "each_quorum", "eachquorum":
		return gocql.EachQuorum, nil
	case "local_one", "localone":
		return gocql.LocalOne, nil
	default:
		return 0, fmt.Errorf("cassandra: unknown consistency level %q (valid: any/one/two/three/quorum/all/local_quorum/each_quorum/local_one)", s)
	}
}
