// @ai:generated by=claude-opus-4-6 date=2026-02-27
package cassandra

import (
	"context"
	"fmt"
	"strings"
)

// Permission represents a single Cassandra permission verb.
type Permission string

const (
	PermAll        Permission = "ALL PERMISSIONS"
	PermCreate     Permission = "CREATE"
	PermAlter      Permission = "ALTER"
	PermDrop       Permission = "DROP"
	PermSelect     Permission = "SELECT"
	PermModify     Permission = "MODIFY"
	PermAuthorize  Permission = "AUTHORIZE"
	PermDescribe   Permission = "DESCRIBE"
	PermExecute    Permission = "EXECUTE"
	PermUnmask     Permission = "UNMASK"
	PermSelectMask Permission = "SELECT_MASKED"
)

// ResourceKind enumerates the resource scopes a permission can target.
type ResourceKind string

const (
	ResAllKeyspaces ResourceKind = "ALL KEYSPACES"
	ResKeyspace     ResourceKind = "KEYSPACE"
	ResTable        ResourceKind = "TABLE"
	ResAllRoles     ResourceKind = "ALL ROLES"
	ResRole         ResourceKind = "ROLE"
	ResAllFunctions ResourceKind = "ALL FUNCTIONS"
	ResFunction     ResourceKind = "FUNCTION"
	ResMBean        ResourceKind = "MBEAN"
	ResAllMBeans    ResourceKind = "ALL MBEANS"
)

// Resource describes the target of a GRANT/REVOKE statement.
type Resource struct {
	Kind     ResourceKind
	Keyspace string
	Name     string // table / role / function / mbean name
}

func (r Resource) cql() (string, error) {
	switch r.Kind {
	case ResAllKeyspaces, ResAllRoles, ResAllFunctions, ResAllMBeans:
		return string(r.Kind), nil
	case ResKeyspace:
		if r.Keyspace == "" {
			return "", fmt.Errorf("cassandra: KEYSPACE resource requires Keyspace")
		}
		return "KEYSPACE " + quoteIdent(r.Keyspace), nil
	case ResTable:
		if r.Name == "" {
			return "", fmt.Errorf("cassandra: TABLE resource requires Name")
		}
		if r.Keyspace != "" {
			return "TABLE " + quoteIdent(r.Keyspace) + "." + quoteIdent(r.Name), nil
		}
		return "TABLE " + quoteIdent(r.Name), nil
	case ResRole:
		if r.Name == "" {
			return "", fmt.Errorf("cassandra: ROLE resource requires Name")
		}
		return "ROLE " + quoteIdent(r.Name), nil
	case ResFunction:
		if r.Name == "" {
			return "", fmt.Errorf("cassandra: FUNCTION resource requires Name")
		}
		if r.Keyspace != "" {
			return "FUNCTION " + quoteIdent(r.Keyspace) + "." + r.Name, nil
		}
		return "FUNCTION " + r.Name, nil
	case ResMBean:
		if r.Name == "" {
			return "", fmt.Errorf("cassandra: MBEAN resource requires Name")
		}
		return "MBEAN '" + strings.ReplaceAll(r.Name, "'", "''") + "'", nil
	default:
		return "", fmt.Errorf("cassandra: unknown resource kind %q", r.Kind)
	}
}

// AllKeyspaces is a convenience constructor for the ALL KEYSPACES resource.
func AllKeyspaces() Resource { return Resource{Kind: ResAllKeyspaces} }

// KeyspaceResource targets a single keyspace.
func KeyspaceResource(ks string) Resource { return Resource{Kind: ResKeyspace, Keyspace: ks} }

// TableResource targets "ks.table" or bare "table".
func TableResource(table string) Resource {
	ks, tbl := splitQualified(table)
	return Resource{Kind: ResTable, Keyspace: ks, Name: tbl}
}

// RoleResource targets a role.
func RoleResource(name string) Resource { return Resource{Kind: ResRole, Name: name} }

// ===== Grant / Revoke =====

// GrantCQL renders a GRANT statement.
func GrantCQL(perm Permission, res Resource, role string) (string, error) {
	r, err := res.cql()
	if err != nil {
		return "", err
	}
	if role == "" {
		return "", fmt.Errorf("cassandra: grant target role is required")
	}
	return fmt.Sprintf("GRANT %s ON %s TO %s", perm, r, quoteIdent(role)), nil
}

// Grant executes GRANT <perm> ON <resource> TO <role>.
func (c *CassandraDB) Grant(ctx context.Context, perm Permission, res Resource, role string) error {
	stmt, err := GrantCQL(perm, res, role)
	if err != nil {
		return err
	}
	return c.Exec(ctx, stmt)
}

