// @ai:generated by=claude-opus-4-6 date=2026-02-27
package cassandra

import (
	"context"
	"fmt"
	"sort"
	"time"

	"github.com/gocql/gocql"
)

// TraceSession is the decoded row from system_traces.sessions.
type TraceSession struct {
	SessionID      gocql.UUID
	Command        string
	Coordinator    string
	DurationMicros int
	Parameters     map[string]string
	Request        string
	StartedAt      time.Time
	ClientIP       string
}

// TraceEvent is a single row from system_traces.events, ordered by event_id.
type TraceEvent struct {
	SessionID     gocql.UUID
	EventID       gocql.UUID
	Activity      string
	Source        string
	SourceElapsed int // microseconds since the session started on this source
	Thread        string
}

// Trace groups a session with its ordered events.
type Trace struct {
	Session TraceSession
	Events  []TraceEvent
}

// Duration returns the total server-side duration of the traced request.
func (t Trace) Duration() time.Duration {
	return time.Duration(t.Session.DurationMicros) * time.Microsecond
}

// TotalElapsed returns the max SourceElapsed across events (approximate wall time).
func (t Trace) TotalElapsed() time.Duration {
	var max int
	for _, e := range t.Events {
		if e.SourceElapsed > max {
			max = e.SourceElapsed
		}
	}
	return time.Duration(max) * time.Microsecond
}

// ===== Server-side trace fetching =====

// GetTrace reads system_traces.sessions + system_traces.events for the given
// session ID. Cassandra writes traces asynchronously, so a short wait/retry
// loop is often needed; use WaitForTrace for that.
func (c *CassandraDB) GetTrace(ctx context.Context, sessionID gocql.UUID) (*Trace, error) {
	if c.session == nil {
		return nil, fmt.Errorf("cassandra: session not connected")
	}

	t := &Trace{Session: TraceSession{SessionID: sessionID}}

	// sessions row
	err := c.session.Query(
		`SELECT command, coordinator, duration, parameters, request, started_at, client
		 FROM system_traces.sessions WHERE session_id = ?`, sessionID,
	).WithContext(ctx).Scan(
		&t.Session.Command,
		&t.Session.Coordinator,
		&t.Session.DurationMicros,
		&t.Session.Parameters,
		&t.Session.Request,
		&t.Session.StartedAt,
		&t.Session.ClientIP,
	)
	if err != nil {
		if err == gocql.ErrNotFound {
			return nil, fmt.Errorf("cassandra: trace %s not yet available", sessionID)
		}
		return nil, fmt.Errorf("cassandra: read trace session: %w", err)
	}

	// events rows
	iter := c.session.Query(
		`SELECT event_id, activity, source, source_elapsed, thread
		 FROM system_traces.events WHERE session_id = ?`, sessionID,
	).WithContext(ctx).Iter()

	var ev TraceEvent
	ev.SessionID = sessionID
	for iter.Scan(&ev.EventID, &ev.Activity, &ev.Source, &ev.SourceElapsed, &ev.Thread) {
		t.Events = append(t.Events, ev)
		ev = TraceEvent{SessionID: sessionID}
	}
	if err := iter.Close(); err != nil {
		return nil, fmt.Errorf("cassandra: read trace events: %w", err)
	}

	// Events are clustered by event_id (timeuuid) which orders chronologically,
	// but sort by SourceElapsed as a secondary guarantee for display.
	sort.SliceStable(t.Events, func(i, j int) bool {
		return t.Events[i].SourceElapsed < t.Events[j].SourceElapsed
	})

	return t, nil
}

// ===== Formatting =====

// Format renders a trace as a human-readable multi-line string, similar to
// cqlsh's TRACING ON output.
func (t Trace) Format() string {
	var b writerBuilder
	fmt.Fprintf(&b, "Trace %s\n", t.Session.SessionID)
	fmt.Fprintf(&b, "  command      : %s\n", t.Session.Command)
	fmt.Fprintf(&b, "  coordinator  : %s\n", t.Session.Coordinator)
	fmt.Fprintf(&b, "  client       : %s\n", t.Session.ClientIP)
	fmt.Fprintf(&b, "  started_at   : %s\n", t.Session.StartedAt.Format(time.RFC3339Nano))
	fmt.Fprintf(&b, "  duration     : %s (server-reported)\n", t.Duration())
	fmt.Fprintf(&b, "  total elapsed: %s (max source_elapsed)\n", t.TotalElapsed())
	if t.Session.Request != "" {
		fmt.Fprintf(&b, "  request      : %s\n", t.Session.Request)
	}
	fmt.Fprintln(&b, "  events:")
	for _, e := range t.Events {
		fmt.Fprintf(&b, "    [%8dµs] %-15s %-20s %s\n",
			e.SourceElapsed, e.Source, truncate(e.Thread, 20), e.Activity)
	}
	return b.String()
}

type writerBuilder struct{ bs []byte }

func (w *writerBuilder) Write(p []byte) (int, error) { w.bs = append(w.bs, p...); return len(p), nil }
func (w *writerBuilder) String() string              { return string(w.bs) }

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	if n <= 1 {
		return s[:n]
	}
	return s[:n-1] + "…"
}
