package cassandra

import (
	"encoding/binary"
	"fmt"
	"math"
)

// Cassandra 5.0 vector codec helpers
// ----------------------------------------------------------------------
// gocql v1.7.0 does not natively recognise the Cassandra 5.0
// `vector<float, N>` type — it is delivered as a CUSTOM type at the
// wire level. These helpers let callers explicitly marshal / unmarshal
// a []float32 against the Cassandra 5.0 vector wire format
// (an N-element packed array of big-endian IEEE-754 binary32 values),
// independent of driver version.
//
// Use them when:
//   - You hit a "marshal: not enough/too many bytes to marshal" or
//     a "type mismatch: list<float> vs vector<float, N>" error from gocql.
//   - You want to insert/select via raw []byte bind values to bypass
//     the driver's type negotiation entirely.
//
// Once gocql adds first-class vector support these helpers can be retired.

// MarshalVectorFloat32 packs a []float32 into Cassandra 5.0 wire format.
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 繞過 gocql v1.7.0 對 vector<float,N> 的不足，直接編碼成 server 看得懂的 bytes
// @ai:input v=要寫入的向量；dim=schema 上宣告的維度（用來檢查長度一致）
// @ai:output 4*dim bytes 的 big-endian binary32 序列；長度不符則 error
// @ai:sideeffect none
func MarshalVectorFloat32(v []float32, dim int) ([]byte, error) {
	if dim <= 0 {
		return nil, fmt.Errorf("cassandra: vector dim must be > 0")
	}
	if len(v) != dim {
		return nil, fmt.Errorf("cassandra: vector length %d does not match declared dim %d", len(v), dim)
	}
	buf := make([]byte, 4*dim)
	for i, x := range v {
		binary.BigEndian.PutUint32(buf[i*4:], math.Float32bits(x))
	}
	return buf, nil
}

// UnmarshalVectorFloat32 decodes a Cassandra 5.0 wire-format vector blob.
//
// @ai:generated by=claude-sonnet-4-6 date=2026-04-29
// @ai:purpose 把 SELECT 拿到的 raw []byte 還原成 []float32（同樣繞過 driver 型別協商）
// @ai:input data=server 回傳的 4N bytes；dim=期望維度
// @ai:output []float32，長度=dim；長度不符或 nil 則 error
// @ai:sideeffect none
func UnmarshalVectorFloat32(data []byte, dim int) ([]float32, error) {
	if dim <= 0 {
		return nil, fmt.Errorf("cassandra: vector dim must be > 0")
	}
	if len(data) != 4*dim {
		return nil, fmt.Errorf("cassandra: vector blob length %d does not match expected %d (dim=%d)", len(data), 4*dim, dim)
	}
	out := make([]float32, dim)
	for i := 0; i < dim; i++ {
		out[i] = math.Float32frombits(binary.BigEndian.Uint32(data[i*4:]))
	}
	return out, nil
}
