package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/maoxiaoyue/hypgo/pkg/airules"
	"github.com/maoxiaoyue/hypgo/pkg/manifest"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var aiRulesCmd = &cobra.Command{
	Use:   "ai-rules",
	Short: "Generate AI tool configuration files",
	Long: `Generate configuration files for AI coding tools so they understand
HypGo conventions and can collaborate more efficiently.

<<<<<<< dev_20260328
Supported tools:
  agents    AGENTS.md                         Codex, Cursor, Aider, OpenHands
  gemini    GEMINI.md                         Google Gemini CLI / AI Studio
  copilot   .github/copilot-instructions.md   GitHub Copilot
  cursor    .cursor/rules/hypgo.mdc           Cursor (scoped rules)
  windsurf  .windsurf/rules/hypgo.md          Windsurf

Files with the auto-generated marker are overwritten on re-run.
Manually created files (without the marker) are never overwritten.

Examples:
  hyp ai-rules
  hyp ai-rules --only agents,gemini
  hyp ai-rules --dry-run`,
=======
When a developer opens your project with any AI coding tool, that tool
reads its configuration file to learn the project's conventions. Without
these files, the AI starts from scratch every time — wasting tokens and
producing code that doesn't follow HypGo patterns.

This command generates all configuration files in one step.

Supported tools:
  agents    AGENTS.md                         Codex CLI, Cursor, Continue.dev,
                                              Aider, OpenHands
  gemini    GEMINI.md                         Google Gemini CLI / AI Studio
  copilot   .github/copilot-instructions.md   GitHub Copilot (VS Code/JetBrains)
  cursor    .cursor/rules/hypgo.mdc           Cursor (with frontmatter)
  windsurf  .windsurf/rules/hypgo.md          Windsurf (max 6,000 chars)

Generated content includes:
  - Framework conventions (Schema-first routes, Typed Errors, etc.)
  - Build & test commands
  - AI collaboration tips (read .hyp/context.yaml first, use hyp impact, etc.)
  - Current routes table (if .hyp/context.yaml exists)

Recommended workflow:
  hyp context -o .hyp/context.yaml   Generate manifest first
  hyp ai-rules                       Then generate AI config files

Overwrite safety:
  Each generated file starts with "<!-- auto-generated by hyp ai-rules -->".
  On re-run, only files with this marker are overwritten. Manually created
  files (without the marker) are never touched.

Flags:
  --only       Comma-separated list of targets (e.g., agents,gemini,copilot)
  --dir        Project root directory (default: current directory)
  --dry-run    Preview output without writing files

Examples:
  hyp ai-rules                          Generate all config files
  hyp ai-rules --only agents,gemini     Only AGENTS.md and GEMINI.md
  hyp ai-rules --dry-run                Preview without writing
  hyp ai-rules --dir ./myproject        Specify project root`,
>>>>>>> main
	RunE: runAIRules,
}

func init() {
<<<<<<< dev_20260328
	rootCmd.AddCommand(aiRulesCmd)
=======
>>>>>>> main
	aiRulesCmd.Flags().String("only", "", "Comma-separated list of targets (e.g., agents,gemini,copilot)")
	aiRulesCmd.Flags().String("dir", ".", "Project root directory")
	aiRulesCmd.Flags().Bool("dry-run", false, "Preview output without writing files")
}

func runAIRules(cmd *cobra.Command, args []string) error {
	only, _ := cmd.Flags().GetString("only")
	dir, _ := cmd.Flags().GetString("dir")
	dryRun, _ := cmd.Flags().GetBool("dry-run")

<<<<<<< dev_20260328
	m := loadManifestIfExists(dir)

=======
	// 嘗試讀取 manifest
	m := loadManifestIfExists(dir)

	// 篩選目標
>>>>>>> main
	targets := airules.FilterTargets(airules.AllTargets(), only)
	if len(targets) == 0 {
		return fmt.Errorf("no matching targets found for: %s", only)
	}

<<<<<<< dev_20260328
=======
	// 生成
>>>>>>> main
	results, err := airules.GenerateAll(dir, targets, m, dryRun)
	if err != nil {
		return err
	}

<<<<<<< dev_20260328
=======
	// 輸出結果
>>>>>>> main
	for _, r := range results {
		rel, _ := filepath.Rel(dir, r.Path)
		if rel == "" {
			rel = r.Path
		}
<<<<<<< dev_20260328
=======

>>>>>>> main
		switch r.Status {
		case airules.StatusCreated:
			fmt.Printf("  + %s\n", rel)
		case airules.StatusSkipped:
			fmt.Printf("  ~ %s (skipped: %s)\n", rel, r.Message)
		case airules.StatusDryRun:
			fmt.Printf("  [dry-run] %s\n", rel)
			fmt.Println(r.Content)
			fmt.Println("---")
		case airules.StatusError:
			fmt.Fprintf(os.Stderr, "  ! %s: %s\n", rel, r.Message)
		}
	}

	if !dryRun {
		created := 0
		for _, r := range results {
			if r.Status == airules.StatusCreated {
				created++
			}
		}
		fmt.Printf("\n%d file(s) generated.\n", created)
	}

	return nil
}

<<<<<<< dev_20260328
=======
// loadManifestIfExists 嘗試載入 .hyp/context.yaml
>>>>>>> main
func loadManifestIfExists(dir string) *manifest.Manifest {
	path := filepath.Join(dir, ".hyp", "context.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var m manifest.Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil
	}
	return &m
}
