// @ai:generated by=claude-opus-4-6 date=2026-02-27
// @ai:modified by=claude-opus-4-7 date=2026-06-15 reason=支援預設集 vs 完整集（--only every）
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/maoxiaoyue/hypgo/pkg/airules"
	"github.com/maoxiaoyue/hypgo/pkg/config"
	"github.com/maoxiaoyue/hypgo/pkg/manifest"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var aiRulesCmd = &cobra.Command{
	Use:   "ai-rules",
	Short: "Generate AI tool configuration files",
	Long: `Generate configuration files for AI coding tools so they understand
HypGo conventions and can collaborate more efficiently.

Default set ("all" mode — used when --only is empty or "all"):
  chatgpt    CHATGPT.md                        ChatGPT
  claude     CLAUDE.md                         Claude Code / Claude API
  trae       .trae/rules/project_rules.md      Trae
  tongyi     .lingma/rules/project_rules.md    通義靈碼 (Tongyi Lingma)
  deepseek   DEEPSEEK.md                       DeepSeek
  cursor     .cursor/rules/hypgo.mdc           Cursor (scoped rules)
  gemini     GEMINI.md                         Google Gemini CLI / AI Studio

Extended set (generated only when explicitly named, or with --only every):
  agents     AGENTS.md                         OpenCode, Codex, Aider, Zed
  copilot    .github/copilot-instructions.md   GitHub Copilot
  windsurf   .windsurf/rules/hypgo.md          Windsurf
  cline      .clinerules/hypgo.md              Cline
  continue   .continue/rules/hypgo.md          Continue.dev
  aider      CONVENTIONS.md                    Aider (--read CONVENTIONS.md)
  roo        .roo/rules/hypgo.md               Roo Code
  codebuddy  .codebuddy/rules/hypgo.md         CodeBuddy

Files with the auto-generated marker are overwritten on re-run.
Manually created files (without the marker) are never overwritten.

Examples:
  hyp ai-rules                              # 7 default targets
  hyp ai-rules --only all                   # same as default
  hyp ai-rules --only every                 # every supported target (15)
  hyp ai-rules --only agents,copilot        # only the listed targets
  hyp ai-rules --dry-run`,
	RunE: runAIRules,
}

var aiRulesCleanCmd = &cobra.Command{
	Use:   "clean",
	Short: "Remove auto-generated AI tool configuration files",
	Long: `Remove configuration files previously generated by 'hyp ai-rules'.

Only files containing the auto-generated marker are removed —
manually edited files (without the marker) are always preserved.

Parent directories are removed if they become empty
(e.g. .cursor/rules/ → .cursor/), bounded by --dir.

By default, every known target path is scanned (safer for cleanup —
files without the marker are simply skipped).

Examples:
  hyp ai-rules clean                          # scan all 15 known targets
  hyp ai-rules clean --only chatgpt,claude    # only the listed targets
  hyp ai-rules clean --dry-run`,
	RunE: runAIRulesClean,
}

func init() {
	rootCmd.AddCommand(aiRulesCmd)
	aiRulesCmd.Flags().String("only", "", "Targets: '' or 'all' = default 7; 'every' = all 15; or comma-separated names")
	aiRulesCmd.Flags().String("dir", ".", "Project root directory")
	aiRulesCmd.Flags().Bool("dry-run", false, "Preview output without writing files")

	aiRulesCmd.AddCommand(aiRulesCleanCmd)
	aiRulesCleanCmd.Flags().String("only", "", "Targets: '' or 'all' = scan all 15; or comma-separated names")
	aiRulesCleanCmd.Flags().String("dir", ".", "Project root directory")
	aiRulesCleanCmd.Flags().Bool("dry-run", false, "Preview which files would be removed without deleting")
}

func runAIRules(cmd *cobra.Command, args []string) error {
	only, _ := cmd.Flags().GetString("only")
	dir, _ := cmd.Flags().GetString("dir")
	dryRun, _ := cmd.Flags().GetBool("dry-run")

	m := loadManifestIfExists(dir)

	targets := airules.ResolveTargets(only)
	if len(targets) == 0 {
		return fmt.Errorf("no matching targets found for: %s", only)
	}

	opts := airules.Options{
		DiffLogEnabled: IsDiffLogEnabled(),
		Comment:        loadCommentToggles(dir),
	}
	results, err := airules.GenerateAll(dir, targets, m, opts, dryRun)
	if err != nil {
		return err
	}

	for _, r := range results {
		rel, _ := filepath.Rel(dir, r.Path)
		if rel == "" {
			rel = r.Path
		}
		switch r.Status {
		case airules.StatusCreated:
			fmt.Printf("  + %s\n", rel)
		case airules.StatusSkipped:
			fmt.Printf("  ~ %s (skipped: %s)\n", rel, r.Message)
		case airules.StatusDryRun:
			fmt.Printf("  [dry-run] %s\n", rel)
			fmt.Println(r.Content)
			fmt.Println("---")
		case airules.StatusError:
			fmt.Fprintf(os.Stderr, "  ! %s: %s\n", rel, r.Message)
		}
	}

	if !dryRun {
		created := 0
		for _, r := range results {
			if r.Status == airules.StatusCreated {
				created++
			}
		}
		fmt.Printf("\n%d file(s) generated.\n", created)
	}

	return nil
}

func runAIRulesClean(cmd *cobra.Command, args []string) error {
	only, _ := cmd.Flags().GetString("only")
	dir, _ := cmd.Flags().GetString("dir")
	dryRun, _ := cmd.Flags().GetBool("dry-run")

	targets := airules.ResolveCleanTargets(only)
	if len(targets) == 0 {
		return fmt.Errorf("no matching targets found for: %s", only)
	}

	results, err := airules.CleanAll(dir, targets, dryRun)
	if err != nil {
		return err
	}

	removed, skipped, errored := 0, 0, 0
	for _, r := range results {
		rel, _ := filepath.Rel(dir, r.Path)
		if rel == "" {
			rel = r.Path
		}
		switch r.Status {
		case airules.StatusRemoved:
			fmt.Printf("  - %s\n", rel)
			removed++
		case airules.StatusDryRun:
			fmt.Printf("  [dry-run] would remove %s\n", rel)
		case airules.StatusSkipped:
			// 「not found」太常見（預設掃 15 個路徑），靜默略過避免雜訊
			if r.Message != "not found" {
				fmt.Printf("  ~ %s (kept: %s)\n", rel, r.Message)
			}
			skipped++
		case airules.StatusError:
			fmt.Fprintf(os.Stderr, "  ! %s: %s\n", rel, r.Message)
			errored++
		}
	}

	if dryRun {
		return nil
	}
	fmt.Printf("\n%d file(s) removed", removed)
	if skipped > 0 {
		fmt.Printf(", %d skipped", skipped)
	}
	if errored > 0 {
		fmt.Printf(", %d errored", errored)
	}
	fmt.Println(".")
	return nil
}

// loadCommentToggles 讀取 .hyp/comment.yaml，回傳註釋開關設定。
// 檔案不存在時用預設值（只開普通註釋）；解析失敗時警告並退回預設。
func loadCommentToggles(dir string) airules.CommentToggles {
	path := filepath.Join(dir, ".hyp", "comment.yaml")
	cfg, err := config.LoadCommentConfig(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: failed to load %s: %v — using defaults\n", path, err)
		cfg = config.DefaultCommentConfig()
	}
	return airules.CommentToggles{
		NormalComment: cfg.NormalComment,
		AIComment:     cfg.AIComment,
		ThinkComment:  cfg.ThinkComment,
	}
}

func loadManifestIfExists(dir string) *manifest.Manifest {
	path := filepath.Join(dir, ".hyp", "context.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var m manifest.Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil
	}
	return &m
}
