// @ai:generated by=claude-opus-4-7 date=2026-06-19
// @ai:purpose hyp chkcomment clean — 移除 //@ai 註釋的子命令
package main

import (
	"fmt"
	"os"

	"github.com/maoxiaoyue/hypgo/pkg/annotation"
	"github.com/spf13/cobra"
)

var chkcommentCleanCmd = &cobra.Command{
	Use:   "clean",
	Short: "Remove //@ai annotations from Go source files",
	Long: `Remove //@ai annotation lines from Go source files.

With --file, only that file is cleaned. Without --file, every .go file
under the current working directory (recursively) is cleaned. Common
directories like vendor/, .git/, node_modules/, .hyp/ and testdata/
are skipped.

--level controls which @ai tags to remove:
  1 (default) — remove ALL @ai annotations (doc block + func body)
  2           — remove ONLY @ai:think (func body intent markers)
  3           — remove @ai:think AND @ai:generated (keep @ai:purpose/input/output/sideeffect)

Special rule: if removing @ai:generated leaves a doc comment without a
human author marker (// @<name>), the descriptive text below is also
removed (since it was AI-authored).

Each modified file gets a .bak backup before being rewritten.

Examples:
  hyp chkcomment clean                              # clean every .go file (level 1)
  hyp chkcomment clean -l 2                         # clean only @ai:think
  hyp chkcomment clean -l 3 -f controllers/user.go  # @ai:think + @ai:generated on one file`,
	RunE: runChkCommentClean,
}

func init() {
	chkcommentCleanCmd.Flags().StringP("file", "f", "", "Target Go file (default: recursively clean all .go files under CWD)")
	chkcommentCleanCmd.Flags().IntP("level", "l", 1, "Clean level: 1=all @ai, 2=only @ai:think, 3=@ai:think + @ai:generated")
	chkcommentCmd.AddCommand(chkcommentCleanCmd)
}

func runChkCommentClean(cmd *cobra.Command, args []string) error {
	file, _ := cmd.Flags().GetString("file")
	levelN, _ := cmd.Flags().GetInt("level")

	level, err := annotation.ParseCleanLevel(levelN)
	if err != nil {
		return err
	}

	if file != "" {
		report, err := annotation.CleanFile(file, level)
		if err != nil {
			return err
		}
		if !report.Modified {
			fmt.Printf("No @ai annotations found in %s (nothing to remove).\n", file)
			return nil
		}
		fmt.Printf("Cleaned %s: removed %d line(s) (backup: %s)\n",
			report.Filename, report.Removed, report.BackupPath)
		return nil
	}

	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}
	fmt.Printf("Cleaning .go files under %s (level=%d)\n\n", cwd, levelN)

	reports, err := annotation.CleanDir(cwd, level)
	if err != nil {
		return fmt.Errorf("clean dir: %w", err)
	}

	if len(reports) == 0 {
		fmt.Println("No files needed cleaning.")
		return nil
	}

	fmt.Print(annotation.FormatCleanReports(reports))
	return nil
}
