package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/maoxiaoyue/hypgo/pkg/annotation"
	"github.com/spf13/cobra"
)

var chkcommentCmd = &cobra.Command{
	Use:   "chkcomment [file.go | dir]",
	Short: "Check and add AI_CODING_RULES-compliant comments to Go source files",
	Long: `Scan Go source file(s) for exported blocks (package, type, func, method,
const, var) and check whether each carries the standardized @ai annotation
block defined in config/AI_CODING_RULES.md (v1.0).

Required @ai tags per block kind:
  exported func / method : generated, purpose, input, output, sideeffect
  exported type/const/var: generated
  package                : generated, purpose

Annotation types recognized:
  // @ai:generated by=<model> date=<YYYY-MM-DD>
  // @ai:purpose <why this block exists>
  // @ai:input <param semantics, not types>
  // @ai:output <return semantics + status codes>
  // @ai:sideeffect <DB/IO/network or "none">
  // @ai:modified by=<model> date=<YYYY-MM-DD> reason=<...>
  // @ai:constraint / @ai:deprecated / @ai:security / @ai:impact / @ai:owner

Output categories:
  [PASS] — block has all required @ai tags
  [WARN] — block has a doc comment but missing one or more required @ai tags
  [FAIL] — block has no doc comment at all

Flags:
  --fix    Automatically add / append suggested comments (creates .bak backup)
  -r       Recursively scan directories (skips vendor/, .git/)

Safety:
  - Pure AST analysis — never executes your code
  - Only accepts .go files, rejects symlinks
  - --fix always creates a backup before modifying

Examples:
  hyp chkcomment controllers/user.go             Check single file
  hyp chkcomment --fix models/order.go            Auto-patch single file
  hyp chkcomment -r pkg/                          Recursively check a dir
  hyp chkcomment -r --fix app/                    Recursively auto-patch`,
	Args: cobra.ExactArgs(1),
	RunE: runChkComment,
}

func init() {
	chkcommentCmd.Flags().Bool("fix", false, "Automatically add/append suggested comments (creates .bak backup)")
	chkcommentCmd.Flags().BoolP("recursive", "r", false, "Recursively scan directories")
}

func runChkComment(cmd *cobra.Command, args []string) error {
	target := args[0]
	fix, _ := cmd.Flags().GetBool("fix")
	recursive, _ := cmd.Flags().GetBool("recursive")

	info, err := os.Stat(target)
	if err != nil {
		return fmt.Errorf("stat %s: %w", target, err)
	}

	var files []string
	if info.IsDir() {
		if !recursive {
			return fmt.Errorf("%s is a directory — use -r for recursive scan", target)
		}
		files, err = collectGoFiles(target)
		if err != nil {
			return err
		}
	} else {
		files = []string{target}
	}

	if len(files) == 0 {
		fmt.Fprintln(os.Stdout, "No .go files found.")
		return nil
	}

	totalBlocks, totalPassed, totalFiles, fixedFiles := 0, 0, 0, 0

	for _, f := range files {
		report, err := annotation.CheckFile(f)
		if err != nil {
			fmt.Fprintf(os.Stderr, "skip %s: %v\n", f, err)
			continue
		}
		totalFiles++
		totalBlocks += report.Total
		totalPassed += report.Passed

		fmt.Print(annotation.FormatReport(report))

		if fix && report.Passed < report.Total {
			if err := annotation.FixFile(f, report.Results); err != nil {
				fmt.Fprintf(os.Stderr, "fix %s: %v\n", f, err)
				continue
			}
			fmt.Fprintf(os.Stdout, "Fixed: %s (backup: %s.bak)\n\n", f, f)
			fixedFiles++
		}
	}

	if len(files) > 1 {
		fmt.Fprintf(os.Stdout, "\n==== Overall ====\n")
		fmt.Fprintf(os.Stdout, "Files scanned : %d\n", totalFiles)
		fmt.Fprintf(os.Stdout, "Blocks total  : %d\n", totalBlocks)
		fmt.Fprintf(os.Stdout, "Blocks passed : %d\n", totalPassed)
		if fix {
			fmt.Fprintf(os.Stdout, "Files patched : %d\n", fixedFiles)
		}
	}

	return nil
}

// collectGoFiles 遞迴蒐集目錄下所有 .go 檔（排除 vendor/.git/node_modules/_test.go 可選）。
func collectGoFiles(root string) ([]string, error) {
	var files []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			base := filepath.Base(path)
			if base == "vendor" || base == ".git" || base == "node_modules" || base == ".hyp" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		// 跳過測試檔（可選；先納入以確保 AI 產生的測試也被檢查）
		files = append(files, path)
		return nil
	})
	return files, err
}
