package main

import (
	"fmt"
	"os"

	"github.com/maoxiaoyue/hypgo/pkg/manifest"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var lintCmd = &cobra.Command{
	Use:   "lint",
	Short: "Check Schema completeness from the project manifest",
	Long: `Check Schema completeness using the lint section of the project manifest.

The Schema Lint is produced by the server's AutoSync on Server.Start()
(written to .hyp/context.yaml). This command reads that manifest and reports
declaration-level gaps, returning a non-zero exit code when warnings exist —
ideal as a CI gate.

What it reports (per route):
  no_schema        Route registered without r.Schema(...)
  missing_input    POST/PUT/PATCH with a Schema but no Input declared
  missing_output   Non-DELETE with a Schema but no Output declared
  missing_summary  Schema present but Summary empty (info level)

Exit codes:
  0   no actionable warnings
  1   one or more warnings (info-level missing_summary only fails with --strict)

Note: this command lints the LAST manifest produced by the running server.
Start the app once (AutoSync writes .hyp/context.yaml) before linting in CI.

Flags:
  -f, --file     Manifest file to lint (default: .hyp/context.yaml)
  --strict       Also fail on info-level findings (missing_summary)
  --quiet        Print only the coverage summary line

Examples:
  hyp lint                          Lint .hyp/context.yaml
  hyp lint -f .hyp/manifest.json    Lint a specific manifest (yaml or json)
  hyp lint --strict                 Fail on any finding, including missing_summary
  hyp lint --quiet                  Print only "Schema coverage: 8/13 (5 warning(s))"`,
	RunE:          runLint,
	SilenceUsage:  true,
	SilenceErrors: false,
}

func init() {
	lintCmd.Flags().StringP("file", "f", ".hyp/context.yaml", "Manifest file to lint")
	lintCmd.Flags().Bool("strict", false, "Also fail on info-level findings (missing_summary)")
	lintCmd.Flags().Bool("quiet", false, "Print only the coverage summary line")
}

func runLint(cmd *cobra.Command, args []string) error {
	file, _ := cmd.Flags().GetString("file")
	strict, _ := cmd.Flags().GetBool("strict")
	quiet, _ := cmd.Flags().GetBool("quiet")

	data, err := os.ReadFile(file)
	if err != nil {
		return fmt.Errorf("cannot read manifest %q: %w\n  hint: start the server once so AutoSync writes %s, or run `hyp context -o %s`", file, err, file, file)
	}

	// yaml.Unmarshal 同時可解析 JSON（YAML 為 JSON 超集）
	var m manifest.Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return fmt.Errorf("invalid manifest %q: %w", file, err)
	}

	if m.Lint == nil {
		fmt.Println("No lint section in manifest (generated by an older version). Nothing to check.")
		return nil
	}

	if quiet {
		fmt.Printf("Schema coverage: %s (%d warning(s))\n", m.Lint.Coverage, len(m.Lint.Warnings))
	} else {
		fmt.Println(manifest.FormatLint(m.Lint))
	}

	// gate：missing_summary 為 info 級，只有 --strict 才視為失敗
	hard := 0
	for _, w := range m.Lint.Warnings {
		if w.Kind != "missing_summary" {
			hard++
		}
	}
	if strict && len(m.Lint.Warnings) > 0 {
		return fmt.Errorf("schema lint failed: %d finding(s) (strict)", len(m.Lint.Warnings))
	}
	if hard > 0 {
		return fmt.Errorf("schema lint failed: %d warning(s)", hard)
	}
	return nil
}
