package main

import (
	"fmt"
	"os"

	"github.com/maoxiaoyue/hypgo/pkg/lintdeep"
	"github.com/maoxiaoyue/hypgo/pkg/manifest"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var lintCmd = &cobra.Command{
	Use:   "lint [packages]",
	Short: "Check Schema completeness (manifest) and Schema↔handler alignment (--deep)",
	Long: `Check Schema completeness using the lint section of the project manifest,
and optionally run a static (compile-time) Schema↔handler alignment check.

SHALLOW (default) — reads the manifest produced by the server's AutoSync on
Server.Start() (.hyp/context.yaml) and reports declaration-level gaps:
  no_schema        Route registered without r.Schema(...)
  missing_input    POST/PUT/PATCH with a Schema but no Input declared
  missing_output   Non-DELETE with a Schema but no Output declared
  missing_summary  Schema present but Summary empty (info level)

DEEP (--deep) — statically analyzes Go source (go/types), no running server or
traffic required. For every r.Schema(schema.Route{...}).Handle(h) it checks the
handler actually binds the declared Input via c.BindInput:
  deep:input_mismatch  handler binds a struct different from the declared Input
  deep:no_bindinput    writable handler never calls c.BindInput at all
This promotes the "bound wrong struct" silent failure — previously only the
runtime BindInput reporter could catch it (and only when a request fired) — into
a build-time CI gate. Handlers that cannot be resolved statically are listed as
skipped (never silently counted as passing).

Exit codes:
  0   no actionable warnings
  1   one or more warnings (info-level missing_summary only fails with --strict;
      any deep finding fails)

Flags:
  -f, --file     Manifest file for the shallow check (default: .hyp/context.yaml)
  --deep         Also run the static source-level Schema↔handler check
  --strict       Also fail on info-level findings (missing_summary) and deep load errors
  --quiet        Print only the shallow coverage summary line

Examples:
  hyp lint                      Shallow check of .hyp/context.yaml
  hyp lint --deep               Shallow + deep (deep scans ./...)
  hyp lint --deep ./pkg/api/... Deep check restricted to a package pattern
  hyp lint --deep --strict      Fail on every finding, including info-level`,
	RunE:          runLint,
	SilenceUsage:  true,
	SilenceErrors: false,
}

func init() {
	lintCmd.Flags().StringP("file", "f", ".hyp/context.yaml", "Manifest file to lint")
	lintCmd.Flags().Bool("deep", false, "Run static (compile-time) Schema↔handler alignment check")
	lintCmd.Flags().Bool("strict", false, "Also fail on info-level findings and deep load errors")
	lintCmd.Flags().Bool("quiet", false, "Print only the coverage summary line")
}

func runLint(cmd *cobra.Command, args []string) error {
	file, _ := cmd.Flags().GetString("file")
	deep, _ := cmd.Flags().GetBool("deep")
	strict, _ := cmd.Flags().GetBool("strict")
	quiet, _ := cmd.Flags().GetBool("quiet")

	hardFailures := 0

	// ── 淺層（manifest）檢查 ──
	data, err := os.ReadFile(file)
	if err != nil {
		if !deep {
			return fmt.Errorf("cannot read manifest %q: %w\n  hint: start the server once so AutoSync writes %s, or run `hyp context -o %s`", file, err, file, file)
		}
		fmt.Printf("（略過 manifest 淺層檢查：無法讀取 %s；改以 --deep 直接分析原始碼）\n", file)
	} else {
		n, perr := runShallow(data, file, strict, quiet)
		if perr != nil {
			return perr
		}
		hardFailures += n
	}

	// ── 深層（原始碼）檢查 ──
	if deep {
		rep, derr := lintdeep.Analyze(".", args...)
		if derr != nil {
			return fmt.Errorf("deep analyze failed: %w", derr)
		}
		fmt.Println()
		fmt.Println(lintdeep.Format(rep))
		hardFailures += len(rep.Findings)
		if strict {
			hardFailures += len(rep.LoadErrors)
		}
	}

	if hardFailures > 0 {
		return fmt.Errorf("schema lint failed: %d issue(s)", hardFailures)
	}
	return nil
}

// runShallow 解析 manifest、印出淺層報告，回傳 hard failure 數（missing_summary 僅 --strict 計入）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func runShallow(data []byte, file string, strict, quiet bool) (int, error) {
	// yaml.Unmarshal 同時可解析 JSON（YAML 為 JSON 超集）
	var m manifest.Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return 0, fmt.Errorf("invalid manifest %q: %w", file, err)
	}

	if m.Lint == nil {
		fmt.Println("No lint section in manifest (generated by an older version). Nothing to check.")
		return 0, nil
	}

	if quiet {
		fmt.Printf("Schema coverage: %s (%d warning(s))\n", m.Lint.Coverage, len(m.Lint.Warnings))
	} else {
		fmt.Println(manifest.FormatLint(m.Lint))
	}

	hard := 0
	for _, w := range m.Lint.Warnings {
		if w.Kind != "missing_summary" {
			hard++
		}
	}
	if strict {
		return len(m.Lint.Warnings), nil
	}
	return hard, nil
}
