// @ai:generated by=claude-opus-4-6 date=2026-02-27
package main

// @ai purpose: hyp observe CLI 命令 — 列出或開啟 .hyp/ 目錄下的 Observe HTML 報告
// @ai input: 可選的過濾關鍵字引數（用於顯示說明），--open flag 控制是否自動開啟瀏覽器
// @ai output: 終端列出可用的 observe 報告清單，或開啟最新報告
// @ai sideeffect: 可能啟動系統瀏覽器開啟 file:// URL
// date: 2026-05-23

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

var observeCmd = &cobra.Command{
	Use:   "observe [func-name]",
	Short: "List or open HypGo Observe HTML reports",
	Long: `List and open contract observe reports generated by contract.ObserveAll() or contract.Observe().

Reports are stored in .hyp/observe_*.html and are generated automatically when you
run ObserveAll(t, router) or Observe(t, router, "funcName") in your test files.

Usage in tests:
  // Observe all routes (generates HTML report)
  func TestObserveAll(t *testing.T) {
      contract.ObserveAll(t, setupRouter())
  }

  // Observe routes matching a function name / path / tag
  func TestObserveCreateOrder(t *testing.T) {
      contract.Observe(t, setupRouter(), "createOrderHandler")
  }

  // Auto-open browser after generating report
  func TestObserveWithBrowser(t *testing.T) {
      contract.ObserveAll(t, setupRouter(), contract.ObserveOptions{OpenBrowser: true})
  }

CLI usage:
  hyp observe             # list all available reports
  hyp observe --open      # open the latest report in browser
  hyp observe --open -n 2 # open the 2nd newest report`,
	RunE: runObserveCmd,
}

var (
	observeOpenBrowser bool
	observeNthReport   int
)

func init() {
	observeCmd.Flags().BoolVarP(&observeOpenBrowser, "open", "o", false,
		"Open the latest (or -n th) observe report in the default browser")
	observeCmd.Flags().IntVarP(&observeNthReport, "n", "n", 1,
		"Which report to open (1 = latest, 2 = second newest, ...)")
}

// runObserveCmd 執行 hyp observe 命令：列出或開啟 observe 報告
func runObserveCmd(cmd *cobra.Command, args []string) error {
	reports, err := findObserveReports()
	if err != nil {
		return fmt.Errorf("掃描 .hyp/ 目錄失敗: %w", err)
	}

	if len(reports) == 0 {
		fmt.Println("📋 尚無 observe 報告。")
		fmt.Println()
		fmt.Println("請在測試中加入：")
		fmt.Println(`  contract.ObserveAll(t, setupRouter())`)
		fmt.Println(`  // 或`)
		fmt.Println(`  contract.Observe(t, setupRouter(), "yourFuncName")`)
		fmt.Println()
		fmt.Println("然後執行：")
		fmt.Println("  go test ./... -run TestObserve -v")
		return nil
	}

	// 列出所有報告
	fmt.Printf("📊 找到 %d 個 observe 報告：\n\n", len(reports))
	for i, r := range reports {
		marker := "  "
		if i == 0 {
			marker = "▶ "
		}
		size := reportFileSizeStr(r)
		fmt.Printf("  %s[%d] %s  %s\n", marker, i+1, filepath.Base(r), size)
	}
	fmt.Println()

	if len(args) > 0 {
		filter := strings.Join(args, " ")
		fmt.Printf("💡 提示：在測試中使用以下命令觀察 %q 相關路由：\n", filter)
		fmt.Printf("   contract.Observe(t, setupRouter(), %q)\n\n", filter)
	}

	// 開啟瀏覽器
	if observeOpenBrowser {
		n := observeNthReport
		if n < 1 || n > len(reports) {
			return fmt.Errorf("報告編號 %d 超出範圍（共 %d 個）", n, len(reports))
		}
		target := reports[n-1]
		abs, err := filepath.Abs(target)
		if err != nil {
			abs = target
		}
		url := "file://" + filepath.ToSlash(abs)
		fmt.Printf("🌐 開啟報告：%s\n", filepath.Base(target))
		return openBrowserURL(url)
	}

	fmt.Println("💡 使用 `hyp observe --open` 在瀏覽器中開啟最新報告")
	return nil
}

// findObserveReports 掃描 .hyp/ 目錄下的所有 observe_*.html，依時間倒序排列
func findObserveReports() ([]string, error) {
	pattern := filepath.Join(".hyp", "observe_*.html")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return nil, err
	}
	if len(matches) == 0 {
		return nil, nil
	}

	// 依修改時間倒序（最新的在前）
	type entry struct {
		path    string
		modTime int64
	}
	entries := make([]entry, 0, len(matches))
	for _, m := range matches {
		info, err := os.Stat(m)
		if err != nil {
			continue
		}
		entries = append(entries, entry{path: m, modTime: info.ModTime().UnixNano()})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].modTime > entries[j].modTime
	})

	result := make([]string, len(entries))
	for i, e := range entries {
		result[i] = e.path
	}
	return result, nil
}

// reportFileSizeStr 回傳格式化的檔案大小字串
func reportFileSizeStr(path string) string {
	info, err := os.Stat(path)
	if err != nil {
		return ""
	}
	size := info.Size()
	switch {
	case size >= 1<<20:
		return fmt.Sprintf("%.1f MB", float64(size)/(1<<20))
	case size >= 1<<10:
		return fmt.Sprintf("%.1f KB", float64(size)/(1<<10))
	default:
		return fmt.Sprintf("%d B", size)
	}
}

// openBrowserURL 在作業系統的預設瀏覽器開啟 URL
func openBrowserURL(url string) error {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", url)
	case "linux":
		cmd = exec.Command("xdg-open", url)
	case "windows":
		cmd = exec.Command("cmd", "/c", "start", "", url)
	default:
		fmt.Printf("請手動開啟：%s\n", url)
		return nil
	}
	return cmd.Start()
}
