// @ai:generated by=claude-opus-4-7 date=2026-06-21
// @ai:purpose 共用的 scaffold 後設定：自動把 generated 專案的 hypgo 依賴升到 @latest
package main

import (
	"fmt"
	"os"
	"os/exec"
)

// postScaffoldUpgrade 在 scaffold 完成後嘗試把專案的 hypgo 依賴升到 @latest
// 並執行 go mod tidy。執行失敗（沒有 go / 沒網路 / 私有 module）時印警告但不中斷
// 整個 hyp new 流程；產生的 go.mod 已有 v0.8.11 作為後備版本。
func postScaffoldUpgrade(projectDir string) {
	// 確認 go 在 PATH 中
	if _, err := exec.LookPath("go"); err != nil {
		fmt.Fprintf(os.Stderr, "\nWarning: 'go' not found in PATH; skipping `go get @latest`.\n")
		fmt.Fprintf(os.Stderr, "  Manually run: cd %s && go get github.com/maoxiaoyue/hypgo@latest && go mod tidy\n", projectDir)
		return
	}

	fmt.Printf("\n📦 Fetching latest hypgo (@latest)...\n")

	get := exec.Command("go", "get", "github.com/maoxiaoyue/hypgo@latest")
	get.Dir = projectDir
	get.Stdout = os.Stdout
	get.Stderr = os.Stderr
	if err := get.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: `go get @latest` failed: %v\n", err)
		fmt.Fprintf(os.Stderr, "  Project still uses the bundled v0.8.11 baseline (see go.mod).\n")
		fmt.Fprintf(os.Stderr, "  Retry manually: cd %s && go get github.com/maoxiaoyue/hypgo@latest\n", projectDir)
		return
	}

	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = projectDir
	tidy.Stdout = os.Stdout
	tidy.Stderr = os.Stderr
	if err := tidy.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: `go mod tidy` failed: %v\n", err)
		return
	}

	fmt.Printf("✓ hypgo upgraded to latest; go.sum populated.\n")
}
