// @ai:generated by=claude-opus-4-7 date=2026-06-21
// @ai:purpose hyp test 命令：先補上缺少的 *_test.go 骨架，再跑 go test
package main

import (
	"fmt"
	"os"
	"os/exec"

	"github.com/maoxiaoyue/hypgo/pkg/testgen"
	"github.com/spf13/cobra"
)

var testCmd = &cobra.Command{
	Use:                "test [packages] [-- go-test-flags...]",
	Short:              "Generate missing test stubs, then run 'go test'",
	DisableFlagParsing: false,
	Long: `Run go test, but first ensure every exported func/method has a *_test.go
stub via 'hyp testgen'. New stubs call t.Skip(...) so they don't pretend to
pass — you replace them with real assertions over time.

Examples:
  hyp test                        # gen stubs + go test ./...
  hyp test ./app/services         # scoped
  hyp test --no-gen ./...         # skip stub generation; just go test
  hyp test -- -run TestFoo -v     # everything after -- is forwarded to go test

The --no-gen / --include-unexported / --dry-run flags affect the testgen
step. Anything after '--' is forwarded verbatim to 'go test'.`,
	RunE: runTest,
}

func init() {
	testCmd.Flags().Bool("no-gen", false, "Skip the testgen step; run 'go test' directly")
	testCmd.Flags().Bool("include-unexported", false, "(testgen) Also stub for unexported funcs")
	testCmd.Flags().Bool("dry-run", false, "(testgen) Show what would be generated without writing")
	rootCmd.AddCommand(testCmd)
}

func runTest(cmd *cobra.Command, args []string) error {
	noGen, _ := cmd.Flags().GetBool("no-gen")
	includeUnexported, _ := cmd.Flags().GetBool("include-unexported")
	dryRun, _ := cmd.Flags().GetBool("dry-run")

	// 區分「目標 packages」與「-- 之後的 go test 旗標」
	// Cobra 把 `--` 移除，但保留 ArgsLenAtDash() 指出原本 `--` 的位置
	var pkgs, goTestArgs []string
	if dashIdx := cmd.ArgsLenAtDash(); dashIdx >= 0 {
		pkgs = args[:dashIdx]
		goTestArgs = args[dashIdx:]
	} else {
		pkgs = args
	}

	// 1) testgen 階段：對目標目錄補上 stub（預設整個專案）
	if !noGen {
		opts := testgen.DefaultOptions()
		opts.IncludeUnexported = includeUnexported
		opts.DryRun = dryRun

		target := "."
		// 如果使用者指定了單一目錄/package（不是 ./... 之類），用它當 scope
		if len(pkgs) == 1 && !isWildcardPackage(pkgs[0]) {
			target = pkgs[0]
		}
		fmt.Printf("== hyp testgen (scope=%s) ==\n", target)
		reports, err := testgen.GenerateForDir(target, opts)
		if err != nil {
			return fmt.Errorf("testgen: %w", err)
		}
		if len(reports) == 0 {
			fmt.Println("No missing tests.")
			fmt.Println()
		} else {
			fmt.Print(testgen.FormatReports(reports))
			fmt.Println()
		}
		if dryRun {
			fmt.Println("(dry-run) skipping 'go test'.")
			return nil
		}
	}

	// 2) 呼叫 go test
	if _, err := exec.LookPath("go"); err != nil {
		return fmt.Errorf("'go' not found in PATH; cannot run go test")
	}
	if len(pkgs) == 0 {
		pkgs = []string{"./..."}
	}
	cmdArgs := append([]string{"test"}, pkgs...)
	cmdArgs = append(cmdArgs, goTestArgs...)

	fmt.Printf("== go %s ==\n", joinArgs(cmdArgs))
	gt := exec.Command("go", cmdArgs...)
	gt.Stdout = os.Stdout
	gt.Stderr = os.Stderr
	gt.Stdin = os.Stdin
	if err := gt.Run(); err != nil {
		// go test 失敗時 exit code 已透過 cmd 傳遞；額外 wrap 一層讓 hyp 也回非零
		return fmt.Errorf("go test failed: %w", err)
	}
	return nil
}

// isWildcardPackage 判斷是否是 ./... 之類的萬用字元 package spec
func isWildcardPackage(s string) bool {
	return len(s) >= 3 && s[len(s)-3:] == "..."
}

// joinArgs 把 args 轉成可讀字串（用於 log）
func joinArgs(args []string) string {
	out := ""
	for i, a := range args {
		if i > 0 {
			out += " "
		}
		out += a
	}
	return out
}
