// @ai:generated by=claude-opus-4-7 date=2026-06-21
// @ai:purpose hyp testgen 命令：為缺少測試的 exported func 產生 *_test.go 骨架
package main

import (
	"fmt"
	"os"

	"github.com/maoxiaoyue/hypgo/pkg/testgen"
	"github.com/spf13/cobra"
)

var testgenCmd = &cobra.Command{
	Use:   "testgen [target]",
	Short: "Generate missing *_test.go stubs for exported funcs/methods",
	Long: `Scan Go source files for exported funcs/methods without a corresponding
Test* function and generate stub *_test.go files.

Each generated stub calls t.Skip("auto-generated stub; replace with real
assertions") so CI sees them as skipped rather than passing — you can find
and replace them with real tests.

Behavior:
  - Default scope is the current working directory (recursive)
  - Provide a path argument to scope to a single file or subdirectory
  - vendor/, .git/, node_modules/, .hyp/, testdata/ are skipped
  - Existing Test* names are preserved (never overwritten)
  - Funcs marked //hyp:notest are skipped entirely

Examples:
  hyp testgen                                 # whole project
  hyp testgen --file app/services/user.go     # one file
  hyp testgen ./app/services                  # one directory
  hyp testgen --include-unexported            # also stub for lower-case funcs
  hyp testgen --dry-run                       # preview without writing

Integration with go test:
  Option A — use the wrapper: hyp test ./...
  Option B — add //go:generate hyp testgen $GOFILE to a source file,
            then run: go generate ./... && go test ./...
`,
	RunE: runTestgen,
}

func init() {
	testgenCmd.Flags().String("file", "", "Target single .go file (default: recursive scan from target dir)")
	testgenCmd.Flags().Bool("include-unexported", false, "Also generate stubs for unexported funcs/methods")
	testgenCmd.Flags().Bool("dry-run", false, "Show what would be generated without writing files")
	testgenCmd.Flags().String("stub-message", "", "Custom t.Skip message (default: 'auto-generated stub; replace with real assertions')")
	rootCmd.AddCommand(testgenCmd)
}

func runTestgen(cmd *cobra.Command, args []string) error {
	file, _ := cmd.Flags().GetString("file")
	includeUnexported, _ := cmd.Flags().GetBool("include-unexported")
	dryRun, _ := cmd.Flags().GetBool("dry-run")
	stubMsg, _ := cmd.Flags().GetString("stub-message")

	opts := testgen.DefaultOptions()
	opts.IncludeUnexported = includeUnexported
	opts.DryRun = dryRun
	if stubMsg != "" {
		opts.StubMessage = stubMsg
	}

	// 單一檔案
	if file != "" {
		rep, err := testgen.GenerateForFile(file, opts)
		if err != nil {
			return err
		}
		printSingleReport(rep, dryRun)
		return nil
	}

	// 目錄遞迴
	target := "."
	if len(args) > 0 {
		target = args[0]
	}
	if dryRun {
		fmt.Printf("[dry-run] Scanning %s for missing test stubs...\n\n", target)
	} else {
		fmt.Printf("Scanning %s for missing test stubs...\n\n", target)
	}
	reports, err := testgen.GenerateForDir(target, opts)
	if err != nil {
		return fmt.Errorf("scan failed: %w", err)
	}
	if len(reports) == 0 {
		fmt.Println("No missing tests found.")
		return nil
	}
	fmt.Print(testgen.FormatReports(reports))
	return nil
}

func printSingleReport(rep *testgen.Report, dryRun bool) {
	if rep == nil {
		return
	}
	prefix := ""
	if dryRun {
		prefix = "[dry-run] "
	}
	if len(rep.Added) == 0 && len(rep.Skipped) == 0 && len(rep.NoTestNeed) == 0 {
		fmt.Fprintf(os.Stdout, "%sNo eligible funcs in %s\n", prefix, rep.SourceFile)
		return
	}
	mark := "~"
	if rep.Created {
		mark = "+"
	}
	fmt.Fprintf(os.Stdout, "%s %s%s → %s\n", mark, prefix, rep.SourceFile, rep.TestFile)
	if len(rep.Added) > 0 {
		fmt.Fprintf(os.Stdout, "    added:  %v\n", rep.Added)
	}
	if len(rep.Skipped) > 0 {
		fmt.Fprintf(os.Stdout, "    kept:   %v\n", rep.Skipped)
	}
	if len(rep.NoTestNeed) > 0 {
		fmt.Fprintf(os.Stdout, "    notest: %v\n", rep.NoTestNeed)
	}
}
