package annotation

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// --- ParseAnnotations ---

func TestParseAnnotationsBasic(t *testing.T) {
	input := `// Create 建立使用者
// @ai:constraint max_items=100
// @ai:security requires_auth`

	anns := ParseAnnotations(input)
	if len(anns) != 2 {
		t.Fatalf("got %d annotations, want 2", len(anns))
	}
	if anns[0].Type != Constraint || anns[0].Value != "max_items=100" {
		t.Errorf("anns[0] = %+v, want constraint max_items=100", anns[0])
	}
	if anns[1].Type != Security || anns[1].Value != "requires_auth" {
		t.Errorf("anns[1] = %+v, want security requires_auth", anns[1])
	}
}

func TestParseAnnotationsAllTypes(t *testing.T) {
	input := `// @ai:constraint limit=50
// @ai:deprecated use V2 instead
// @ai:security requires_admin
// @ai:impact routes=/api/users
// @ai:owner team=backend
// @ai:generated by=claude-sonnet-4-6 date=2026-04-23
// @ai:purpose 提供註冊 API
// @ai:input JSON body
// @ai:output 201 + UserResponse
// @ai:sideeffect DB insert
// @ai:modified by=gpt-5 date=2026-04-24 reason=add validation`

	anns := ParseAnnotations(input)
	if len(anns) != 11 {
		t.Fatalf("got %d annotations, want 11", len(anns))
	}

	expected := []AnnotationType{Constraint, Deprecated, Security, Impact, Owner, Generated, Purpose, Input, Output, SideEffect, Modified}
	for i, want := range expected {
		if anns[i].Type != want {
			t.Errorf("anns[%d].Type = %q, want %q", i, anns[i].Type, want)
		}
	}
}

func TestParseAnnotationsNoAnnotations(t *testing.T) {
	input := `// This is a normal comment
// Another comment without @ai prefix`

	anns := ParseAnnotations(input)
	if len(anns) != 0 {
		t.Errorf("got %d annotations, want 0", len(anns))
	}
}

func TestParseAnnotationsEmpty(t *testing.T) {
	anns := ParseAnnotations("")
	if len(anns) != 0 {
		t.Errorf("got %d annotations, want 0", len(anns))
	}
}

func TestParseAnnotationsUnknownType(t *testing.T) {
	input := `// @ai:unknown something`
	anns := ParseAnnotations(input)
	if len(anns) != 0 {
		t.Errorf("unknown type should be ignored, got %d", len(anns))
	}
}

func TestParseAnnotationsNoValue(t *testing.T) {
	input := `// @ai:deprecated`
	anns := ParseAnnotations(input)
	if len(anns) != 1 {
		t.Fatalf("got %d, want 1", len(anns))
	}
	if anns[0].Value != "" {
		t.Errorf("Value = %q, want empty", anns[0].Value)
	}
}

// --- FormatAnnotation ---

func TestFormatAnnotation(t *testing.T) {
	tests := []struct {
		input Annotation
		want  string
	}{
		{Annotation{Type: Constraint, Value: "max=100"}, "// @ai:constraint max=100"},
		{Annotation{Type: Deprecated, Value: "use V2"}, "// @ai:deprecated use V2"},
		{Annotation{Type: Security, Value: ""}, "// @ai:security"},
		{Annotation{Type: Generated, Value: "by=claude date=2026-04-23"}, "// @ai:generated by=claude date=2026-04-23"},
		{Annotation{Type: SideEffect, Value: "none"}, "// @ai:sideeffect none"},
	}
	for _, tt := range tests {
		got := FormatAnnotation(tt.input)
		if got != tt.want {
			t.Errorf("FormatAnnotation(%+v) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

// --- FormatAnnotation → ParseAnnotations 往返 ---

func TestAnnotationRoundTrip(t *testing.T) {
	original := Annotation{Type: Impact, Value: "routes=/api/users, models=User"}
	formatted := FormatAnnotation(original)
	parsed := ParseAnnotations(formatted)

	if len(parsed) != 1 {
		t.Fatalf("round trip: got %d annotations, want 1", len(parsed))
	}
	if parsed[0].Type != original.Type || parsed[0].Value != original.Value {
		t.Errorf("round trip failed: got %+v, want %+v", parsed[0], original)
	}
}

// --- RequiredAnnotations ---

func TestRequiredAnnotationsExportedFunc(t *testing.T) {
	req := RequiredAnnotations("func", true)
	if len(req) != 5 {
		t.Fatalf("exported func requires 5, got %d", len(req))
	}
	want := []AnnotationType{Generated, Purpose, Input, Output, SideEffect}
	for i, w := range want {
		if req[i] != w {
			t.Errorf("req[%d] = %q, want %q", i, req[i], w)
		}
	}
}

func TestRequiredAnnotationsUnexported(t *testing.T) {
	req := RequiredAnnotations("func", false)
	if len(req) != 1 || req[0] != Generated {
		t.Errorf("unexported func requires only generated, got %v", req)
	}
}

func TestRequiredAnnotationsPackage(t *testing.T) {
	req := RequiredAnnotations("package", true)
	if len(req) != 2 {
		t.Fatalf("package requires 2, got %d", len(req))
	}
}

// --- MissingAnnotations ---

func TestMissingAnnotations(t *testing.T) {
	existing := []Annotation{
		{Type: Generated, Value: "by=x"},
		{Type: Purpose, Value: "y"},
	}
	required := []AnnotationType{Generated, Purpose, Input, Output, SideEffect}
	missing := MissingAnnotations(existing, required)
	if len(missing) != 3 {
		t.Fatalf("missing = %v, want 3 entries", missing)
	}
	if missing[0] != Input || missing[1] != Output || missing[2] != SideEffect {
		t.Errorf("missing order wrong: %v", missing)
	}
}

func TestMissingAnnotationsNone(t *testing.T) {
	existing := []Annotation{
		{Type: Generated}, {Type: Purpose}, {Type: Input}, {Type: Output}, {Type: SideEffect},
	}
	required := []AnnotationType{Generated, Purpose, Input, Output, SideEffect}
	missing := MissingAnnotations(existing, required)
	if len(missing) != 0 {
		t.Errorf("expected no missing, got %v", missing)
	}
}

// --- CheckFile ---

func TestCheckFileFullyCompliant(t *testing.T) {
	content := `// Package testpkg provides test coverage.
//
// @ai:generated by=claude date=2026-04-23
// @ai:purpose test package
package testpkg

// ExportedFunc does something.
//
// @ai:generated by=claude date=2026-04-23
// @ai:purpose 提供測試用
// @ai:input none
// @ai:output error
// @ai:sideeffect none
func ExportedFunc() error { return nil }

func unexportedFunc() {}
`
	tmpFile := writeTempGoFile(t, content)

	report, err := CheckFile(tmpFile)
	if err != nil {
		t.Fatalf("CheckFile failed: %v", err)
	}

	if report.Total != 2 {
		t.Errorf("Total = %d, want 2 (package + ExportedFunc)", report.Total)
	}
	if report.Passed != 2 {
		t.Errorf("Passed = %d, want 2 (all compliant)", report.Passed)
	}
	for _, r := range report.Results {
		if !r.HasRequired {
			t.Errorf("%s should HasRequired=true, missing=%v", r.Name, r.MissingRequired)
		}
	}
}

func TestCheckFileMissingAITags(t *testing.T) {
	// 有 doc 但缺 @ai 欄位
	content := `package testpkg

// ExportedFunc does something.
func ExportedFunc() {}
`
	tmpFile := writeTempGoFile(t, content)

	report, err := CheckFile(tmpFile)
	if err != nil {
		t.Fatalf("CheckFile failed: %v", err)
	}

	var funcResult *CheckResult
	for i, r := range report.Results {
		if strings.Contains(r.Name, "ExportedFunc") {
			funcResult = &report.Results[i]
		}
	}
	if funcResult == nil {
		t.Fatal("ExportedFunc result not found")
	}
	if !funcResult.HasDoc {
		t.Error("ExportedFunc should HasDoc=true")
	}
	if funcResult.HasRequired {
		t.Error("ExportedFunc should HasRequired=false (missing @ai tags)")
	}
	if len(funcResult.MissingRequired) != 5 {
		t.Errorf("should miss 5 @ai tags, got %d: %v", len(funcResult.MissingRequired), funcResult.MissingRequired)
	}
}

func TestCheckFileNoDoc(t *testing.T) {
	content := `package testpkg

func ExportedFunc() {}

type ExportedType struct{}
`
	tmpFile := writeTempGoFile(t, content)

	report, err := CheckFile(tmpFile)
	if err != nil {
		t.Fatalf("CheckFile failed: %v", err)
	}

	// package + ExportedFunc + ExportedType = 3
	if report.Total != 3 {
		t.Errorf("Total = %d, want 3", report.Total)
	}
	if report.Passed != 0 {
		t.Errorf("Passed = %d, want 0 (nothing has @ai)", report.Passed)
	}
}

func TestCheckFileRejectsNonGo(t *testing.T) {
	_, err := CheckFile("test.txt")
	if err == nil {
		t.Error("should reject non-.go files")
	}
}

func TestCheckFileMethod(t *testing.T) {
	content := `package testpkg

// Server represents a test server.
//
// @ai:generated by=claude date=2026-04-23
type Server struct{}

// Start starts the server.
//
// @ai:generated by=claude date=2026-04-23
// @ai:purpose 啟動伺服器
// @ai:input none
// @ai:output error
// @ai:sideeffect 開啟 listening socket
func (s *Server) Start() error { return nil }

func (s *Server) Stop() {}
`
	tmpFile := writeTempGoFile(t, content)

	report, err := CheckFile(tmpFile)
	if err != nil {
		t.Fatalf("CheckFile failed: %v", err)
	}

	var startResult, stopResult *CheckResult
	for i, r := range report.Results {
		if strings.Contains(r.Name, "Start") {
			startResult = &report.Results[i]
		}
		if strings.Contains(r.Name, "Stop") {
			stopResult = &report.Results[i]
		}
	}
	if startResult == nil || stopResult == nil {
		t.Fatal("methods not found")
	}
	if !startResult.HasRequired {
		t.Errorf("Start should be compliant, missing=%v", startResult.MissingRequired)
	}
	if stopResult.HasRequired {
		t.Error("Stop should not be compliant (no @ai tags)")
	}
	if stopResult.Kind != "method" {
		t.Errorf("Stop.Kind = %q, want method", stopResult.Kind)
	}
}

// --- FormatReport ---

func TestFormatReport(t *testing.T) {
	report := &CheckReport{
		Filename: "test.go",
		Total:    3,
		Passed:   1,
		Results: []CheckResult{
			{Name: "package test", Kind: "package", HasDoc: true, HasRequired: true, Line: 1},
			{Name: "func Create", Kind: "func", Exported: true, HasDoc: false, HasRequired: false, Line: 5,
				MissingRequired: []AnnotationType{Generated, Purpose, Input, Output, SideEffect},
				Suggested:       "// Create ...\n//\n// @ai:generated by=unknown date=2026-04-23"},
			{Name: "type User", Kind: "type", Exported: true, HasDoc: true, HasRequired: false, Line: 10,
				MissingRequired: []AnnotationType{Generated},
				Suggested:       "// User ...\n//\n// @ai:generated by=unknown date=2026-04-23"},
		},
	}

	output := FormatReport(report)
	if !strings.Contains(output, "[PASS]") {
		t.Error("should contain [PASS]")
	}
	if !strings.Contains(output, "[FAIL]") {
		t.Error("should contain [FAIL] for missing doc")
	}
	if !strings.Contains(output, "[WARN]") {
		t.Error("should contain [WARN] for missing @ai tags")
	}
	if !strings.Contains(output, "1/3") {
		t.Error("should contain 1/3 summary")
	}
	if !strings.Contains(output, "--fix") {
		t.Error("should suggest --fix")
	}
}

// --- FixFile ---

func TestFixFileNoDoc(t *testing.T) {
	content := `package testpkg

func ExportedFunc() {}
`
	tmpFile := writeTempGoFile(t, content)

	report, err := CheckFile(tmpFile)
	if err != nil {
		t.Fatalf("CheckFile failed: %v", err)
	}

	if err := FixFile(tmpFile, report.Results); err != nil {
		t.Fatalf("FixFile failed: %v", err)
	}

	if _, err := os.Stat(tmpFile + ".bak"); os.IsNotExist(err) {
		t.Error("backup file should be created")
	}

	fixed, _ := os.ReadFile(tmpFile)
	fixedStr := string(fixed)

	if !strings.Contains(fixedStr, "@ai:generated") {
		t.Error("@ai:generated should be added")
	}
	if !strings.Contains(fixedStr, "@ai:purpose") {
		t.Error("@ai:purpose should be added")
	}
	if !strings.Contains(fixedStr, "@ai:sideeffect") {
		t.Error("@ai:sideeffect should be added")
	}
}

func TestFixFilePartialDoc(t *testing.T) {
	// 既有 doc 但缺 @ai tags → 應該 append 在 doc 後面
	content := `package testpkg

// ExportedFunc does something important.
func ExportedFunc() {}
`
	tmpFile := writeTempGoFile(t, content)

	report, err := CheckFile(tmpFile)
	if err != nil {
		t.Fatalf("CheckFile failed: %v", err)
	}

	if err := FixFile(tmpFile, report.Results); err != nil {
		t.Fatalf("FixFile failed: %v", err)
	}

	fixed, _ := os.ReadFile(tmpFile)
	fixedStr := string(fixed)

	// 原有的 "does something important." 必須保留
	if !strings.Contains(fixedStr, "does something important") {
		t.Error("original doc should be preserved")
	}
	// 補上的 @ai 欄位必須存在
	for _, tag := range []string{"@ai:generated", "@ai:purpose", "@ai:input", "@ai:output", "@ai:sideeffect"} {
		if !strings.Contains(fixedStr, tag) {
			t.Errorf("%s should be appended", tag)
		}
	}
}

// --- ValidAnnotationTypes ---

func TestValidAnnotationTypes(t *testing.T) {
	types := ValidAnnotationTypes()
	if len(types) != 11 {
		t.Errorf("got %d types, want 11 (5 legacy + 6 new)", len(types))
	}
}

// --- helpers ---

func writeTempGoFile(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "test.go")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("write temp file: %v", err)
	}
	return path
}
