// Package annotation 提供 HypGo 標準化 Annotation Protocol
// 定義 // @ai: 前綴的結構化標註格式，讓 AI 從註解理解業務約束、安全需求與依賴關係
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 提供 AI 協作所需的結構化標註解析與驗證能力
package annotation

import (
	"strings"
)

// AnnotationType 標註類型
type AnnotationType string

const (
	// Constraint 業務約束（如最大值、格式限制）
	Constraint AnnotationType = "constraint"
	// Deprecated 標記已棄用，說明替代方案
	Deprecated AnnotationType = "deprecated"
	// Security 安全相關標註（如需要認證、權限）
	Security AnnotationType = "security"
	// Impact 影響範圍標註（關聯的路由、模型）
	Impact AnnotationType = "impact"
	// Owner 負責人/團隊標註
	Owner AnnotationType = "owner"
	// Generated AI 生成紀錄（by + date）— AI_CODING_RULES v1.0 強制
	Generated AnnotationType = "generated"
	// Purpose 函式存在的理由（為什麼，非做什麼）— AI_CODING_RULES v1.0 強制
	Purpose AnnotationType = "purpose"
	// Input 參數語意描述（非型別）— AI_CODING_RULES v1.0 強制
	Input AnnotationType = "input"
	// Output 回傳值語意與狀態碼描述 — AI_CODING_RULES v1.0 強制
	Output AnnotationType = "output"
	// SideEffect 副作用清單（DB / 外部呼叫 / IO / none）— AI_CODING_RULES v1.0 強制
	SideEffect AnnotationType = "sideeffect"
	// Modified AI 修改紀錄（by + date + reason）
	Modified AnnotationType = "modified"
)

// Annotation 結構化標註
type Annotation struct {
	Type  AnnotationType // 標註類型
	Value string         // 標註值（= 之後的部分）
	Line  int            // 所在行號
}

// prefix 是所有 AI 標註的前綴
const prefix = "@ai:"

// ParseAnnotations 從多行註解文字中提取所有 @ai: 標註
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 供 checker 與驗證工具解析既有 Go 註解中的 @ai 區塊
// @ai:input 多行 Go 註解文字（含或不含 // 前綴）
// @ai:output 所有已識別的 Annotation 切片（未知類型會被忽略）
// @ai:sideeffect none
func ParseAnnotations(text string) []Annotation {
	var result []Annotation
	lines := strings.Split(text, "\n")

	for i, line := range lines {
		line = strings.TrimSpace(line)
		// 移除 Go 註解前綴
		line = strings.TrimPrefix(line, "//")
		line = strings.TrimSpace(line)

		if !strings.HasPrefix(line, prefix) {
			continue
		}

		rest := line[len(prefix):]
		annType, value := parseAnnotationParts(rest)
		if annType != "" {
			result = append(result, Annotation{
				Type:  annType,
				Value: value,
				Line:  i + 1,
			})
		}
	}

	return result
}

// parseAnnotationParts 解析 @ai: 之後的型別和值
// 例如 "constraint max_items=100" → (Constraint, "max_items=100")
func parseAnnotationParts(s string) (AnnotationType, string) {
	s = strings.TrimSpace(s)
	parts := strings.SplitN(s, " ", 2)
	if len(parts) == 0 {
		return "", ""
	}

	typStr := strings.ToLower(parts[0])
	value := ""
	if len(parts) > 1 {
		value = strings.TrimSpace(parts[1])
	}

	switch AnnotationType(typStr) {
	case Constraint, Deprecated, Security, Impact, Owner,
		Generated, Purpose, Input, Output, SideEffect, Modified:
		return AnnotationType(typStr), value
	default:
		return "", ""
	}
}

// FormatAnnotation 將 Annotation 格式化為 Go 註解字串
func FormatAnnotation(a Annotation) string {
	if a.Value == "" {
		return "// " + prefix + string(a.Type)
	}
	return "// " + prefix + string(a.Type) + " " + a.Value
}

// ValidAnnotationTypes 回傳所有合法的標註類型
func ValidAnnotationTypes() []AnnotationType {
	return []AnnotationType{
		Constraint, Deprecated, Security, Impact, Owner,
		Generated, Purpose, Input, Output, SideEffect, Modified,
	}
}

// RequiredAnnotations 回傳特定區塊類型所需的必填標註。
// AI_CODING_RULES v1.0 規範：
//   - Exported func / method：generated + purpose + input + output + sideeffect
//   - Exported type / const / var：generated
//   - Package：generated + purpose
//   - Unexported：generated（僅當進入嚴格模式時才檢查）
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 讓 checker 依據區塊類型動態決定必填 @ai 欄位清單
// @ai:input kind 區塊類型字串 (package/type/func/method/const/var)，exported 是否為 exported
// @ai:output 必填標註類型切片
// @ai:sideeffect none
func RequiredAnnotations(kind string, exported bool) []AnnotationType {
	if !exported {
		return []AnnotationType{Generated}
	}
	switch kind {
	case "func", "method":
		return []AnnotationType{Generated, Purpose, Input, Output, SideEffect}
	case "package":
		return []AnnotationType{Generated, Purpose}
	case "type", "const", "var":
		return []AnnotationType{Generated}
	default:
		return []AnnotationType{Generated}
	}
}

// MissingAnnotations 比對既有與必填標註，回傳缺少的標註類型清單。
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 供 checker 計算某區塊尚欠哪些 @ai 欄位
// @ai:input existing 既有標註切片，required 必填標註類型切片
// @ai:output 缺少的標註類型切片（依 required 原順序）
// @ai:sideeffect none
func MissingAnnotations(existing []Annotation, required []AnnotationType) []AnnotationType {
	have := make(map[AnnotationType]bool, len(existing))
	for _, a := range existing {
		have[a.Type] = true
	}
	var missing []AnnotationType
	for _, req := range required {
		if !have[req] {
			missing = append(missing, req)
		}
	}
	return missing
}
