package annotation

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// CheckResult 單一區塊的檢查結果
type CheckResult struct {
	Name            string             // "func Create" 或 "type User"
	Kind            string             // "package", "type", "func", "method", "const", "var"
	Exported        bool               // 是否為 exported
	Line            int                // 宣告所在行號
	DocStartLine    int                // 既有 doc 的起始行（1-based，0 表示無 doc）
	DocEndLine      int                // 既有 doc 的結束行
	HasDoc          bool               // 是否已有任何文檔註解
	HasRequired     bool               // 是否具備所有必填 @ai 欄位
	ExistingTypes   []AnnotationType   // 既有的 @ai 標註類型
	MissingRequired []AnnotationType   // 缺少的必填 @ai 標註類型
	Suggested       string             // 建議的註解文字（無 doc 時用）
	SuggestedTags   map[AnnotationType]string // 缺漏的 @ai 標註建議值
}

// CheckReport 完整檢查報告
type CheckReport struct {
	Filename string
	Results  []CheckResult
	Total    int // 總區塊數
	Passed   int // 已符合 AI_CODING_RULES（HasRequired）的區塊數
}

// todayISO 回傳今日日期（YYYY-MM-DD）。變數化便於測試。
var todayISO = func() string {
	return time.Now().Format("2006-01-02")
}

// defaultProvider 為建議註解中 @ai:generated by= 的預設值。
const defaultProvider = "unknown"

// CheckFile 掃描 Go 檔案，回傳所有 exported 區塊的檢查結果
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 由 hyp chkcomment 呼叫，檢查檔案是否符合 AI_CODING_RULES v1.0 規範
// @ai:input filename Go 原始碼檔案路徑
// @ai:output CheckReport 指標與錯誤
// @ai:sideeffect 讀取檔案（僅讀不寫）
func CheckFile(filename string) (*CheckReport, error) {
	// 安全檢查：只接受 .go 檔案
	if filepath.Ext(filename) != ".go" {
		return nil, fmt.Errorf("only .go files are supported: %s", filename)
	}

	// 安全檢查：拒絕符號連結
	info, err := os.Lstat(filename)
	if err != nil {
		return nil, fmt.Errorf("cannot stat file: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("symbolic links are not supported: %s", filename)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse error: %w", err)
	}

	report := &CheckReport{
		Filename: filename,
	}

	// 檢查 package 宣告
	pkgResult := CheckResult{
		Name:     "package " + f.Name.Name,
		Kind:     "package",
		Exported: true,
		Line:     fset.Position(f.Package).Line,
	}
	applyDoc(&pkgResult, fset, f.Doc)
	pkgResult.Suggested = buildSuggested("Package "+f.Name.Name+" provides ...", "package", true, pkgResult.MissingRequired)
	pkgResult.SuggestedTags = buildTagSuggestions(pkgResult.MissingRequired, "package", f.Name.Name)
	report.addResult(pkgResult)

	// 遍歷所有頂層宣告
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			report.checkGenDecl(fset, d)
		case *ast.FuncDecl:
			report.checkFuncDecl(fset, d)
		}
	}

	// 排序（按行號）
	sort.Slice(report.Results, func(i, j int) bool {
		return report.Results[i].Line < report.Results[j].Line
	})

	// 計算統計：以「符合必填」為通過標準
	report.Total = len(report.Results)
	for _, r := range report.Results {
		if r.HasRequired {
			report.Passed++
		}
	}

	return report, nil
}

// applyDoc 從 ast.CommentGroup 填入 CheckResult 的 doc/annotation 相關欄位。
func applyDoc(r *CheckResult, fset *token.FileSet, doc *ast.CommentGroup) {
	required := RequiredAnnotations(r.Kind, r.Exported)

	if doc == nil || strings.TrimSpace(doc.Text()) == "" {
		r.HasDoc = false
		r.MissingRequired = append([]AnnotationType(nil), required...)
		r.HasRequired = len(r.MissingRequired) == 0
		return
	}

	r.HasDoc = true
	r.DocStartLine = fset.Position(doc.Pos()).Line
	r.DocEndLine = fset.Position(doc.End()).Line

	// 將整段 doc（含 // 符號）重組後交給 ParseAnnotations
	var sb strings.Builder
	for _, c := range doc.List {
		sb.WriteString(c.Text)
		sb.WriteString("\n")
	}
	anns := ParseAnnotations(sb.String())
	r.ExistingTypes = make([]AnnotationType, 0, len(anns))
	for _, a := range anns {
		r.ExistingTypes = append(r.ExistingTypes, a.Type)
	}
	r.MissingRequired = MissingAnnotations(anns, required)
	r.HasRequired = len(r.MissingRequired) == 0
}

// checkGenDecl 檢查 type/const/var 宣告
func (r *CheckReport) checkGenDecl(fset *token.FileSet, d *ast.GenDecl) {
	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.TypeSpec:
			if !s.Name.IsExported() {
				continue
			}
			res := CheckResult{
				Name:     "type " + s.Name.Name,
				Kind:     "type",
				Exported: true,
				Line:     fset.Position(s.Pos()).Line,
			}
			// 優先使用 s.Doc，否則退回 d.Doc
			doc := s.Doc
			if doc == nil {
				doc = d.Doc
			}
			applyDoc(&res, fset, doc)

			verb := "represents"
			if _, ok := s.Type.(*ast.InterfaceType); ok {
				verb = "defines"
			} else if _, ok := s.Type.(*ast.StructType); ok {
				verb = "represents"
			}
			res.Suggested = buildSuggested(fmt.Sprintf("%s %s ...", s.Name.Name, verb), "type", true, res.MissingRequired)
			res.SuggestedTags = buildTagSuggestions(res.MissingRequired, "type", s.Name.Name)
			r.addResult(res)

		case *ast.ValueSpec:
			for _, name := range s.Names {
				if !name.IsExported() {
					continue
				}
				kind := "var"
				if d.Tok == token.CONST {
					kind = "const"
				}
				res := CheckResult{
					Name:     kind + " " + name.Name,
					Kind:     kind,
					Exported: true,
					Line:     fset.Position(name.Pos()).Line,
				}
				doc := s.Doc
				if doc == nil {
					doc = d.Doc
				}
				applyDoc(&res, fset, doc)
				res.Suggested = buildSuggested(name.Name+" ...", kind, true, res.MissingRequired)
				res.SuggestedTags = buildTagSuggestions(res.MissingRequired, kind, name.Name)
				r.addResult(res)
			}
		}
	}
}

// checkFuncDecl 檢查 func/method 宣告
func (r *CheckReport) checkFuncDecl(fset *token.FileSet, d *ast.FuncDecl) {
	exported := d.Name.IsExported()

	kind := "func"
	name := d.Name.Name
	if d.Recv != nil && len(d.Recv.List) > 0 {
		kind = "method"
		recvType := exprToString(d.Recv.List[0].Type)
		name = recvType + "." + name
	}

	// 未 exported 的 func 若沒有 doc，則跳過（AI_CODING_RULES v1.0 只嚴格檢查 exported）
	if !exported {
		if d.Doc == nil || strings.TrimSpace(d.Doc.Text()) == "" {
			return
		}
	}

	res := CheckResult{
		Name:     kind + " " + name,
		Kind:     kind,
		Exported: exported,
		Line:     fset.Position(d.Pos()).Line,
	}
	applyDoc(&res, fset, d.Doc)

	// 根據函式名稱推斷建議的首句
	funcName := strings.ToLower(d.Name.Name)
	headline := d.Name.Name + " ..."
	switch {
	case strings.HasPrefix(funcName, "create"):
		headline = d.Name.Name + " 建立新資源"
	case strings.HasPrefix(funcName, "update"):
		headline = d.Name.Name + " 更新既有資源"
	case strings.HasPrefix(funcName, "delete"):
		headline = d.Name.Name + " 刪除資源"
	case strings.HasPrefix(funcName, "get"), strings.HasPrefix(funcName, "list"), strings.HasPrefix(funcName, "find"):
		headline = d.Name.Name + " 讀取資料"
	}

	res.Suggested = buildSuggested(headline, kind, exported, res.MissingRequired)
	res.SuggestedTags = buildTagSuggestions(res.MissingRequired, kind, d.Name.Name)
	r.addResult(res)
}

// buildSuggested 根據缺失的 @ai 標註建立完整建議註解區塊。
// 當區塊完全沒有 doc 時，FixFile 會使用這個完整區塊插入。
func buildSuggested(headline, kind string, exported bool, missing []AnnotationType) string {
	var sb strings.Builder
	sb.WriteString("// ")
	sb.WriteString(headline)
	sb.WriteString("\n//\n")

	required := RequiredAnnotations(kind, exported)
	if len(missing) == 0 {
		// 全部都有 → 仍列出標準骨架供使用者參考
		missing = required
	}

	placeholders := placeholderMap(kind)
	for _, m := range missing {
		if val, ok := placeholders[m]; ok && val != "" {
			sb.WriteString(fmt.Sprintf("// @ai:%s %s\n", m, val))
		} else {
			sb.WriteString(fmt.Sprintf("// @ai:%s\n", m))
		}
	}
	return strings.TrimSuffix(sb.String(), "\n")
}

// buildTagSuggestions 回傳缺漏標註的預設值，供 FixFile「增補」模式使用
// （當既有 doc 存在但欠某些 @ai 欄位）。
func buildTagSuggestions(missing []AnnotationType, kind, name string) map[AnnotationType]string {
	placeholders := placeholderMap(kind)
	out := make(map[AnnotationType]string, len(missing))
	for _, m := range missing {
		out[m] = placeholders[m]
	}
	_ = name
	return out
}

// placeholderMap 回傳某區塊類型的每個 @ai 欄位預設值。
func placeholderMap(kind string) map[AnnotationType]string {
	date := todayISO()
	base := map[AnnotationType]string{
		Generated:  fmt.Sprintf("by=%s date=%s", defaultProvider, date),
		Purpose:    "TODO: 說明此區塊為何存在（為什麼，非做什麼）",
		Input:      "TODO: 描述輸入語意（非型別）",
		Output:     "TODO: 描述回傳語意與狀態碼",
		SideEffect: "none",
		Owner:      "team=unassigned",
	}
	switch kind {
	case "package":
		base[Purpose] = "TODO: 說明此套件的職責"
	case "type", "const", "var":
		// 保持 generated 即可
	}
	return base
}

// addResult 加入檢查結果
func (r *CheckReport) addResult(result CheckResult) {
	r.Results = append(r.Results, result)
}

// FixFile 為缺少註解的區塊加入建議註解。
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 將 checker 的建議註解寫回 Go 檔案，支援「完全缺失」與「部分缺漏」兩種修補模式
// @ai:input filename 目標檔案路徑；results 先前 CheckFile 產出的結果清單
// @ai:output 寫入錯誤
// @ai:sideeffect 建立 <filename>.bak 備份後覆寫原檔
func FixFile(filename string, results []CheckResult) error {
	// 讀取原始檔案
	content, err := os.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("cannot read file: %w", err)
	}

	// 建立備份
	backupPath := filename + ".bak"
	if err := os.WriteFile(backupPath, content, 0644); err != nil {
		return fmt.Errorf("cannot create backup: %w", err)
	}

	lines := strings.Split(string(content), "\n")

	// 收集操作：分為「在 line 之前插入整塊註解」與「在某行之後插入若干 @ai 行」
	type op struct {
		line      int      // 作用行（0-based）
		mode      string   // "insertBefore" | "appendAfter"
		textLines []string // 欲插入的行（不含尾端 newline）
	}
	var ops []op

	for _, r := range results {
		if r.HasRequired {
			continue
		}

		// 模式 1：完全沒有 doc → 在宣告行之前插入完整建議
		if !r.HasDoc {
			commentLines := strings.Split(r.Suggested, "\n")
			ops = append(ops, op{
				line:      r.Line - 1, // 轉 0-based
				mode:      "insertBefore",
				textLines: commentLines,
			})
			continue
		}

		// 模式 2：有 doc 但缺 @ai 欄位 → 在既有 doc 的最後一行之後追加
		var addLines []string
		for _, m := range r.MissingRequired {
			val := r.SuggestedTags[m]
			if val == "" {
				addLines = append(addLines, "// @ai:"+string(m))
			} else {
				addLines = append(addLines, "// @ai:"+string(m)+" "+val)
			}
		}
		if len(addLines) == 0 {
			continue
		}
		if r.DocEndLine == 0 {
			// fallback：若無法取得 doc 結束行，視為 mode 1
			commentLines := strings.Split(r.Suggested, "\n")
			ops = append(ops, op{
				line:      r.Line - 1,
				mode:      "insertBefore",
				textLines: commentLines,
			})
			continue
		}
		ops = append(ops, op{
			line:      r.DocEndLine - 1, // 0-based，該行之後插入
			mode:      "appendAfter",
			textLines: addLines,
		})
	}

	// 由下往上套用，避免行號偏移
	sort.Slice(ops, func(i, j int) bool {
		if ops[i].line != ops[j].line {
			return ops[i].line > ops[j].line
		}
		// 同一行時：appendAfter 先於 insertBefore（讓 before 在更前面，數值大者先執行）
		return ops[i].mode == "insertBefore" && ops[j].mode == "appendAfter"
	})

	for _, o := range ops {
		if o.line < 0 {
			o.line = 0
		}
		if o.line > len(lines) {
			o.line = len(lines)
		}

		// 取得該宣告行（或 doc 末行）的縮排
		indent := ""
		refLine := o.line
		if o.mode == "appendAfter" {
			refLine = o.line // 以 doc 末行縮排為準
		}
		if refLine < len(lines) {
			for _, ch := range lines[refLine] {
				if ch == '\t' || ch == ' ' {
					indent += string(ch)
				} else {
					break
				}
			}
		}

		newLines := make([]string, len(o.textLines))
		for i, cl := range o.textLines {
			newLines[i] = indent + cl
		}

		switch o.mode {
		case "insertBefore":
			before := append([]string{}, lines[:o.line]...)
			after := append([]string{}, lines[o.line:]...)
			lines = append(before, append(newLines, after...)...)
		case "appendAfter":
			insertAt := o.line + 1
			if insertAt > len(lines) {
				insertAt = len(lines)
			}
			before := append([]string{}, lines[:insertAt]...)
			after := append([]string{}, lines[insertAt:]...)
			lines = append(before, append(newLines, after...)...)
		}
	}

	return os.WriteFile(filename, []byte(strings.Join(lines, "\n")), 0644)
}

// FormatReport 格式化檢查報告為人類可讀字串
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 將 CheckReport 轉為終端機友善輸出，顯示每個區塊缺少的 @ai 欄位
// @ai:input CheckReport 指標
// @ai:output 人類可讀字串
// @ai:sideeffect none
func FormatReport(report *CheckReport) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("Scanning: %s\n\n", report.Filename))

	for _, r := range report.Results {
		if r.HasRequired {
			sb.WriteString(fmt.Sprintf("[PASS] %s (line %d)\n", r.Name, r.Line))
			continue
		}
		if !r.HasDoc {
			sb.WriteString(fmt.Sprintf("[FAIL] %s (line %d) — missing doc comment\n", r.Name, r.Line))
		} else {
			sb.WriteString(fmt.Sprintf("[WARN] %s (line %d) — missing required @ai tags: %s\n",
				r.Name, r.Line, joinTypes(r.MissingRequired)))
		}
		sb.WriteString("  → suggested:\n")
		for _, line := range strings.Split(r.Suggested, "\n") {
			sb.WriteString("    " + line + "\n")
		}
	}

	sb.WriteString(fmt.Sprintf("\nSummary: %d/%d blocks satisfy AI_CODING_RULES (%d%%)\n",
		report.Passed, report.Total, percent(report.Passed, report.Total)))

	failed := report.Total - report.Passed
	if failed > 0 {
		sb.WriteString(fmt.Sprintf("  %d blocks need attention — run with --fix to auto-patch\n", failed))
	}

	return sb.String()
}

// joinTypes 將 AnnotationType 切片用 "," 串接。
func joinTypes(ts []AnnotationType) string {
	if len(ts) == 0 {
		return "(none)"
	}
	parts := make([]string, len(ts))
	for i, t := range ts {
		parts[i] = string(t)
	}
	return strings.Join(parts, ",")
}

// exprToString 將 AST expr 轉為字串（用於 receiver type）
func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	default:
		return "?"
	}
}

func percent(a, b int) int {
	if b == 0 {
		return 0
	}
	return a * 100 / b
}
