package annotation

import (
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// CheckResult 單一區塊的檢查結果
type CheckResult struct {
	Name            string                    // "func Create" 或 "type User"
	Kind            string                    // "package", "type", "func", "method", "const", "var"
	Exported        bool                      // 是否為 exported
	Line            int                       // 宣告所在行號
	DocStartLine    int                       // 既有 doc 的起始行（1-based，0 表示無 doc）
	DocEndLine      int                       // 既有 doc 的結束行
	HasDoc          bool                      // 是否已有任何文檔註解
	DocHeadline     string                    // 第一個非 @ai:、非空白的 godoc 說明行（空字串 = 缺失或佔位符待補）
	HasRequired     bool                      // 是否具備所有必填 @ai 欄位
	HumanAuthor     string                    // 人類作者標記 // @<author> 的作者代號（非空 = 人類撰寫，免 @ai 必填）
	ExistingTypes   []AnnotationType          // 既有的 @ai 標註類型
	MissingRequired []AnnotationType          // 缺少的必填 @ai 標註類型
	Suggested       string                    // 建議的註解文字（無 doc 時用）
	SuggestedTags   map[AnnotationType]string // 缺漏的 @ai 標註建議值
}

// CheckReport 完整檢查報告
type CheckReport struct {
	Filename string
	Results  []CheckResult
	Total    int // 總區塊數
	Passed   int // 已符合 AI_CODING_RULES（HasRequired）的區塊數
}

// todayISO 回傳今日日期（YYYY-MM-DD）。變數化便於測試。
var todayISO = func() string {
	return time.Now().Format("2006-01-02")
}

// defaultProvider 為建議註解中 @ai:generated by= 的預設值。
const defaultProvider = "unknown"

// CheckFile 掃描 Go 檔案，回傳所有 exported 區塊的檢查結果
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 由 hyp chkcomment 呼叫，檢查檔案是否符合 AI_CODING_RULES v1.0 規範
// @ai:input filename Go 原始碼檔案路徑
// @ai:output CheckReport 指標與錯誤
// @ai:sideeffect 讀取檔案（僅讀不寫）
func CheckFile(filename string) (*CheckReport, error) {
	// 安全檢查：只接受 .go 檔案
	if filepath.Ext(filename) != ".go" {
		return nil, fmt.Errorf("only .go files are supported: %s", filename)
	}

	// 安全檢查：拒絕符號連結
	info, err := os.Lstat(filename)
	if err != nil {
		return nil, fmt.Errorf("cannot stat file: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("symbolic links are not supported: %s", filename)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse error: %w", err)
	}

	report := &CheckReport{
		Filename: filename,
	}

	// 檢查 package 宣告
	pkgResult := CheckResult{
		Name:     "package " + f.Name.Name,
		Kind:     "package",
		Exported: true,
		Line:     fset.Position(f.Package).Line,
	}
	applyDoc(&pkgResult, fset, f.Doc)
	pkgResult.Suggested = buildSuggested("Package "+f.Name.Name+" provides ...", "package", true, pkgResult.MissingRequired)
	pkgResult.SuggestedTags = buildTagSuggestions(pkgResult.MissingRequired, "package", f.Name.Name)
	report.addResult(pkgResult)

	// 遍歷所有頂層宣告
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			report.checkGenDecl(fset, d)
		case *ast.FuncDecl:
			report.checkFuncDecl(fset, d)
		}
	}

	// 排序（按行號）
	sort.Slice(report.Results, func(i, j int) bool {
		return report.Results[i].Line < report.Results[j].Line
	})

	// 檔案層級作者宣告：package doc 若建立了作者出處 ⇒ 整個檔案視為「該作者撰寫」。
	// 兩種建立方式對稱：
	//   - 人類作者標記 // @<author>（如 // @chris）
	//   - 檔案層級 // @ai:generated by=<model>（如 claude-opus-4-6）
	// 此時各區塊若未「自行」宣告 @ai:generated，便繼承免除 @ai 必填檢查；
	// 自帶 @ai:generated 的區塊仍依 AI 標準檢查（混合作者檔案中後加的部分不會被誤免除）。
	pkgAuthored := pkgResult.HumanAuthor != "" || containsAnnotationType(pkgResult.ExistingTypes, Generated)
	if pkgAuthored {
		for i := range report.Results {
			r := &report.Results[i]
			if r.HasRequired {
				continue
			}
			// package 區塊本身即作者宣告處 → 視為已滿足（@ai:generated 即足以建立檔案出處）
			if r.Kind == "package" {
				r.MissingRequired = nil
				r.HasRequired = true
				continue
			}
			// 其他區塊自帶 @ai:generated 者照常檢查（不繼承豁免）
			if containsAnnotationType(r.ExistingTypes, Generated) {
				continue
			}
			if r.HumanAuthor == "" {
				r.HumanAuthor = pkgResult.HumanAuthor // 人類作者繼承（claude 等 AI 作者情況為空字串）
			}
			r.MissingRequired = nil
			r.HasRequired = true
		}
	}

	// 計算統計：以「符合必填」為通過標準
	report.Total = len(report.Results)
	for _, r := range report.Results {
		if r.HasRequired {
			report.Passed++
		}
	}

	return report, nil
}

// applyDoc 從 ast.CommentGroup 填入 CheckResult 的 doc/annotation 相關欄位。
func applyDoc(r *CheckResult, fset *token.FileSet, doc *ast.CommentGroup) {
	required := RequiredAnnotations(r.Kind, r.Exported)

	if doc == nil || strings.TrimSpace(doc.Text()) == "" {
		r.HasDoc = false
		r.MissingRequired = append([]AnnotationType(nil), required...)
		r.HasRequired = len(r.MissingRequired) == 0
		return
	}

	r.HasDoc = true
	r.DocHeadline = extractDocHeadline(doc)
	r.DocStartLine = fset.Position(doc.Pos()).Line
	r.DocEndLine = fset.Position(doc.End()).Line

	// 將整段 doc（含 // 符號）重組後交給 ParseAnnotations
	var sb strings.Builder
	for _, c := range doc.List {
		sb.WriteString(c.Text)
		sb.WriteString("\n")
	}
	anns := ParseAnnotations(sb.String())
	r.ExistingTypes = make([]AnnotationType, 0, len(anns))
	for _, a := range anns {
		r.ExistingTypes = append(r.ExistingTypes, a.Type)
	}
	r.MissingRequired = MissingAnnotations(anns, required)

	// 人類作者標記（// @<author>）建立真實 provenance：免除此區塊的 @ai 必填檢查，
	// 避免對人類撰寫的程式碼強加 @ai:generated 的假歸屬。
	if author, ok := HumanAuthor(sb.String()); ok {
		r.HumanAuthor = author
		r.MissingRequired = nil
	}
	r.HasRequired = len(r.MissingRequired) == 0
}

// checkGenDecl 檢查 type/const/var 宣告
func (r *CheckReport) checkGenDecl(fset *token.FileSet, d *ast.GenDecl) {
	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.TypeSpec:
			if !s.Name.IsExported() {
				continue
			}
			res := CheckResult{
				Name:     "type " + s.Name.Name,
				Kind:     "type",
				Exported: true,
				Line:     fset.Position(s.Pos()).Line,
			}
			// 優先使用 s.Doc，否則退回 d.Doc
			doc := s.Doc
			if doc == nil {
				doc = d.Doc
			}
			applyDoc(&res, fset, doc)

			verb := "represents"
			if _, ok := s.Type.(*ast.InterfaceType); ok {
				verb = "defines"
			} else if _, ok := s.Type.(*ast.StructType); ok {
				verb = "represents"
			}
			res.Suggested = buildSuggested(fmt.Sprintf("%s %s ...", s.Name.Name, verb), "type", true, res.MissingRequired)
			res.SuggestedTags = buildTagSuggestions(res.MissingRequired, "type", s.Name.Name)
			r.addResult(res)

		case *ast.ValueSpec:
			for _, name := range s.Names {
				if !name.IsExported() {
					continue
				}
				kind := "var"
				if d.Tok == token.CONST {
					kind = "const"
				}
				res := CheckResult{
					Name:     kind + " " + name.Name,
					Kind:     kind,
					Exported: true,
					Line:     fset.Position(name.Pos()).Line,
				}
				doc := s.Doc
				if doc == nil {
					doc = d.Doc
				}
				applyDoc(&res, fset, doc)
				res.Suggested = buildSuggested(name.Name+" ...", kind, true, res.MissingRequired)
				res.SuggestedTags = buildTagSuggestions(res.MissingRequired, kind, name.Name)
				r.addResult(res)
			}
		}
	}
}

// checkFuncDecl 檢查 func/method 宣告
func (r *CheckReport) checkFuncDecl(fset *token.FileSet, d *ast.FuncDecl) {
	exported := d.Name.IsExported()

	kind := "func"
	name := d.Name.Name
	if d.Recv != nil && len(d.Recv.List) > 0 {
		kind = "method"
		recvType := exprToString(d.Recv.List[0].Type)
		name = recvType + "." + name
	}

	// 未 exported 的 func 若沒有 doc，則跳過（AI_CODING_RULES v1.0 只嚴格檢查 exported）
	if !exported {
		if d.Doc == nil || strings.TrimSpace(d.Doc.Text()) == "" {
			return
		}
	}

	res := CheckResult{
		Name:     kind + " " + name,
		Kind:     kind,
		Exported: exported,
		Line:     fset.Position(d.Pos()).Line,
	}
	applyDoc(&res, fset, d.Doc)

	// 根據函式名稱推斷建議的首句
	funcName := strings.ToLower(d.Name.Name)
	headline := d.Name.Name + " ..."
	switch {
	case strings.HasPrefix(funcName, "create"):
		headline = d.Name.Name + " 建立新資源"
	case strings.HasPrefix(funcName, "update"):
		headline = d.Name.Name + " 更新既有資源"
	case strings.HasPrefix(funcName, "delete"):
		headline = d.Name.Name + " 刪除資源"
	case strings.HasPrefix(funcName, "get"), strings.HasPrefix(funcName, "list"), strings.HasPrefix(funcName, "find"):
		headline = d.Name.Name + " 讀取資料"
	}

	res.Suggested = buildSuggested(headline, kind, exported, res.MissingRequired)
	res.SuggestedTags = buildTagSuggestions(res.MissingRequired, kind, d.Name.Name)
	r.addResult(res)
}

// buildSuggested 根據缺失的 @ai 標註建立完整建議註解區塊。
// 當區塊完全沒有 doc 時，FixFile 會使用這個完整區塊插入。
func buildSuggested(headline, kind string, exported bool, missing []AnnotationType) string {
	var sb strings.Builder
	sb.WriteString("// ")
	sb.WriteString(headline)
	sb.WriteString("\n//\n")

	required := RequiredAnnotations(kind, exported)
	if len(missing) == 0 {
		// 全部都有 → 仍列出標準骨架供使用者參考
		missing = required
	}

	placeholders := placeholderMap(kind)
	for _, m := range missing {
		if val, ok := placeholders[m]; ok && val != "" {
			sb.WriteString(fmt.Sprintf("// @ai:%s %s\n", m, val))
		} else {
			sb.WriteString(fmt.Sprintf("// @ai:%s\n", m))
		}
	}
	return strings.TrimSuffix(sb.String(), "\n")
}

// buildTagSuggestions 回傳缺漏標註的預設值，供 FixFile「增補」模式使用
// （當既有 doc 存在但欠某些 @ai 欄位）。
func buildTagSuggestions(missing []AnnotationType, kind, name string) map[AnnotationType]string {
	placeholders := placeholderMap(kind)
	out := make(map[AnnotationType]string, len(missing))
	for _, m := range missing {
		out[m] = placeholders[m]
	}
	_ = name
	return out
}

// placeholderMap 回傳某區塊類型的每個 @ai 欄位預設值。
func placeholderMap(kind string) map[AnnotationType]string {
	date := todayISO()
	base := map[AnnotationType]string{
		Generated:  fmt.Sprintf("by=%s date=%s", defaultProvider, date),
		Purpose:    "TODO: 說明此區塊為何存在（為什麼，非做什麼）",
		Input:      "TODO: 描述輸入語意（非型別）",
		Output:     "TODO: 描述回傳語意與狀態碼",
		SideEffect: "none",
		Owner:      "team=unassigned",
	}
	switch kind {
	case "package":
		base[Purpose] = "TODO: 說明此套件的職責"
	case "type", "const", "var":
		// 保持 generated 即可
	}
	return base
}

// addResult 加入檢查結果
func (r *CheckReport) addResult(result CheckResult) {
	r.Results = append(r.Results, result)
}

// FixFile 為缺少註解的區塊加入建議註解。
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 將 checker 的建議註解寫回 Go 檔案，支援「完全缺失」與「部分缺漏」兩種修補模式
// @ai:input filename 目標檔案路徑；results 先前 CheckFile 產出的結果清單
// @ai:output 寫入錯誤
// @ai:sideeffect 建立 <filename>.bak 備份後覆寫原檔
func FixFile(filename string, results []CheckResult) error {
	// 讀取原始檔案
	content, err := os.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("cannot read file: %w", err)
	}

	// 建立備份
	backupPath := filename + ".bak"
	if err := os.WriteFile(backupPath, content, 0644); err != nil {
		return fmt.Errorf("cannot create backup: %w", err)
	}

	lines := strings.Split(string(content), "\n")

	// 收集操作：分為「在 line 之前插入整塊註解」與「在某行之後插入若干 @ai 行」
	type op struct {
		line      int      // 作用行（0-based）
		mode      string   // "insertBefore" | "appendAfter"
		textLines []string // 欲插入的行（不含尾端 newline）
	}
	var ops []op

	for _, r := range results {
		if r.HasRequired {
			continue
		}

		// 模式 1：完全沒有 doc → 在宣告行之前插入完整建議
		if !r.HasDoc {
			commentLines := strings.Split(r.Suggested, "\n")
			ops = append(ops, op{
				line:      r.Line - 1, // 轉 0-based
				mode:      "insertBefore",
				textLines: commentLines,
			})
			continue
		}

		// 模式 2：有 doc 但缺 @ai 欄位 → 在既有 doc 的最後一行之後追加
		var addLines []string
		for _, m := range r.MissingRequired {
			val := r.SuggestedTags[m]
			if val == "" {
				addLines = append(addLines, "// @ai:"+string(m))
			} else {
				addLines = append(addLines, "// @ai:"+string(m)+" "+val)
			}
		}
		if len(addLines) == 0 {
			continue
		}
		if r.DocEndLine == 0 {
			// fallback：若無法取得 doc 結束行，視為 mode 1
			commentLines := strings.Split(r.Suggested, "\n")
			ops = append(ops, op{
				line:      r.Line - 1,
				mode:      "insertBefore",
				textLines: commentLines,
			})
			continue
		}
		ops = append(ops, op{
			line:      r.DocEndLine - 1, // 0-based，該行之後插入
			mode:      "appendAfter",
			textLines: addLines,
		})
	}

	// 由下往上套用，避免行號偏移
	sort.Slice(ops, func(i, j int) bool {
		if ops[i].line != ops[j].line {
			return ops[i].line > ops[j].line
		}
		// 同一行時：appendAfter 先於 insertBefore（讓 before 在更前面，數值大者先執行）
		return ops[i].mode == "insertBefore" && ops[j].mode == "appendAfter"
	})

	for _, o := range ops {
		if o.line < 0 {
			o.line = 0
		}
		if o.line > len(lines) {
			o.line = len(lines)
		}

		// 取得該宣告行（或 doc 末行）的縮排
		indent := ""
		refLine := o.line
		if o.mode == "appendAfter" {
			refLine = o.line // 以 doc 末行縮排為準
		}
		if refLine < len(lines) {
			for _, ch := range lines[refLine] {
				if ch == '\t' || ch == ' ' {
					indent += string(ch)
				} else {
					break
				}
			}
		}

		newLines := make([]string, len(o.textLines))
		for i, cl := range o.textLines {
			newLines[i] = indent + cl
		}

		switch o.mode {
		case "insertBefore":
			before := append([]string{}, lines[:o.line]...)
			after := append([]string{}, lines[o.line:]...)
			lines = append(before, append(newLines, after...)...)
		case "appendAfter":
			insertAt := o.line + 1
			if insertAt > len(lines) {
				insertAt = len(lines)
			}
			before := append([]string{}, lines[:insertAt]...)
			after := append([]string{}, lines[insertAt:]...)
			lines = append(before, append(newLines, after...)...)
		}
	}

	return os.WriteFile(filename, []byte(strings.Join(lines, "\n")), 0644)
}

// FormatReport 格式化檢查報告為人類可讀字串
//
// @ai:generated by=hypgo date=2026-04-23
// @ai:purpose 將 CheckReport 轉為終端機友善輸出，顯示每個區塊缺少的 @ai 欄位
// @ai:input CheckReport 指標
// @ai:output 人類可讀字串
// @ai:sideeffect none
func FormatReport(report *CheckReport) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("Scanning: %s\n\n", report.Filename))

	for _, r := range report.Results {
		if r.HasRequired {
			if r.HumanAuthor != "" {
				sb.WriteString(fmt.Sprintf("[HUMAN] %s (line %d) — authored by @%s\n", r.Name, r.Line, r.HumanAuthor))
			} else {
				sb.WriteString(fmt.Sprintf("[PASS] %s (line %d)\n", r.Name, r.Line))
			}
			continue
		}
		if !r.HasDoc {
			sb.WriteString(fmt.Sprintf("[FAIL] %s (line %d) — missing doc comment\n", r.Name, r.Line))
		} else {
			sb.WriteString(fmt.Sprintf("[WARN] %s (line %d) — missing required @ai tags: %s\n",
				r.Name, r.Line, joinTypes(r.MissingRequired)))
		}
		sb.WriteString("  → suggested:\n")
		for _, line := range strings.Split(r.Suggested, "\n") {
			sb.WriteString("    " + line + "\n")
		}
	}

	sb.WriteString(fmt.Sprintf("\nSummary: %d/%d blocks satisfy AI_CODING_RULES (%d%%)\n",
		report.Passed, report.Total, percent(report.Passed, report.Total)))

	failed := report.Total - report.Passed
	if failed > 0 {
		sb.WriteString(fmt.Sprintf("  %d blocks need attention — run with --fix to auto-patch\n", failed))
	}

	return sb.String()
}

// joinTypes 將 AnnotationType 切片用 "," 串接。
func joinTypes(ts []AnnotationType) string {
	if len(ts) == 0 {
		return "(none)"
	}
	parts := make([]string, len(ts))
	for i, t := range ts {
		parts[i] = string(t)
	}
	return strings.Join(parts, ",")
}

// exprToString 將 AST expr 轉為字串（用於 receiver type）
func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	default:
		return "?"
	}
}

func percent(a, b int) int {
	if b == 0 {
		return 0
	}
	return a * 100 / b
}

// FixFileWithSuggester 為缺少註解的區塊呼叫 Suggester 取得 doc 與 @ai 標註，
// 再委派給 FixFile 寫入檔案（仍會建立 .go.bak 備份）。
//
// 與單純 FixFile 的差異：
//  1. r.Suggested（無 doc 時用）的「headline」會替換為 Suggester 產出的一行說明
//  2. r.SuggestedTags（補 @ai 欄位用）的 generated 一欄會填入真實 provider 名稱
//  3. Suggester 額外回傳的 @ai 標註（security/owner/...）會合併進 SuggestedTags
//
// 任一 Suggest 呼叫失敗時，該區塊退回使用既有的 r.Suggested / r.SuggestedTags。
func FixFileWithSuggester(ctx context.Context, filename string, results []CheckResult, s Suggester) error {
	if s == nil {
		return FixFile(filename, results)
	}
	provider := s.ProviderName()
	if provider == "" {
		provider = defaultProvider
	}
	date := todayISO()
	generatedValue := fmt.Sprintf("by=%s date=%s", provider, date)

	enriched := make([]CheckResult, len(results))
	copy(enriched, results)

	for i := range enriched {
		r := &enriched[i]
		if r.HasRequired && r.HasDoc {
			continue
		}

		// 一律以真實 provider 取代 @ai:generated by=<unknown> 預設
		if r.SuggestedTags == nil {
			r.SuggestedTags = make(map[AnnotationType]string)
		}
		r.SuggestedTags[Generated] = generatedValue
		r.Suggested = replaceGeneratedProvider(r.Suggested, generatedValue)

		name := strings.TrimPrefix(r.Name, r.Kind+" ")
		req := SuggestRequest{
			Kind: r.Kind,
			Name: name,
			File: filename,
		}
		// package 的 r.Name 為 "package <pkgName>"，把 PkgName 補上才能讓 Suggester 產生
		// 正確的 "Package <pkgName> provides ..." 標題
		if r.Kind == "package" {
			req.PkgName = name
		}
		out, err := s.Suggest(ctx, req)
		if err != nil {
			continue
		}

		// 用 Suggester 產出的 doc 替換 r.Suggested 的 headline
		if !r.HasDoc && out.Doc != "" {
			r.Suggested = replaceSuggestedHeadline(r.Suggested, out.Doc)
		}

		// 合併額外的 @ai 標註（security/owner/constraint/...）；不覆寫既有值
		for _, a := range out.Annotations {
			if a.Value == "" {
				continue
			}
			if _, exists := r.SuggestedTags[a.Type]; exists {
				continue
			}
			r.SuggestedTags[a.Type] = a.Value
			// 若該區塊原本 HasDoc=true 但缺必填欄位，FixFile 只會輸出 MissingRequired
			// 中列出的標籤。把額外的標籤補進 MissingRequired，確保 appendAfter 模式也會寫入
			if r.HasDoc && !containsAnnotationType(r.MissingRequired, a.Type) {
				r.MissingRequired = append(r.MissingRequired, a.Type)
			}
		}

		// 如果 LLM 沒回 doc 但區塊本身就缺 doc，仍需重建 r.Suggested 以包含新合併的 tags
		if !r.HasDoc {
			r.Suggested = rebuildSuggestedFromTags(r)
		}
	}

	return FixFile(filename, enriched)
}

// replaceGeneratedProvider 把 r.Suggested 內的 `@ai:generated by=... date=...` 行替換成新值
func replaceGeneratedProvider(suggested, generatedValue string) string {
	if suggested == "" {
		return suggested
	}
	lines := strings.Split(suggested, "\n")
	for i, ln := range lines {
		trim := strings.TrimSpace(strings.TrimPrefix(ln, "//"))
		if strings.HasPrefix(trim, "@ai:generated") {
			lines[i] = "// @ai:generated " + generatedValue
		}
	}
	return strings.Join(lines, "\n")
}

// replaceSuggestedHeadline 取代 r.Suggested 的第一行 godoc 標題為新文字
func replaceSuggestedHeadline(suggested, doc string) string {
	if doc == "" {
		return suggested
	}
	lines := strings.Split(suggested, "\n")
	if len(lines) == 0 {
		return "// " + doc
	}
	lines[0] = "// " + doc
	return strings.Join(lines, "\n")
}

// rebuildSuggestedFromTags 依 r.SuggestedTags 重建建議註解區塊。
// 用於 LLM 補上額外 @ai 標籤時，r.Suggested 也需要包含這些新增行。
func rebuildSuggestedFromTags(r *CheckResult) string {
	if r == nil {
		return ""
	}
	// 取出第一行 headline；若 r.Suggested 為空，給一個 placeholder
	headline := r.Name + " ..."
	if r.Suggested != "" {
		parts := strings.SplitN(r.Suggested, "\n", 2)
		if strings.HasPrefix(parts[0], "// ") {
			headline = strings.TrimPrefix(parts[0], "// ")
		}
	}

	var sb strings.Builder
	sb.WriteString("// ")
	sb.WriteString(headline)
	sb.WriteString("\n//")
	// 先輸出必填欄位，再附加其他（owner/security/constraint/...）
	required := RequiredAnnotations(r.Kind, r.Exported)
	emitted := make(map[AnnotationType]bool, len(r.SuggestedTags))
	for _, t := range required {
		val := r.SuggestedTags[t]
		sb.WriteString("\n// @ai:")
		sb.WriteString(string(t))
		if val != "" {
			sb.WriteString(" ")
			sb.WriteString(val)
		}
		emitted[t] = true
	}
	for t, val := range r.SuggestedTags {
		if emitted[t] {
			continue
		}
		sb.WriteString("\n// @ai:")
		sb.WriteString(string(t))
		if val != "" {
			sb.WriteString(" ")
			sb.WriteString(val)
		}
	}
	return sb.String()
}

func containsAnnotationType(s []AnnotationType, t AnnotationType) bool {
	for _, v := range s {
		if v == t {
			return true
		}
	}
	return false
}

// extractDocHeadline 回傳 doc 中第一個非 @ai:、非空白的 godoc 說明行（已去除 // 前綴）。
func extractDocHeadline(doc *ast.CommentGroup) string {
	if doc == nil {
		return ""
	}
	for _, c := range doc.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if text == "" || strings.HasPrefix(text, "@ai:") {
			continue
		}
		return text
	}
	return ""
}

// isPlaceholderHeadline 回傳 true 若說明行為空或仍是自動生成的佔位符。
func isPlaceholderHeadline(s string) bool {
	s = strings.TrimSpace(s)
	if s == "" {
		return true
	}
	return strings.HasSuffix(s, "...") || strings.HasPrefix(s, "TODO:")
}

// needsGitEnrichment 回傳 true 若區塊已有 @ai: 標註但 godoc headline 仍是佔位符。
func needsGitEnrichment(r CheckResult) bool {
	return len(r.ExistingTypes) > 0 && isPlaceholderHeadline(r.DocHeadline)
}

// findHeadlineLineIdx 在 lines（0-based）的 [docStart-1, docEnd-1] 範圍內，
// 找出第一個可替換的 godoc headline 行，回傳 0-based 索引；找不到回傳 -1。
func findHeadlineLineIdx(lines []string, docStart, docEnd int) int {
	for i := docStart - 1; i < docEnd && i < len(lines); i++ {
		if i < 0 {
			continue
		}
		text := strings.TrimSpace(strings.TrimPrefix(lines[i], "//"))
		if text != "" && !strings.HasPrefix(text, "@ai:") {
			return i
		}
	}
	return -1
}

// EnrichMissingHeadlines 對所有已有 @ai: 標註但 godoc headline 仍是佔位符的區塊，
// 使用 git 歷史脈絡呼叫 Suggester 產生有意義的說明行，並原地替換。
// 僅替換既有行、不新增行，因此不影響其他行號，可在 FixFileWithSuggester 之前安全呼叫。
//
// @ai:generated by=hypgo date=2026-05-25
// @ai:purpose 補充 placeholder headline：在 LLM 有 git 脈絡時產生真實語意說明
// @ai:input ctx context；filename 目標 .go 路徑；results CheckFile 的輸出；s Suggester
// @ai:output 已替換的區塊數量，以及任何 IO / Suggest 錯誤
// @ai:sideeffect 讀寫 filename（直接替換，不建立備份）
func EnrichMissingHeadlines(ctx context.Context, filename string, results []CheckResult, s Suggester) (int, error) {
	if s == nil {
		return 0, nil
	}

	content, err := os.ReadFile(filename)
	if err != nil {
		return 0, fmt.Errorf("enrich read: %w", err)
	}
	lines := strings.Split(string(content), "\n")

	count := 0
	for _, r := range results {
		if !needsGitEnrichment(r) {
			continue
		}
		if r.DocStartLine == 0 || r.DocEndLine == 0 {
			continue
		}

		idx := findHeadlineLineIdx(lines, r.DocStartLine, r.DocEndLine)
		if idx < 0 {
			continue
		}

		declName := strings.TrimPrefix(r.Name, r.Kind+" ")
		bare := baseName(declName)
		gc := GatherGitContext(filename, bare, r.Kind, 10)

		req := SuggestRequest{
			Kind:       r.Kind,
			Name:       bare,
			File:       filename,
			GitContext: gc,
		}
		if r.Kind == "package" {
			req.PkgName = bare
		}

		out, suggestErr := s.Suggest(ctx, req)
		if suggestErr != nil || out.Doc == "" {
			continue
		}

		origLine := lines[idx]
		indent := ""
		for _, ch := range origLine {
			if ch == '\t' || ch == ' ' {
				indent += string(ch)
			} else {
				break
			}
		}
		lines[idx] = indent + "// " + out.Doc
		count++
	}

	if count == 0 {
		return 0, nil
	}
	if writeErr := os.WriteFile(filename, []byte(strings.Join(lines, "\n")), 0644); writeErr != nil {
		return count, fmt.Errorf("enrich write: %w", writeErr)
	}
	return count, nil
}
