// @ai:generated by=claude-opus-4-7 date=2026-06-19
package annotation

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeTempGo(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "fixture.go")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestParseCleanLevel(t *testing.T) {
	for _, n := range []int{1, 2, 3} {
		if _, err := ParseCleanLevel(n); err != nil {
			t.Errorf("ParseCleanLevel(%d) error: %v", n, err)
		}
	}
	for _, n := range []int{0, 4, -1, 99} {
		if _, err := ParseCleanLevel(n); err == nil {
			t.Errorf("ParseCleanLevel(%d) should reject", n)
		}
	}
}

// Level 1：移除所有 @ai；func 無 @<human> 標記 → 描述行也移除
func TestCleanFile_Level1_RemovesAll_StripsDescriptionWhenNoHumanMarker(t *testing.T) {
	src := `package example

// CreateUser 建立使用者並寫進資料庫。
//
// @ai:generated by=claude-opus-4-8 date=2026-06-18
// @ai:purpose 提供 REST API 建立帳號
// @ai:input JSON body
// @ai:output 201 + UserResp
// @ai:sideeffect DB insert
func CreateUser() {
	//@ai:think intent=先驗證 email 唯一性 model=claude-opus-4-8
	println("ok")
}
`
	path := writeTempGo(t, src)
	report, err := CleanFile(path, CleanLevelAll)
	if err != nil {
		t.Fatal(err)
	}
	if !report.Modified {
		t.Fatal("expected file to be modified")
	}

	data, _ := os.ReadFile(path)
	out := string(data)
	if strings.Contains(out, "@ai:") {
		t.Errorf("level 1 should remove all @ai, got:\n%s", out)
	}
	// 描述也應被移除（無 @human）
	if strings.Contains(out, "CreateUser 建立使用者並寫進資料庫") {
		t.Errorf("description should be removed (no human marker), got:\n%s", out)
	}
	// 但 func 本體應保留
	if !strings.Contains(out, "func CreateUser()") {
		t.Errorf("func declaration should remain, got:\n%s", out)
	}
	if !strings.Contains(out, `println("ok")`) {
		t.Errorf("func body code should remain, got:\n%s", out)
	}
	// .bak 應該存在
	if _, err := os.Stat(report.BackupPath); err != nil {
		t.Errorf("backup should exist: %v", err)
	}
}

// Level 1 + 有 @human 標記 → 移除 @ai 但保留描述
func TestCleanFile_Level1_KeepsDescriptionWhenHumanMarkerPresent(t *testing.T) {
	src := `package example

// CreateUser 建立使用者。
//
// @chris 2026-06-18
// @ai:generated by=claude-opus-4-8 date=2026-06-18
// @ai:purpose 提供 REST API
func CreateUser() {
	println("ok")
}
`
	path := writeTempGo(t, src)
	if _, err := CleanFile(path, CleanLevelAll); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(path)
	out := string(data)
	if strings.Contains(out, "@ai:") {
		t.Errorf("should remove all @ai, got:\n%s", out)
	}
	if !strings.Contains(out, "@chris") {
		t.Errorf("human marker @chris should be preserved, got:\n%s", out)
	}
	if !strings.Contains(out, "CreateUser 建立使用者") {
		t.Errorf("description should be preserved (human-authored), got:\n%s", out)
	}
}

// Level 2：只移除 @ai:think；doc 區塊整個保留
func TestCleanFile_Level2_OnlyRemovesThink(t *testing.T) {
	src := `package example

// Foo 做事。
// @ai:generated by=x date=2026-06-18
// @ai:purpose ABC
func Foo() {
	//@ai:think intent=先 validate model=x
	//@ai:think special=邊界處理 model=x
	println("ok")
}
`
	path := writeTempGo(t, src)
	if _, err := CleanFile(path, CleanLevelThink); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(path)
	out := string(data)
	if strings.Contains(out, "@ai:think") {
		t.Errorf("@ai:think should be removed, got:\n%s", out)
	}
	if !strings.Contains(out, "@ai:generated") {
		t.Errorf("@ai:generated should be preserved at level 2, got:\n%s", out)
	}
	if !strings.Contains(out, "@ai:purpose") {
		t.Errorf("@ai:purpose should be preserved at level 2, got:\n%s", out)
	}
	if !strings.Contains(out, "Foo 做事") {
		t.Errorf("description should be preserved at level 2, got:\n%s", out)
	}
}

// Level 3：移除 @ai:think + @ai:generated；無 @human → 描述也清
func TestCleanFile_Level3_RemovesThinkAndGenerated_StripsDescIfNoHuman(t *testing.T) {
	src := `package example

// Bar 處理請求。
// @ai:generated by=x date=2026-06-18
// @ai:purpose handle req
// @ai:input none
// @ai:output none
// @ai:sideeffect log
func Bar() {
	//@ai:think intent=略 model=x
	println("ok")
}
`
	path := writeTempGo(t, src)
	if _, err := CleanFile(path, CleanLevelThinkAndGenerated); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(path)
	out := string(data)
	if strings.Contains(out, "@ai:think") {
		t.Errorf("@ai:think should be removed, got:\n%s", out)
	}
	if strings.Contains(out, "@ai:generated") {
		t.Errorf("@ai:generated should be removed at level 3, got:\n%s", out)
	}
	if !strings.Contains(out, "@ai:purpose") {
		t.Errorf("@ai:purpose should be preserved at level 3, got:\n%s", out)
	}
	if !strings.Contains(out, "@ai:input") || !strings.Contains(out, "@ai:output") || !strings.Contains(out, "@ai:sideeffect") {
		t.Errorf("other @ai:* should be preserved at level 3, got:\n%s", out)
	}
	if strings.Contains(out, "Bar 處理請求") {
		t.Errorf("description should be stripped when no human marker, got:\n%s", out)
	}
}

// Level 3 + @human → 描述保留
func TestCleanFile_Level3_KeepsDescriptionWhenHumanMarkerPresent(t *testing.T) {
	src := `package example

// Bar 處理請求。
// @chris
// @ai:generated by=x date=2026-06-18
// @ai:purpose handle req
func Bar() {
	println("ok")
}
`
	path := writeTempGo(t, src)
	if _, err := CleanFile(path, CleanLevelThinkAndGenerated); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(path)
	out := string(data)
	if strings.Contains(out, "@ai:generated") {
		t.Errorf("@ai:generated should be removed at level 3, got:\n%s", out)
	}
	if !strings.Contains(out, "Bar 處理請求") {
		t.Errorf("description should be preserved (human marker present), got:\n%s", out)
	}
	if !strings.Contains(out, "@chris") {
		t.Errorf("@chris should be preserved, got:\n%s", out)
	}
}

// 無 @ai 註釋 → 不修改、不建 .bak
func TestCleanFile_NoChangesWhenNoAITagsPresent(t *testing.T) {
	src := `package example

// Plain 是純人類撰寫的註釋。
func Plain() {
	println("ok")
}
`
	path := writeTempGo(t, src)
	original, _ := os.ReadFile(path)

	report, err := CleanFile(path, CleanLevelAll)
	if err != nil {
		t.Fatal(err)
	}
	if report.Modified {
		t.Error("should not modify file when no @ai tags")
	}
	if report.Removed != 0 {
		t.Errorf("Removed = %d, want 0", report.Removed)
	}

	current, _ := os.ReadFile(path)
	if string(current) != string(original) {
		t.Error("file content should be unchanged")
	}
	// .bak 不應該被建立
	if _, err := os.Stat(path + ".bak"); err == nil {
		t.Error("backup should NOT be created when no changes")
	}
}

// Package doc 與 type doc 也要清
func TestCleanFile_AppliesToPackageAndTypeDoc(t *testing.T) {
	src := `// Package example demo.
//
// @ai:generated by=x date=2026-06-18
package example

// MyType 範例型別。
// @ai:generated by=x date=2026-06-18
// @ai:purpose 範例
type MyType struct {
	Name string
}
`
	path := writeTempGo(t, src)
	if _, err := CleanFile(path, CleanLevelAll); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(path)
	out := string(data)
	if strings.Contains(out, "@ai:") {
		t.Errorf("all @ai should be removed (package + type), got:\n%s", out)
	}
	if !strings.Contains(out, "type MyType struct") {
		t.Errorf("type declaration should remain, got:\n%s", out)
	}
}

// CleanDir 應該遞迴處理子目錄並跳過 vendor/
func TestCleanDir_RecursesAndSkipsVendor(t *testing.T) {
	root := t.TempDir()

	mkfile := func(rel, content string) {
		full := filepath.Join(root, rel)
		os.MkdirAll(filepath.Dir(full), 0755)
		if err := os.WriteFile(full, []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
	}

	withAI := `package x
// Foo
// @ai:generated by=x date=2026-06-18
func Foo() {}
`
	mkfile("a.go", withAI)
	mkfile("sub/b.go", withAI)
	mkfile("vendor/c.go", withAI) // 應被跳過
	mkfile(".hyp/d.go", withAI)   // 應被跳過

	reports, err := CleanDir(root, CleanLevelAll)
	if err != nil {
		t.Fatal(err)
	}

	cleanedSet := map[string]bool{}
	for _, r := range reports {
		if r.Modified {
			rel, _ := filepath.Rel(root, r.Filename)
			cleanedSet[filepath.ToSlash(rel)] = true
		}
	}

	if !cleanedSet["a.go"] {
		t.Error("a.go should be cleaned")
	}
	if !cleanedSet["sub/b.go"] {
		t.Error("sub/b.go should be cleaned")
	}
	if cleanedSet["vendor/c.go"] {
		t.Error("vendor/c.go should be skipped")
	}
	if cleanedSet[".hyp/d.go"] {
		t.Error(".hyp/d.go should be skipped")
	}
}

func TestExtractAITag(t *testing.T) {
	tests := []struct {
		line    string
		wantTag string
		wantOK  bool
	}{
		{"// @ai:generated by=x", "generated", true},
		{"//@ai:think intent=xyz", "think", true},
		{"\t//@ai:think special=abc", "think", true},
		{"// @ai:purpose foo", "purpose", true},
		{"// just a comment", "", false},
		{"// @chris hello", "", false},
		{"//@ai:", "", true}, // 邊界：空 tag 名（但有 @ai: 前綴）
		{"  //  @ai:input foo  ", "input", true},
	}
	for _, tt := range tests {
		got, ok := extractAITag(tt.line)
		if ok != tt.wantOK {
			t.Errorf("extractAITag(%q) ok = %v, want %v", tt.line, ok, tt.wantOK)
		}
		if ok && got != tt.wantTag {
			t.Errorf("extractAITag(%q) = %q, want %q", tt.line, got, tt.wantTag)
		}
	}
}
