// @ai:generated by=claude-opus-4-7 date=2026-06-19
// @ai:purpose 移除 Go 原始檔中的 //@ai 註釋（chkcomment clean 命令的核心邏輯）
package annotation

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// CleanLevel 控制要移除哪些類型的 @ai 註釋
type CleanLevel int

const (
	// CleanLevelAll (= 1) 移除所有 //@ai 註釋（含 doc 區塊與 func body）
	CleanLevelAll CleanLevel = 1

	// CleanLevelThink (= 2) 只移除 func body 內的 //@ai:think
	CleanLevelThink CleanLevel = 2

	// CleanLevelThinkAndGenerated (= 3) 移除 //@ai:think 與 //@ai:generated
	// 其他 @ai:purpose / @ai:input / @ai:output / @ai:sideeffect 等保留
	CleanLevelThinkAndGenerated CleanLevel = 3
)

// ParseCleanLevel 把 1/2/3 轉成 CleanLevel；不合法時回傳 error
func ParseCleanLevel(n int) (CleanLevel, error) {
	switch CleanLevel(n) {
	case CleanLevelAll, CleanLevelThink, CleanLevelThinkAndGenerated:
		return CleanLevel(n), nil
	default:
		return 0, fmt.Errorf("invalid clean level %d (must be 1, 2, or 3)", n)
	}
}

// CleanReport 描述單一檔案的清理結果
type CleanReport struct {
	Filename     string
	Removed      int  // 移除的行數（含 @ai 行與被連帶移除的描述行）
	Modified     bool // 檔案是否實際被修改
	BackupPath   string
}

// CleanFile 清除單一 Go 原始檔的 //@ai 註釋
// 失敗時回傳 error；無變更時 Modified=false 且不寫檔
func CleanFile(filename string, level CleanLevel) (*CleanReport, error) {
	if !strings.HasSuffix(filename, ".go") {
		return nil, fmt.Errorf("not a .go file: %s", filename)
	}

	content, err := os.ReadFile(filename)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", filename, err)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, content, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", filename, err)
	}

	lines := strings.Split(string(content), "\n")
	toRemove := make(map[int]bool) // 0-indexed lines to remove

	// 處理 package doc 與所有 declaration 的 doc / body
	if f.Doc != nil {
		processDocForClean(lines, fset, f.Doc, level, toRemove)
	}

	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			processDocForClean(lines, fset, d.Doc, level, toRemove)
			processBodyForClean(lines, fset, d, level, toRemove)
		case *ast.GenDecl:
			processDocForClean(lines, fset, d.Doc, level, toRemove)
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.ValueSpec:
					processDocForClean(lines, fset, s.Doc, level, toRemove)
				case *ast.TypeSpec:
					processDocForClean(lines, fset, s.Doc, level, toRemove)
				}
			}
		}
	}

	if len(toRemove) == 0 {
		return &CleanReport{Filename: filename, Removed: 0, Modified: false}, nil
	}

	// 寫 .bak（僅在實際要改檔時建立）
	backupPath := filename + ".bak"
	if err := os.WriteFile(backupPath, content, 0644); err != nil {
		return nil, fmt.Errorf("write backup: %w", err)
	}

	// 組成輸出
	out := make([]string, 0, len(lines))
	for i, line := range lines {
		if toRemove[i] {
			continue
		}
		out = append(out, line)
	}

	if err := os.WriteFile(filename, []byte(strings.Join(out, "\n")), 0644); err != nil {
		return nil, fmt.Errorf("write %s: %w", filename, err)
	}

	return &CleanReport{
		Filename:   filename,
		Removed:    len(toRemove),
		Modified:   true,
		BackupPath: backupPath,
	}, nil
}

// CleanDir 遞迴清理 rootDir 下所有 .go 檔
// 自動跳過 vendor / .git / node_modules / .hyp / *_test.go 中的 testdata
func CleanDir(rootDir string, level CleanLevel) ([]CleanReport, error) {
	var reports []CleanReport

	err := filepath.WalkDir(rootDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// 跳過常見不該動的目錄
		if d.IsDir() {
			name := d.Name()
			if name == "vendor" || name == ".git" || name == "node_modules" ||
				name == ".hyp" || name == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		// 只處理 .go，跳過 .bak / 隱藏檔
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		report, cleanErr := CleanFile(path, level)
		if cleanErr != nil {
			// 個別檔案失敗不中斷整批
			reports = append(reports, CleanReport{
				Filename: path,
				Removed:  0,
				Modified: false,
			})
			fmt.Fprintf(os.Stderr, "  ! %s: %v\n", path, cleanErr)
			return nil
		}
		if report.Modified {
			reports = append(reports, *report)
		}
		return nil
	})
	if err != nil {
		return reports, err
	}
	return reports, nil
}

// --- internal helpers ---

// processDocForClean 處理單一 doc comment cgroup：
//  1. 依 level 標記要移除的 @ai 行
//  2. 若移除了 @ai:generated 且無 @<human> 標記，連描述行一起移除
func processDocForClean(lines []string, fset *token.FileSet, doc *ast.CommentGroup, level CleanLevel, toRemove map[int]bool) {
	if doc == nil {
		return
	}

	startLine := fset.Position(doc.Pos()).Line - 1
	endLine := fset.Position(doc.End()).Line - 1
	if startLine < 0 || endLine >= len(lines) {
		return
	}

	// 先檢查整個 doc 文字是否有 human marker（不會被移除）
	docText := strings.Join(lines[startLine:endLine+1], "\n")
	_, hasHuman := HumanAuthor(docText)

	removedGenerated := false
	for i := startLine; i <= endLine; i++ {
		tag, ok := extractAITag(lines[i])
		if !ok {
			continue
		}
		if shouldRemoveByLevel(tag, level) {
			toRemove[i] = true
			if tag == string(Generated) {
				removedGenerated = true
			}
		}
	}

	// 「移除 generated 且無 human marker」→ 連描述一起清
	// 此規則只在「會移除 generated」的 level（1, 3）下會觸發
	if removedGenerated && !hasHuman {
		for i := startLine; i <= endLine; i++ {
			if toRemove[i] {
				continue
			}
			s := strings.TrimSpace(lines[i])
			// 純空白註釋行（`//`）也算描述的一部分
			if s == "" {
				continue // 空行不處理
			}
			if !isAITagLine(lines[i]) {
				toRemove[i] = true
			}
		}
	}
}

// processBodyForClean 移除 func body 內的 //@ai:think 行（所有 level 都會清）
func processBodyForClean(lines []string, fset *token.FileSet, fd *ast.FuncDecl, _ CleanLevel, toRemove map[int]bool) {
	if fd.Body == nil {
		return
	}
	bodyStart := fset.Position(fd.Body.Lbrace).Line - 1
	bodyEnd := fset.Position(fd.Body.Rbrace).Line - 1
	if bodyStart < 0 || bodyEnd >= len(lines) {
		return
	}
	for i := bodyStart + 1; i < bodyEnd; i++ {
		tag, ok := extractAITag(lines[i])
		if ok && tag == "think" {
			toRemove[i] = true
		}
	}
}

// extractAITag 從一行（可能含縮排與 // 前綴）抽出 @ai: 之後的 tag 名稱
// 支援 "// @ai:think" 與 "//@ai:think"（無空格）兩種寫法
func extractAITag(line string) (string, bool) {
	s := strings.TrimSpace(line)
	if !strings.HasPrefix(s, "//") {
		return "", false
	}
	s = strings.TrimSpace(strings.TrimPrefix(s, "//"))
	if !strings.HasPrefix(s, "@ai:") {
		return "", false
	}
	s = s[len("@ai:"):]
	// tag 名稱到第一個空白為止
	for i := 0; i < len(s); i++ {
		if s[i] == ' ' || s[i] == '\t' {
			return s[:i], true
		}
	}
	return s, true
}

// isAITagLine 判斷一行是否為 @ai:* 註釋
func isAITagLine(line string) bool {
	_, ok := extractAITag(line)
	return ok
}

// shouldRemoveByLevel 依 level 決定是否要移除某 @ai 標籤
func shouldRemoveByLevel(tag string, level CleanLevel) bool {
	switch level {
	case CleanLevelAll:
		return true
	case CleanLevelThink:
		return tag == "think"
	case CleanLevelThinkAndGenerated:
		return tag == "think" || tag == string(Generated)
	}
	return false
}

// FormatCleanReports 把 CleanDir 的結果整理成終端報告
func FormatCleanReports(reports []CleanReport) string {
	var sb strings.Builder
	totalLines := 0
	for _, r := range reports {
		if !r.Modified {
			continue
		}
		sb.WriteString(fmt.Sprintf("  ~ %s (removed %d line(s), backup: %s)\n", r.Filename, r.Removed, r.BackupPath))
		totalLines += r.Removed
	}
	sb.WriteString(fmt.Sprintf("\nCleaned %d file(s), removed %d line(s) total.\n", len(reports), totalLines))
	return sb.String()
}
