package annotation

import (
	"fmt"
	"os/exec"
	"strings"
)

// GitCommit git 提交記錄摘要
//
// @ai:generated by=hypgo date=2026-05-25
type GitCommit struct {
	Hash    string
	Author  string
	Date    string
	Subject string
}

// GitContext 檔案與宣告層級的 git 提交歷史
//
// @ai:generated by=hypgo date=2026-05-25
type GitContext struct {
	FileCommits []GitCommit // 整個檔案的提交歷史
	DeclCommits []GitCommit // 特定 func/method 的提交歷史（可能為空）
}

// IsEmpty 回傳 true 若兩個列表均為空或 receiver 為 nil
//
// @ai:generated by=hypgo date=2026-05-25
// @ai:purpose 避免 LLM prompt 附加無意義的空 git 段落
// @ai:input none（receiver 方法）
// @ai:output true = 無任何 git 歷史資訊
// @ai:sideeffect none
func (g *GitContext) IsEmpty() bool {
	if g == nil {
		return true
	}
	return len(g.FileCommits) == 0 && len(g.DeclCommits) == 0
}

// GatherGitContext 收集 filepath 的檔案層級提交歷史，
// 以及 func/method 宣告的行範圍歷史（透過 git log -L）。
// 若目錄不在 git repo 內或 git 不可用，回傳 nil。
//
// @ai:generated by=hypgo date=2026-05-25
// @ai:purpose 為 LLM headline 補充請求提供 git 歷史脈絡，讓 LLM 理解宣告的演進背景
// @ai:input filepath 目標 Go 檔案路徑；declName 宣告的純名稱（無 receiver 前綴）；kind 宣告類型；maxCommits 最多取幾筆
// @ai:output *GitContext，不在 git repo 或無歷史時回傳 nil
// @ai:sideeffect 以 exec.Command 執行 git log（只讀）
func GatherGitContext(filepath, declName, kind string, maxCommits int) *GitContext {
	if maxCommits <= 0 {
		maxCommits = 10
	}

	fileOut, err := runGitLog(
		fmt.Sprintf("-n%d", maxCommits),
		"--format=%H\x1f%an\x1f%ad\x1f%s",
		"--date=short",
		"--",
		filepath,
	)
	if err != nil {
		return nil
	}
	fileCommits := parseGitLog(fileOut)

	gc := &GitContext{FileCommits: fileCommits}

	// 函式/方法層級歷史：git log -L :<name>:<file>
	// 此功能在部分 git 版本或 binary 模式下可能失敗，靜默退回
	if (kind == "func" || kind == "method") && declName != "" {
		lspec := fmt.Sprintf(":%s:%s", declName, filepath)
		declOut, declErr := runGitLog(
			"-L", lspec,
			fmt.Sprintf("-n%d", maxCommits),
			"--no-patch",
			"--format=%H\x1f%an\x1f%ad\x1f%s",
			"--date=short",
		)
		if declErr == nil {
			gc.DeclCommits = parseGitLog(declOut)
		}
	}

	return gc
}

// parseGitLog 解析 git log 的 \x1f 分隔格式輸出，忽略不匹配的行（patch 內容、空行等）
//
// @ai:generated by=hypgo date=2026-05-25
// @ai:purpose 將 git log 原始輸出轉為 GitCommit 切片，對 patch 行具備容錯性
// @ai:input git log stdout 字串（含或不含 diff/patch 內容）
// @ai:output GitCommit 切片（不含無效行）
// @ai:sideeffect none
func parseGitLog(output string) []GitCommit {
	var commits []GitCommit
	for _, line := range strings.Split(output, "\n") {
		parts := strings.SplitN(line, "\x1f", 4)
		if len(parts) != 4 {
			continue
		}
		hash := strings.TrimSpace(parts[0])
		if len(hash) < 7 {
			continue
		}
		commits = append(commits, GitCommit{
			Hash:    hash,
			Author:  strings.TrimSpace(parts[1]),
			Date:    strings.TrimSpace(parts[2]),
			Subject: strings.TrimSpace(parts[3]),
		})
	}
	return commits
}

// runGitLog 執行 git log <args...> 並回傳 stdout。
// 使用 cmd.Output()，stderr 靜默丟棄。
func runGitLog(args ...string) (string, error) {
	cmd := exec.Command("git", append([]string{"log"}, args...)...)
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return string(out), nil
}
