// @ai:generated by=claude-opus-4-7 date=2026-06-21
package annotation

import (
	"os"
	"path/filepath"
	"testing"
)

// llmDebugEnabled 解析優先序：
//   debug_level=none   → 永遠 false（即使環境變數有設）
//   HYP_DEBUG_LLM 環境變數 → true
//   debug_level=debug  → true
//   其他               → false
func TestLLMDebugEnabled_Priority(t *testing.T) {
	// 切到沒有 .hyp/config.yaml 的暫存目錄
	dir := t.TempDir()
	old, _ := os.Getwd()
	defer os.Chdir(old)
	os.Chdir(dir)

	t.Run("no config + no env → false", func(t *testing.T) {
		t.Setenv("HYP_DEBUG_LLM", "")
		if llmDebugEnabled() {
			t.Error("expected false when nothing configured")
		}
	})

	t.Run("env var on → true", func(t *testing.T) {
		t.Setenv("HYP_DEBUG_LLM", "1")
		if !llmDebugEnabled() {
			t.Error("env var should enable")
		}
	})

	t.Run("debug_level=none silences even env var", func(t *testing.T) {
		os.MkdirAll(".hyp", 0755)
		os.WriteFile(filepath.Join(".hyp", "config.yaml"),
			[]byte("language: en\ndebug_level: none\nenvironment: local\n"), 0644)
		defer os.RemoveAll(".hyp")

		t.Setenv("HYP_DEBUG_LLM", "1")
		if llmDebugEnabled() {
			t.Error("debug_level=none should silence even when env var set")
		}
	})

	t.Run("debug_level=debug enables without env var", func(t *testing.T) {
		os.MkdirAll(".hyp", 0755)
		os.WriteFile(filepath.Join(".hyp", "config.yaml"),
			[]byte("language: en\ndebug_level: debug\nenvironment: local\n"), 0644)
		defer os.RemoveAll(".hyp")

		t.Setenv("HYP_DEBUG_LLM", "")
		if !llmDebugEnabled() {
			t.Error("debug_level=debug should enable debug output")
		}
	})

	t.Run("debug_level=warning + no env → false", func(t *testing.T) {
		os.MkdirAll(".hyp", 0755)
		os.WriteFile(filepath.Join(".hyp", "config.yaml"),
			[]byte("language: en\ndebug_level: warning\nenvironment: local\n"), 0644)
		defer os.RemoveAll(".hyp")

		t.Setenv("HYP_DEBUG_LLM", "")
		if llmDebugEnabled() {
			t.Error("warning level should NOT enable debug output without env var")
		}
	})
}
