package annotation

import (
	"context"
	"fmt"

	"github.com/maoxiaoyue/hypgo/pkg/config"
)

// SuggestRequest 描述一個待補註解的 Go 宣告，供 Suggester 產生 doc 與 @ai 標註
type SuggestRequest struct {
	Kind     string   // "package", "type", "func", "method", "const", "var"
	Name     string   // "Create" 或 "UserController.Delete"
	Receiver string   // method receiver type；func 為空
	Params   []string // 參數名稱列表
	PkgName  string   // 所屬 package 名稱
	File     string   // 檔案路徑
}

// Suggestion 為 Suggester 的回傳值
type Suggestion struct {
	Doc         string       // 一行 godoc 風格說明（不含 // 前綴）
	Annotations []Annotation // 附加的 @ai 標註
}

// Suggester 抽象出「為宣告產生 doc 與 @ai 標註」的能力
type Suggester interface {
	Suggest(ctx context.Context, req SuggestRequest) (Suggestion, error)
	// ProviderName 回傳此 Suggester 的提供者識別字串，
	// 用於填入 @ai:generated by=<provider>。
	// 例：claude / openai / gemini / ollama / heuristic
	ProviderName() string
}

// NewSuggester 依 LLMConfig.Mode 建立對應實作
//
// mode=none 回傳 HeuristicSuggester；
// mode=ollama / api 回傳 LLMSuggester，但若 LLM 呼叫失敗會自動 fallback。
func NewSuggester(cfg *config.LLMConfig) (Suggester, error) {
	if cfg == nil || cfg.Mode == "" || cfg.Mode == config.LLMModeNone {
		return NewHeuristicSuggester(), nil
	}
	llm, err := NewLLMSuggester(cfg)
	if err != nil {
		return nil, fmt.Errorf("init llm suggester: %w", err)
	}
	return &fallbackSuggester{primary: llm, fallback: NewHeuristicSuggester()}, nil
}

// fallbackSuggester 在 primary 失敗時退回 fallback，使 chkcomment --fix 不致整體失敗
type fallbackSuggester struct {
	primary  Suggester
	fallback Suggester
}

func (s *fallbackSuggester) Suggest(ctx context.Context, req SuggestRequest) (Suggestion, error) {
	if s.primary != nil {
		if out, err := s.primary.Suggest(ctx, req); err == nil {
			return out, nil
		}
	}
	return s.fallback.Suggest(ctx, req)
}

// ProviderName 偏好 primary 的名稱，fallback 時仍可標示真實使用的 provider
func (s *fallbackSuggester) ProviderName() string {
	if s.primary != nil {
		return s.primary.ProviderName()
	}
	if s.fallback != nil {
		return s.fallback.ProviderName()
	}
	return "unknown"
}
