package annotation

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/maoxiaoyue/hypgo/pkg/config"
)

// --- heuristic intent ---

func TestHeuristicIntent(t *testing.T) {
	tests := []struct {
		name string
		want string
	}{
		{"CreateUser", "建立資源"},
		{"NewService", "建立資源"},
		{"UpdateOrder", "更新資源"},
		{"SaveConfig", "更新資源"},
		{"DeleteItem", "刪除資源"},
		{"RemoveCache", "刪除資源"},
		{"GetUser", "讀取資料"},
		{"FindByID", "讀取資料"},
		{"ListOrders", "列表查詢"},
		{"SearchProducts", "列表查詢"},
		{"InitDB", "初始化設定"},
		{"HandleRequest", "處理請求"},
		{"ValidateInput", "驗證輸入"},
		{"ParseJSON", "解析資料"},
		{"FormatOutput", "格式化輸出"},
		{"RegisterRoutes", "註冊元件"},
		{"StartServer", "啟動服務"},
		{"StopWorker", "停止或釋放資源"},
		{"DoSomething", "TODO: 說明此函式的意圖"},
	}
	for _, tt := range tests {
		got := heuristicIntent(tt.name)
		if got != tt.want {
			t.Errorf("heuristicIntent(%q) = %q, want %q", tt.name, got, tt.want)
		}
	}
}

// --- parseThinkSuggestion ---

func TestParseThinkSuggestion(t *testing.T) {
	raw := `{"intent":"處理使用者建立流程","special":"用 upsert 避免併發衝突"}`
	got := parseThinkSuggestion(raw)
	if got.Intent != "處理使用者建立流程" {
		t.Errorf("intent = %q", got.Intent)
	}
	if got.Special != "用 upsert 避免併發衝突" {
		t.Errorf("special = %q", got.Special)
	}
}

func TestParseThinkSuggestion_Empty(t *testing.T) {
	got := parseThinkSuggestion("not json at all")
	if got.Intent != "" || got.Special != "" {
		t.Errorf("expected empty, got %+v", got)
	}
}

func TestParseThinkSuggestion_NoSpecial(t *testing.T) {
	raw := `{"intent":"讀取使用者","special":""}`
	got := parseThinkSuggestion(raw)
	if got.Intent != "讀取使用者" {
		t.Errorf("intent = %q", got.Intent)
	}
	if got.Special != "" {
		t.Errorf("special should be empty, got %q", got.Special)
	}
}

// --- resolveModelName ---

func TestResolveModelName_Nil(t *testing.T) {
	if got := resolveModelName(nil); got != "unknown" {
		t.Errorf("got %q, want unknown", got)
	}
}

// --- NewThinkSuggester rejects mode=none ---

func TestNewThinkSuggester_RejectsNone(t *testing.T) {
	cases := []struct {
		name string
		cfg  *config.LLMConfig
	}{
		{"nil config", nil},
		{"empty mode", &config.LLMConfig{}},
		{"mode=none", &config.LLMConfig{Mode: config.LLMModeNone}},
	}
	for _, tt := range cases {
		s, err := NewThinkSuggester(tt.cfg)
		if err == nil {
			t.Errorf("%s: expected error, got suggester %v", tt.name, s)
		}
		if s != nil {
			t.Errorf("%s: suggester should be nil on error", tt.name)
		}
	}
}

// --- FixThinkFile ---

func TestFixThinkFile_Heuristic(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "fix.go")
	src := `package example

// CreateUser 建立使用者
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func CreateUser() {
	println("no think here")
}

// GetUser 讀取使用者
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func GetUser() {
	println("also missing")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Missing) != 2 {
		t.Fatalf("missing = %d, want 2", len(report.Missing))
	}

	s := &heuristicThinkSuggester{}
	fixed, err := FixThinkFile(context.Background(), path, report, s)
	if err != nil {
		t.Fatal(err)
	}
	if fixed != 2 {
		t.Errorf("fixed = %d, want 2", fixed)
	}

	data, _ := os.ReadFile(path)
	content := string(data)

	if !strings.Contains(content, "//@ai:think intent=建立資源 model=heuristic") {
		t.Error("missing CreateUser @ai:think")
	}
	if !strings.Contains(content, "//@ai:think intent=讀取資料 model=heuristic") {
		t.Error("missing GetUser @ai:think")
	}

	// Verify backup exists
	if _, err := os.Stat(path + ".bak"); err != nil {
		t.Error("backup file not created")
	}
}

func TestFixThinkFile_PreservesExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "existing.go")
	src := `package example

// Good 已有 think
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func Good() {
	//@ai:think intent=已有意圖 model=claude-opus-4-6
	println("ok")
}

// Bad 缺 think
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func Bad() {
	println("missing")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, _ := CheckThink(path)
	if len(report.Missing) != 1 {
		t.Fatalf("missing = %d, want 1", len(report.Missing))
	}

	s := &heuristicThinkSuggester{}
	fixed, err := FixThinkFile(context.Background(), path, report, s)
	if err != nil {
		t.Fatal(err)
	}
	if fixed != 1 {
		t.Errorf("fixed = %d, want 1", fixed)
	}

	data, _ := os.ReadFile(path)
	content := string(data)

	// Good's existing think should still be there
	if !strings.Contains(content, "intent=已有意圖 model=claude-opus-4-6") {
		t.Error("existing @ai:think was modified")
	}
}

func TestFixThinkFile_NoMissing(t *testing.T) {
	report := &ThinkReport{Filename: "test.go", Scanned: 1}
	fixed, err := FixThinkFile(context.Background(), "test.go", report, &heuristicThinkSuggester{})
	if err != nil {
		t.Fatal(err)
	}
	if fixed != 0 {
		t.Errorf("fixed = %d, want 0", fixed)
	}
}

func TestFixThinkFile_Method(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "method.go")
	src := `package example

type Svc struct{}

// Delete 刪除
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func (s *Svc) Delete() {
	println("method missing think")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, _ := CheckThink(path)
	s := &heuristicThinkSuggester{}
	fixed, err := FixThinkFile(context.Background(), path, report, s)
	if err != nil {
		t.Fatal(err)
	}
	if fixed != 1 {
		t.Errorf("fixed = %d, want 1", fixed)
	}

	data, _ := os.ReadFile(path)
	content := string(data)
	if !strings.Contains(content, "//@ai:think intent=刪除資源 model=heuristic") {
		t.Errorf("missing method @ai:think in:\n%s", content)
	}
}

func TestFixThinkFile_Indentation(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "indent.go")
	src := `package example

// Run 執行
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func Run() {
    println("4-space indent")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, _ := CheckThink(path)
	s := &heuristicThinkSuggester{}
	FixThinkFile(context.Background(), path, report, s)

	data, _ := os.ReadFile(path)
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		if strings.Contains(line, "@ai:think") {
			if !strings.HasPrefix(line, "    //@ai:think") {
				t.Errorf("indentation mismatch: %q", line)
			}
			break
		}
	}
}

func TestFixThinkFile_VerifyClean(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "verify.go")
	src := `package example

// Do 處理
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func Do() {
	println("missing")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, _ := CheckThink(path)
	s := &heuristicThinkSuggester{}
	FixThinkFile(context.Background(), path, report, s)

	// After fix, CheckThink should find zero missing
	report2, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(report2.Missing) != 0 {
		t.Errorf("after fix, still %d missing", len(report2.Missing))
	}
}

// --- fallback ---

type failingThinkSuggester struct{}

func (f *failingThinkSuggester) SuggestThink(_ context.Context, _ ThinkSuggestRequest) (ThinkSuggestion, error) {
	return ThinkSuggestion{}, fmt.Errorf("LLM unavailable")
}
func (f *failingThinkSuggester) ModelName() string { return "failing" }

func TestFallbackThinkSuggester(t *testing.T) {
	fb := &fallbackThinkSuggester{
		primary:  &failingThinkSuggester{},
		fallback: &heuristicThinkSuggester{},
	}

	got, err := fb.SuggestThink(context.Background(), ThinkSuggestRequest{FuncName: "CreateUser", Kind: "func"})
	if err != nil {
		t.Fatal(err)
	}
	if got.Intent != "建立資源" {
		t.Errorf("fallback intent = %q, want 建立資源", got.Intent)
	}
	if fb.ModelName() != "failing" {
		t.Errorf("model name should prefer primary: %q", fb.ModelName())
	}
}
