// @ai:generated by=claude-opus-4-6 date=2026-06-18
// @ai:purpose 為缺少 //@ai:think 的 AI 生成函式自動補上意圖註解（LLM 或啟發式）
package annotation

import (
	"context"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"

	"github.com/maoxiaoyue/hypgo/pkg/config"
)

// ThinkSuggestion 為 ThinkSuggester 的回傳值
type ThinkSuggestion struct {
	Intent  string
	Special string
}

// ThinkSuggestRequest 描述一個待補 @ai:think 的函式
type ThinkSuggestRequest struct {
	FuncName string
	Kind     string // "func" 或 "method"
	Receiver string
	Source   string // 函式原始碼片段（含簽名，至多 30 行）
	File     string
}

// ThinkSuggester 產生 @ai:think 內容
type ThinkSuggester interface {
	SuggestThink(ctx context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error)
	ModelName() string
}

// NewThinkSuggester 依 LLMConfig 建立 ThinkSuggester。
// mode=none 或無設定時回傳 error，呼叫端應改為警告使用者需要 LLM 支援。
func NewThinkSuggester(cfg *config.LLMConfig) (ThinkSuggester, error) {
	if cfg == nil || cfg.Mode == "" || cfg.Mode == config.LLMModeNone {
		return nil, fmt.Errorf("fixintent requires LLM support (mode=ollama or mode=api); current mode is none")
	}
	llm, err := NewLLMSuggester(cfg)
	if err != nil {
		return nil, fmt.Errorf("init llm think suggester: %w", err)
	}
	return &fallbackThinkSuggester{
		primary:  &llmThinkSuggester{llm: llm, modelName: resolveModelName(cfg)},
		fallback: &heuristicThinkSuggester{},
	}, nil
}

func resolveModelName(cfg *config.LLMConfig) string {
	if cfg == nil {
		return "unknown"
	}
	switch cfg.Mode {
	case config.LLMModeOllama:
		if cfg.Ollama.Model != "" {
			return cfg.Ollama.Model
		}
		return "ollama"
	case config.LLMModeAPI:
		if cfg.API.Model != "" {
			return cfg.API.Model
		}
		if cfg.API.Provider != "" {
			return cfg.API.Provider
		}
		return "api"
	}
	return "unknown"
}

// --- fallback ---

type fallbackThinkSuggester struct {
	primary  ThinkSuggester
	fallback ThinkSuggester
}

func (f *fallbackThinkSuggester) SuggestThink(ctx context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error) {
	if f.primary != nil {
		if out, err := f.primary.SuggestThink(ctx, req); err == nil {
			return out, nil
		}
	}
	return f.fallback.SuggestThink(ctx, req)
}

func (f *fallbackThinkSuggester) ModelName() string {
	if f.primary != nil {
		return f.primary.ModelName()
	}
	return f.fallback.ModelName()
}

// --- heuristic ---

type heuristicThinkSuggester struct{}

func (h *heuristicThinkSuggester) ModelName() string { return "heuristic" }

func (h *heuristicThinkSuggester) SuggestThink(_ context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error) {
	return ThinkSuggestion{Intent: heuristicIntent(req.FuncName)}, nil
}

func heuristicIntent(name string) string {
	lower := strings.ToLower(baseName(name))
	switch {
	case strings.HasPrefix(lower, "create"), strings.HasPrefix(lower, "new"):
		return "建立資源"
	case strings.HasPrefix(lower, "update"), strings.HasPrefix(lower, "save"):
		return "更新資源"
	case strings.HasPrefix(lower, "delete"), strings.HasPrefix(lower, "remove"):
		return "刪除資源"
	case strings.HasPrefix(lower, "get"), strings.HasPrefix(lower, "find"), strings.HasPrefix(lower, "read"):
		return "讀取資料"
	case strings.HasPrefix(lower, "list"), strings.HasPrefix(lower, "search"), strings.HasPrefix(lower, "index"):
		return "列表查詢"
	case strings.HasPrefix(lower, "init"), strings.HasPrefix(lower, "setup"):
		return "初始化設定"
	case strings.HasPrefix(lower, "handle"):
		return "處理請求"
	case strings.HasPrefix(lower, "validate"), strings.HasPrefix(lower, "check"):
		return "驗證輸入"
	case strings.HasPrefix(lower, "parse"):
		return "解析資料"
	case strings.HasPrefix(lower, "format"), strings.HasPrefix(lower, "render"):
		return "格式化輸出"
	case strings.HasPrefix(lower, "register"):
		return "註冊元件"
	case strings.HasPrefix(lower, "start"), strings.HasPrefix(lower, "run"):
		return "啟動服務"
	case strings.HasPrefix(lower, "stop"), strings.HasPrefix(lower, "close"), strings.HasPrefix(lower, "shutdown"):
		return "停止或釋放資源"
	case strings.HasPrefix(lower, "test"):
		return "測試驗證"
	default:
		return "TODO: 說明此函式的意圖"
	}
}

// --- LLM ---

type llmThinkSuggester struct {
	llm       *LLMSuggester
	modelName string
}

func (l *llmThinkSuggester) ModelName() string { return l.modelName }

func (l *llmThinkSuggester) SuggestThink(ctx context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error) {
	prompt := buildThinkPrompt(req)
	var raw string
	var err error
	switch l.llm.cfg.Mode {
	case config.LLMModeOllama:
		raw, err = l.llm.callOllama(ctx, prompt)
	case config.LLMModeAPI:
		raw, err = l.llm.callAPI(ctx, prompt)
	default:
		return ThinkSuggestion{}, fmt.Errorf("unsupported mode %q", l.llm.cfg.Mode)
	}
	if err != nil {
		return ThinkSuggestion{}, err
	}
	return parseThinkSuggestion(raw), nil
}

const thinkSystemPrompt = `你是 Go 程式碼意圖分析助手。分析以下函式，產出：
1) intent：此函式的設計意圖（為什麼需要這個函式、它解決什麼問題），一行簡潔說明
2) special：函式內的特殊設計選擇、邊界處理、workaround（如有），沒有則留空字串

請只以 JSON 物件回覆：
{"intent":"...","special":"..."}
不要附加任何其他文字。`

func buildThinkPrompt(req ThinkSuggestRequest) string {
	var sb strings.Builder
	sb.WriteString(thinkSystemPrompt)
	sb.WriteString("\n\n函式資訊：\n")
	fmt.Fprintf(&sb, "Name=%s\n", req.FuncName)
	fmt.Fprintf(&sb, "Kind=%s\n", req.Kind)
	if req.Receiver != "" {
		fmt.Fprintf(&sb, "Receiver=%s\n", req.Receiver)
	}
	if req.Source != "" {
		sb.WriteString("\n原始碼：\n```go\n")
		sb.WriteString(req.Source)
		sb.WriteString("\n```\n")
	}
	return sb.String()
}

type thinkPayload struct {
	Intent  string `json:"intent"`
	Special string `json:"special"`
}

func parseThinkSuggestion(raw string) ThinkSuggestion {
	jsonText := jsonObjectRE.FindString(raw)
	if jsonText == "" {
		return ThinkSuggestion{}
	}
	var p thinkPayload
	if err := json.Unmarshal([]byte(jsonText), &p); err != nil {
		return ThinkSuggestion{}
	}
	return ThinkSuggestion{
		Intent:  sanitize(p.Intent, maxDocRunes),
		Special: sanitize(p.Special, maxDocRunes),
	}
}

// FixThinkFile 在缺少 //@ai:think 的函式體中插入意圖註解。
// 回傳修補的函式數量。修改前會建立 .bak 備份。
func FixThinkFile(ctx context.Context, filename string, report *ThinkReport, s ThinkSuggester) (int, error) {
	if report == nil || len(report.Missing) == 0 {
		return 0, nil
	}

	content, err := os.ReadFile(filename)
	if err != nil {
		return 0, fmt.Errorf("read: %w", err)
	}

	backupPath := filename + ".bak"
	if err := os.WriteFile(backupPath, content, 0644); err != nil {
		return 0, fmt.Errorf("backup: %w", err)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, content, parser.ParseComments)
	if err != nil {
		return 0, fmt.Errorf("parse: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	modelName := s.ModelName()

	type insertOp struct {
		braceLineIdx int
		thinkLines   []string
	}
	var ops []insertOp

	missingSet := make(map[int]ThinkResult)
	for _, m := range report.Missing {
		missingSet[m.Line] = m
	}

	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Body == nil {
			continue
		}

		declLine := fset.Position(fd.Pos()).Line
		m, ok := missingSet[declLine]
		if !ok {
			continue
		}

		braceIdx := fset.Position(fd.Body.Lbrace).Line - 1

		bodyEnd := fset.Position(fd.Body.Rbrace).Line
		srcStart := declLine - 1
		srcEnd := bodyEnd
		if srcEnd-srcStart > 30 {
			srcEnd = srcStart + 30
		}
		if srcEnd > len(lines) {
			srcEnd = len(lines)
		}
		funcSource := strings.Join(lines[srcStart:srcEnd], "\n")

		recv := ""
		if fd.Recv != nil && len(fd.Recv.List) > 0 {
			recv = exprToString(fd.Recv.List[0].Type)
		}

		suggestion, sugErr := s.SuggestThink(ctx, ThinkSuggestRequest{
			FuncName: baseName(m.Name),
			Kind:     m.Kind,
			Receiver: recv,
			Source:   funcSource,
			File:     filename,
		})
		if sugErr != nil {
			suggestion = ThinkSuggestion{Intent: "TODO: 說明此函式的意圖"}
		}

		var thinkLines []string
		if suggestion.Intent != "" {
			thinkLines = append(thinkLines, fmt.Sprintf("//@ai:think intent=%s model=%s", suggestion.Intent, modelName))
		}
		if suggestion.Special != "" {
			thinkLines = append(thinkLines, fmt.Sprintf("//@ai:think special=%s model=%s", suggestion.Special, modelName))
		}
		if len(thinkLines) == 0 {
			thinkLines = append(thinkLines, fmt.Sprintf("//@ai:think intent=TODO: 說明此函式的意圖 model=%s", modelName))
		}

		ops = append(ops, insertOp{braceLineIdx: braceIdx, thinkLines: thinkLines})
	}

	sort.Slice(ops, func(i, j int) bool {
		return ops[i].braceLineIdx > ops[j].braceLineIdx
	})

	count := 0
	for _, op := range ops {
		insertAt := op.braceLineIdx + 1
		if insertAt > len(lines) {
			insertAt = len(lines)
		}

		indent := "\t"
		if insertAt < len(lines) {
			nextLine := lines[insertAt]
			trimmed := strings.TrimLeft(nextLine, " \t")
			if trimmed != "" && trimmed != "}" {
				indent = nextLine[:len(nextLine)-len(trimmed)]
			}
		}

		newLines := make([]string, len(op.thinkLines))
		for i, tl := range op.thinkLines {
			newLines[i] = indent + tl
		}

		before := append([]string{}, lines[:insertAt]...)
		after := append([]string{}, lines[insertAt:]...)
		lines = append(before, append(newLines, after...)...)
		count++
	}

	if count == 0 {
		return 0, nil
	}

	return count, os.WriteFile(filename, []byte(strings.Join(lines, "\n")), 0644)
}
