// @ai:generated by=claude-opus-4-6 date=2026-06-18
// @ai:purpose 為缺少 //@ai:think 的 AI 生成函式自動補上意圖註解（LLM 或啟發式）
package annotation

import (
	"context"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"

	"github.com/maoxiaoyue/hypgo/pkg/config"
)

// ThinkSuggestion 為 ThinkSuggester 的回傳值
type ThinkSuggestion struct {
	Intent  string
	Special string
}

// ThinkSuggestRequest 描述一個待補 @ai:think 的函式
type ThinkSuggestRequest struct {
	FuncName string
	Kind     string // "func" 或 "method"
	Receiver string
	Source   string // 函式原始碼片段（含簽名，至多 30 行）
	File     string

	// Retroactive 為 true 時 (v0.8.11+)，prompt 切換為「事後反推」模式：
	// 分析函式現在實際在做什麼，而不是「設計時為什麼要寫它」。
	// 由 chkcomment --fixintent --all 觸發；輸出的 @ai:think 會帶 retroactive=true 標籤。
	Retroactive bool
}

// ThinkSuggester 產生 @ai:think 內容
type ThinkSuggester interface {
	SuggestThink(ctx context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error)
	ModelName() string
}

// NewThinkSuggester 依 LLMConfig 建立 ThinkSuggester。
// mode=none 或無設定時回傳 error，呼叫端應改為警告使用者需要 LLM 支援。
func NewThinkSuggester(cfg *config.LLMConfig) (ThinkSuggester, error) {
	if cfg == nil || cfg.Mode == "" || cfg.Mode == config.LLMModeNone {
		return nil, fmt.Errorf("fixintent requires LLM support (mode=ollama or mode=api); current mode is none")
	}
	llm, err := NewLLMSuggester(cfg)
	if err != nil {
		return nil, fmt.Errorf("init llm think suggester: %w", err)
	}
	return &fallbackThinkSuggester{
		primary:  &llmThinkSuggester{llm: llm, modelName: resolveModelName(cfg)},
		fallback: &heuristicThinkSuggester{},
	}, nil
}

func resolveModelName(cfg *config.LLMConfig) string {
	if cfg == nil {
		return "unknown"
	}
	switch cfg.Mode {
	case config.LLMModeOllama:
		if cfg.Ollama.Model != "" {
			return cfg.Ollama.Model
		}
		return "ollama"
	case config.LLMModeAPI:
		if cfg.API.Model != "" {
			return cfg.API.Model
		}
		if cfg.API.Provider != "" {
			return cfg.API.Provider
		}
		return "api"
	}
	return "unknown"
}

// --- fallback ---

type fallbackThinkSuggester struct {
	primary  ThinkSuggester
	fallback ThinkSuggester
}

func (f *fallbackThinkSuggester) SuggestThink(ctx context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error) {
	if f.primary != nil {
		out, err := f.primary.SuggestThink(ctx, req)
		// 「沒 error 但回傳空」也視為失敗 → 走 fallback
		// （某些 LLM 在 prompt 過長或不熟悉的格式時會回傳空字串而非 error）
		if err == nil && (out.Intent != "" || out.Special != "") {
			return out, nil
		}
	}
	return f.fallback.SuggestThink(ctx, req)
}

func (f *fallbackThinkSuggester) ModelName() string {
	if f.primary != nil {
		return f.primary.ModelName()
	}
	return f.fallback.ModelName()
}

// --- heuristic ---

type heuristicThinkSuggester struct{}

func (h *heuristicThinkSuggester) ModelName() string { return "heuristic" }

func (h *heuristicThinkSuggester) SuggestThink(_ context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error) {
	return ThinkSuggestion{Intent: heuristicIntentFor(req.FuncName, req.Retroactive)}, nil
}

// heuristicIntentFor 依函式名前綴推斷一句意圖。
// retroactive=true 時改用「推測」開頭，誠實標示這是 heuristic 而非 LLM 推導結果。
func heuristicIntentFor(name string, retroactive bool) string {
	intent := heuristicIntent(name)
	defaultPrefix := "TODO: "
	if !strings.HasPrefix(intent, defaultPrefix) && retroactive {
		return "推測：" + intent
	}
	if strings.HasPrefix(intent, defaultPrefix) && retroactive {
		return "TODO: 反推此函式的實際職責（heuristic 無法依名稱判定）"
	}
	return intent
}

func heuristicIntent(name string) string {
	lower := strings.ToLower(baseName(name))
	switch {
	case strings.HasPrefix(lower, "create"), strings.HasPrefix(lower, "new"):
		return "建立資源"
	case strings.HasPrefix(lower, "update"), strings.HasPrefix(lower, "save"):
		return "更新資源"
	case strings.HasPrefix(lower, "delete"), strings.HasPrefix(lower, "remove"):
		return "刪除資源"
	case strings.HasPrefix(lower, "get"), strings.HasPrefix(lower, "find"), strings.HasPrefix(lower, "read"):
		return "讀取資料"
	case strings.HasPrefix(lower, "list"), strings.HasPrefix(lower, "search"), strings.HasPrefix(lower, "index"):
		return "列表查詢"
	case strings.HasPrefix(lower, "init"), strings.HasPrefix(lower, "setup"):
		return "初始化設定"
	case strings.HasPrefix(lower, "handle"):
		return "處理請求"
	case strings.HasPrefix(lower, "validate"), strings.HasPrefix(lower, "check"):
		return "驗證輸入"
	case strings.HasPrefix(lower, "parse"):
		return "解析資料"
	case strings.HasPrefix(lower, "format"), strings.HasPrefix(lower, "render"):
		return "格式化輸出"
	case strings.HasPrefix(lower, "register"):
		return "註冊元件"
	case strings.HasPrefix(lower, "start"), strings.HasPrefix(lower, "run"):
		return "啟動服務"
	case strings.HasPrefix(lower, "stop"), strings.HasPrefix(lower, "close"), strings.HasPrefix(lower, "shutdown"):
		return "停止或釋放資源"
	case strings.HasPrefix(lower, "test"):
		return "測試驗證"
	default:
		return "TODO: 說明此函式的意圖"
	}
}

// --- LLM ---

type llmThinkSuggester struct {
	llm       *LLMSuggester
	modelName string
}

func (l *llmThinkSuggester) ModelName() string { return l.modelName }

func (l *llmThinkSuggester) SuggestThink(ctx context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error) {
	debug := llmDebugEnabled()
	prompt := buildThinkPrompt(req)
	if debug {
		fmt.Fprintf(os.Stderr, "[hyp llm] calling LLM for %s (prompt len=%d)...\n", req.FuncName, len(prompt))
	}
	var raw string
	var err error
	switch l.llm.cfg.Mode {
	case config.LLMModeOllama:
		raw, err = l.llm.callOllama(ctx, prompt)
	case config.LLMModeAPI:
		raw, err = l.llm.callAPI(ctx, prompt)
	default:
		return ThinkSuggestion{}, fmt.Errorf("unsupported mode %q", l.llm.cfg.Mode)
	}
	if err != nil {
		if debug {
			fmt.Fprintf(os.Stderr, "[hyp llm] %s FAILED: %v\n", req.FuncName, err)
		}
		return ThinkSuggestion{}, err
	}
	return parseThinkSuggestion(raw), nil
}

const thinkSystemPrompt = `你是 Go 程式碼意圖分析助手。分析以下函式，產出：
1) intent：此函式的設計意圖（為什麼需要這個函式、它解決什麼問題），一行簡潔說明
2) special：函式內的特殊設計選擇、邊界處理、workaround（如有），沒有則留空字串

請只以 JSON 物件回覆：
{"intent":"...","special":"..."}
不要附加任何其他文字。`

// thinkRetroactiveSystemPrompt 用於 --all 模式：事後反推、不假定設計意圖
const thinkRetroactiveSystemPrompt = `你是 Go 程式碼事後分析助手。讀完以下函式後，產出對「它現在實際在做什麼、為什麼這樣寫」的反推說明（注意：你並不是原作者，這是事後分析）：
1) intent：函式現在實際的職責（用陳述語氣，不要假裝這是設計時的意圖）。一行簡潔說明。
2) special：函式內值得留意的技巧、邊界處理、workaround、或可疑寫法（如有），沒有則留空字串。

請只以 JSON 物件回覆：
{"intent":"...","special":"..."}
不要附加任何其他文字。`

func buildThinkPrompt(req ThinkSuggestRequest) string {
	var sb strings.Builder
	if req.Retroactive {
		sb.WriteString(thinkRetroactiveSystemPrompt)
	} else {
		sb.WriteString(thinkSystemPrompt)
	}
	sb.WriteString("\n\n函式資訊：\n")
	fmt.Fprintf(&sb, "Name=%s\n", req.FuncName)
	fmt.Fprintf(&sb, "Kind=%s\n", req.Kind)
	if req.Receiver != "" {
		fmt.Fprintf(&sb, "Receiver=%s\n", req.Receiver)
	}
	if req.Source != "" {
		sb.WriteString("\n原始碼：\n```go\n")
		sb.WriteString(req.Source)
		sb.WriteString("\n```\n")
	}
	return sb.String()
}

type thinkPayload struct {
	Intent  string `json:"intent"`
	Special string `json:"special"`
}

func parseThinkSuggestion(raw string) ThinkSuggestion {
	debug := llmDebugEnabled()
	if debug {
		fmt.Fprintf(os.Stderr, "[hyp llm] raw len=%d: %.300s\n", len(raw), raw)
	}
	jsonText := jsonObjectRE.FindString(raw)
	if jsonText == "" {
		if debug {
			fmt.Fprintln(os.Stderr, "[hyp llm] no JSON object in response")
		}
		return ThinkSuggestion{}
	}
	var p thinkPayload
	if err := json.Unmarshal([]byte(jsonText), &p); err != nil {
		if debug {
			fmt.Fprintf(os.Stderr, "[hyp llm] JSON unmarshal failed: %v\n", err)
		}
		return ThinkSuggestion{}
	}
	intent := sanitize(p.Intent, maxDocRunes)
	special := sanitize(p.Special, maxDocRunes)
	// 編碼健全性檢查：若 LLM 輸出含 U+FFFD（Unicode 替代字元，編碼錯誤的明確信號），
	// 或亂碼率過高（私用區或代理區字元比例過半），整個回傳視為失敗 → 走 fallback。
	// 某些本地推論伺服器（如 llama.cpp）在中文回應時偶發 mojibake。
	if !looksWellFormed(intent) || !looksWellFormed(special) {
		if debug {
			fmt.Fprintf(os.Stderr, "[hyp llm] mojibake rejected: intent=%q\n", intent)
		}
		return ThinkSuggestion{}
	}
	return ThinkSuggestion{Intent: intent, Special: special}
}

// looksWellFormed 判斷字串是否看起來編碼健全：
// 不含 Unicode 替代字元（U+FFFD）；亂碼字元（高位面非 CJK 範圍）比例不過半。
func looksWellFormed(s string) bool {
	if s == "" {
		return true
	}
	garbled := 0
	total := 0
	for _, r := range s {
		total++
		// U+FFFD 直接判定亂碼
		if r == '�' {
			return false
		}
		// 大量 surrogate / private-use / unassigned 範圍 → 編碼錯誤的跡象
		if (r >= 0xE000 && r <= 0xF8FF) || (r >= 0xD800 && r <= 0xDFFF) {
			garbled++
		}
	}
	return total == 0 || garbled*2 < total
}

// llmDebugEnabled 回傳是否啟用 [hyp llm] 除錯輸出。
// 優先序：
//  1. .hyp/config.yaml 的 debug_level=none → 永遠靜默（即使環境變數有設）
//  2. HYP_DEBUG_LLM 環境變數有設 → 開啟
//  3. .hyp/config.yaml 存在且 debug_level=debug → 開啟
//  4. 其他（含「沒有 config 檔」）→ 關閉（保留 v0.8.11 之前的行為）
func llmDebugEnabled() bool {
	const cfgPath = ".hyp/config.yaml"
	cfg, _ := config.LoadHypConfig(cfgPath)
	if cfg.IsSilent() {
		return false
	}
	if os.Getenv("HYP_DEBUG_LLM") != "" {
		return true
	}
	if _, err := os.Stat(cfgPath); err == nil {
		return cfg.IsDebug()
	}
	return false
}

// fallbackIntent 在 LLM 失敗時的最後備援文字
func fallbackIntent(retroactive bool) string {
	if retroactive {
		return "TODO: 反推此函式的實際職責"
	}
	return "TODO: 說明此函式的意圖"
}

// FixThinkOpts 控制 FixThinkFileWithOpts 的行為（v0.8.11+）
type FixThinkOpts struct {
	// Retroactive 為 true 時，LLM prompt 切換為「事後反推」模式，
	// 且每行 //@ai:think 會附帶 retroactive=true 標籤，
	// 誠實標示「這是事後分析，不是設計時意圖」。
	Retroactive bool
}

// FixThinkFile 在缺少 //@ai:think 的函式體中插入意圖註解。
// 回傳修補的函式數量。修改前會建立 .bak 備份。
// 等同 FixThinkFileWithOpts(ctx, filename, report, s, FixThinkOpts{}).
func FixThinkFile(ctx context.Context, filename string, report *ThinkReport, s ThinkSuggester) (int, error) {
	return FixThinkFileWithOpts(ctx, filename, report, s, FixThinkOpts{})
}

// FixThinkFileWithOpts 同 FixThinkFile，但接受 opts 控制行為。
// opts.Retroactive=true 時切換為事後反推模式（搭配 --fixintent --all）。
func FixThinkFileWithOpts(ctx context.Context, filename string, report *ThinkReport, s ThinkSuggester, opts FixThinkOpts) (int, error) {
	if report == nil || len(report.Missing) == 0 {
		return 0, nil
	}

	content, err := os.ReadFile(filename)
	if err != nil {
		return 0, fmt.Errorf("read: %w", err)
	}

	backupPath := filename + ".bak"
	if err := os.WriteFile(backupPath, content, 0644); err != nil {
		return 0, fmt.Errorf("backup: %w", err)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, content, parser.ParseComments)
	if err != nil {
		return 0, fmt.Errorf("parse: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	modelName := s.ModelName()

	type insertOp struct {
		braceLineIdx int
		thinkLines   []string
	}
	var ops []insertOp

	missingSet := make(map[int]ThinkResult)
	for _, m := range report.Missing {
		missingSet[m.Line] = m
	}

	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Body == nil {
			continue
		}

		declLine := fset.Position(fd.Pos()).Line
		m, ok := missingSet[declLine]
		if !ok {
			continue
		}

		braceIdx := fset.Position(fd.Body.Lbrace).Line - 1

		bodyEnd := fset.Position(fd.Body.Rbrace).Line
		srcStart := declLine - 1
		srcEnd := bodyEnd
		if srcEnd-srcStart > 30 {
			srcEnd = srcStart + 30
		}
		if srcEnd > len(lines) {
			srcEnd = len(lines)
		}
		funcSource := strings.Join(lines[srcStart:srcEnd], "\n")

		recv := ""
		if fd.Recv != nil && len(fd.Recv.List) > 0 {
			recv = exprToString(fd.Recv.List[0].Type)
		}

		suggestion, sugErr := s.SuggestThink(ctx, ThinkSuggestRequest{
			FuncName:    baseName(m.Name),
			Kind:        m.Kind,
			Receiver:    recv,
			Source:      funcSource,
			File:        filename,
			Retroactive: opts.Retroactive,
		})
		if sugErr != nil {
			suggestion = ThinkSuggestion{Intent: fallbackIntent(opts.Retroactive)}
		}

		suffix := fmt.Sprintf("model=%s", modelName)
		if opts.Retroactive {
			suffix += " retroactive=true"
		}

		var thinkLines []string
		if suggestion.Intent != "" {
			thinkLines = append(thinkLines, fmt.Sprintf("//@ai:think intent=%s %s", suggestion.Intent, suffix))
		}
		if suggestion.Special != "" {
			thinkLines = append(thinkLines, fmt.Sprintf("//@ai:think special=%s %s", suggestion.Special, suffix))
		}
		if len(thinkLines) == 0 {
			thinkLines = append(thinkLines, fmt.Sprintf("//@ai:think intent=%s %s", fallbackIntent(opts.Retroactive), suffix))
		}

		ops = append(ops, insertOp{braceLineIdx: braceIdx, thinkLines: thinkLines})
	}

	sort.Slice(ops, func(i, j int) bool {
		return ops[i].braceLineIdx > ops[j].braceLineIdx
	})

	count := 0
	for _, op := range ops {
		insertAt := op.braceLineIdx + 1
		if insertAt > len(lines) {
			insertAt = len(lines)
		}

		indent := "\t"
		if insertAt < len(lines) {
			nextLine := lines[insertAt]
			trimmed := strings.TrimLeft(nextLine, " \t")
			if trimmed != "" && trimmed != "}" {
				indent = nextLine[:len(nextLine)-len(trimmed)]
			}
		}

		newLines := make([]string, len(op.thinkLines))
		for i, tl := range op.thinkLines {
			newLines[i] = indent + tl
		}

		before := append([]string{}, lines[:insertAt]...)
		after := append([]string{}, lines[insertAt:]...)
		lines = append(before, append(newLines, after...)...)
		count++
	}

	if count == 0 {
		return 0, nil
	}

	return count, os.WriteFile(filename, []byte(strings.Join(lines, "\n")), 0644)
}
