// @ai:generated by=claude-opus-4-7 date=2026-06-19
package annotation

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// CheckThinkWithOpts(IncludeAll=false) 等同舊 CheckThink：略過無 @ai:generated 的 func
func TestCheckThinkWithOpts_DefaultSkipsNonGenerated(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "x.go")
	src := `package example

// Human 是人類寫的（沒有 @ai:generated）。
func Human() {
	println("human")
}

// AIGen
// @ai:generated by=x date=2026-06-19
func AIGen() {
	println("ai")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThinkWithOpts(path, CheckThinkOpts{})
	if err != nil {
		t.Fatal(err)
	}
	if report.Scanned != 1 {
		t.Errorf("scanned = %d, want 1 (only @ai:generated)", report.Scanned)
	}
	if len(report.Missing) != 1 || report.Missing[0].Name != "AIGen" {
		t.Errorf("missing = %+v, want [AIGen]", report.Missing)
	}
}

// CheckThinkWithOpts(IncludeAll=true) 把所有 func 都納入
func TestCheckThinkWithOpts_IncludeAllScansEveryFunc(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "x.go")
	src := `package example

// Human 是人類寫的（沒有 @ai:generated）。
func Human() {
	println("human")
}

// AIGen
// @ai:generated by=x date=2026-06-19
func AIGen() {
	println("ai")
}

// Already 已有 think 的，不該再進 missing
// @ai:generated by=x date=2026-06-19
func Already() {
	//@ai:think intent=已有 model=x
	println("already")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThinkWithOpts(path, CheckThinkOpts{IncludeAll: true})
	if err != nil {
		t.Fatal(err)
	}
	if report.Scanned != 3 {
		t.Errorf("scanned = %d, want 3", report.Scanned)
	}
	// Missing = Human + AIGen（Already 已有 think）
	if len(report.Missing) != 2 {
		t.Fatalf("missing = %d, want 2", len(report.Missing))
	}
	names := map[string]bool{}
	for _, m := range report.Missing {
		names[m.Name] = true
	}
	if !names["Human"] || !names["AIGen"] {
		t.Errorf("missing names = %+v, want both Human and AIGen", names)
	}
	if names["Already"] {
		t.Error("Already has @ai:think, should NOT be in missing")
	}
}

// stub suggester：可以從 req.Retroactive 觀察到旗標傳遞
type retroStub struct {
	gotRetroactive bool
	intent         string
}

func (s *retroStub) ModelName() string { return "stub-model" }
func (s *retroStub) SuggestThink(_ context.Context, req ThinkSuggestRequest) (ThinkSuggestion, error) {
	s.gotRetroactive = req.Retroactive
	return ThinkSuggestion{Intent: s.intent}, nil
}

// FixThinkFileWithOpts retroactive=true 時：
//   - prompt 切換為 retroactive 模式（透過觀察 req.Retroactive）
//   - 插入的 //@ai:think 帶 retroactive=true 標籤
func TestFixThinkFileWithOpts_RetroactiveAddsTag(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "x.go")
	src := `package example

// Plain 沒有 @ai:generated。
func Plain() {
	println("hi")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThinkWithOpts(path, CheckThinkOpts{IncludeAll: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Missing) != 1 {
		t.Fatalf("missing = %d, want 1", len(report.Missing))
	}

	s := &retroStub{intent: "事後反推：印 hi"}
	fixed, err := FixThinkFileWithOpts(context.Background(), path, report, s, FixThinkOpts{Retroactive: true})
	if err != nil {
		t.Fatal(err)
	}
	if fixed != 1 {
		t.Errorf("fixed = %d, want 1", fixed)
	}
	if !s.gotRetroactive {
		t.Error("Retroactive flag was not propagated to suggester")
	}

	data, _ := os.ReadFile(path)
	out := string(data)
	if !strings.Contains(out, "retroactive=true") {
		t.Errorf("expected `retroactive=true` tag in output:\n%s", out)
	}
	if !strings.Contains(out, "intent=事後反推：印 hi") {
		t.Errorf("expected suggested intent in output:\n%s", out)
	}
	if !strings.Contains(out, "model=stub-model") {
		t.Errorf("expected model tag in output:\n%s", out)
	}
}

// 不帶 opts → 等同舊行為（無 retroactive 標籤）
func TestFixThinkFile_BackwardCompatNoRetroactiveTag(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "x.go")
	src := `package example

// AIGen
// @ai:generated by=x date=2026-06-19
func AIGen() {
	println("hi")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}

	s := &retroStub{intent: "建立資源"}
	if _, err := FixThinkFile(context.Background(), path, report, s); err != nil {
		t.Fatal(err)
	}
	if s.gotRetroactive {
		t.Error("Default FixThinkFile should NOT pass Retroactive=true")
	}

	data, _ := os.ReadFile(path)
	out := string(data)
	if strings.Contains(out, "retroactive=true") {
		t.Errorf("backward-compat path should NOT add retroactive tag:\n%s", out)
	}
}

// buildThinkPrompt 切換 prompt 字串
func TestBuildThinkPrompt_RetroactiveUsesDifferentSystem(t *testing.T) {
	normal := buildThinkPrompt(ThinkSuggestRequest{FuncName: "Foo", Kind: "func"})
	retro := buildThinkPrompt(ThinkSuggestRequest{FuncName: "Foo", Kind: "func", Retroactive: true})

	if !strings.Contains(normal, "設計意圖") {
		t.Error("normal prompt should mention 設計意圖")
	}
	if strings.Contains(normal, "事後分析") {
		t.Error("normal prompt should NOT mention 事後分析")
	}
	if !strings.Contains(retro, "事後") {
		t.Error("retroactive prompt should mention 事後")
	}
	if !strings.Contains(retro, "你並不是原作者") {
		t.Error("retroactive prompt should clarify you are not the author")
	}
}

func TestFallbackIntent(t *testing.T) {
	if got := fallbackIntent(false); got != "TODO: 說明此函式的意圖" {
		t.Errorf("design fallback = %q", got)
	}
	if got := fallbackIntent(true); got != "TODO: 反推此函式的實際職責" {
		t.Errorf("retroactive fallback = %q", got)
	}
}

// heuristicIntentFor 在 retroactive 模式下要正確改寫，誠實標示 heuristic 出處
func TestHeuristicIntentFor_Retroactive(t *testing.T) {
	tests := []struct {
		name        string
		retroactive bool
		want        string
	}{
		{"CreateUser", false, "建立資源"},
		{"CreateUser", true, "推測：建立資源"},
		{"runGUI", false, "啟動服務"},
		{"runGUI", true, "推測：啟動服務"},
		// 不在 heuristic prefix 表內 → retroactive 模式給更明確的訊息
		{"main", false, "TODO: 說明此函式的意圖"},
		{"main", true, "TODO: 反推此函式的實際職責（heuristic 無法依名稱判定）"},
		{"usage", true, "TODO: 反推此函式的實際職責（heuristic 無法依名稱判定）"},
	}
	for _, tt := range tests {
		got := heuristicIntentFor(tt.name, tt.retroactive)
		if got != tt.want {
			t.Errorf("heuristicIntentFor(%q, %v) = %q, want %q", tt.name, tt.retroactive, got, tt.want)
		}
	}
}

// 空 primary 輸出（沒 error 但 Intent/Special 都空）應走 fallback
type emptyPrimary struct{}

func (e *emptyPrimary) SuggestThink(_ context.Context, _ ThinkSuggestRequest) (ThinkSuggestion, error) {
	return ThinkSuggestion{}, nil // 故意回空且無 error
}
func (e *emptyPrimary) ModelName() string { return "empty-llm" }

// 編碼健全性：含 U+FFFD 或大量私用區字元 → looksWellFormed=false → 整個 Suggestion 被丟棄
func TestParseThinkSuggestion_RejectsMojibake(t *testing.T) {
	tests := []struct {
		name string
		raw  string
		want ThinkSuggestion
	}{
		{
			name: "valid CJK passes",
			raw:  `{"intent":"建立 Fyne 視窗","special":"使用 ShowAndRun 阻塞"}`,
			want: ThinkSuggestion{Intent: "建立 Fyne 視窗", Special: "使用 ShowAndRun 阻塞"},
		},
		{
			name: "valid ASCII passes",
			raw:  `{"intent":"main entrypoint","special":""}`,
			want: ThinkSuggestion{Intent: "main entrypoint"},
		},
		{
			name: "U+FFFD in intent → empty",
			raw:  `{"intent":"程式啟動入口��","special":""}`,
			want: ThinkSuggestion{},
		},
		{
			name: "private-use heavy → empty",
			raw:  `{"intent":"","special":""}`,
			want: ThinkSuggestion{},
		},
	}
	for _, tt := range tests {
		got := parseThinkSuggestion(tt.raw)
		if got.Intent != tt.want.Intent || got.Special != tt.want.Special {
			t.Errorf("%s: got %+v, want %+v", tt.name, got, tt.want)
		}
	}
}

func TestLooksWellFormed(t *testing.T) {
	tests := []struct {
		s    string
		want bool
	}{
		{"", true},
		{"hello world", true},
		{"建立資源", true},
		{"程式啟動入口�", false}, // 含 U+FFFD
		{"", false}, // 全私用區
	}
	for _, tt := range tests {
		if got := looksWellFormed(tt.s); got != tt.want {
			t.Errorf("looksWellFormed(%q) = %v, want %v", tt.s, got, tt.want)
		}
	}
}

func TestFallbackThinkSuggester_FallsBackOnEmptyPrimary(t *testing.T) {
	fb := &fallbackThinkSuggester{
		primary:  &emptyPrimary{},
		fallback: &heuristicThinkSuggester{},
	}
	out, err := fb.SuggestThink(context.Background(), ThinkSuggestRequest{FuncName: "CreateOrder"})
	if err != nil {
		t.Fatal(err)
	}
	// heuristic 對 Create 開頭給「建立資源」
	if out.Intent != "建立資源" {
		t.Errorf("expected heuristic fallback when primary empty, got intent=%q", out.Intent)
	}
}
