package annotation

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckThink_WithThink(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "ok.go")
	src := `package example

// CreateUser 建立使用者
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func CreateUser() {
	//@ai:think intent=建立使用者流程
	println("ok")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}
	if report.Scanned != 1 {
		t.Errorf("scanned = %d, want 1", report.Scanned)
	}
	if len(report.Missing) != 0 {
		t.Errorf("missing = %d, want 0", len(report.Missing))
	}
}

func TestCheckThink_WithThinkSpaced(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "spaced.go")
	src := `package example

// Update 更新
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func Update() {
	// @ai:think intent=更新資料
	println("ok")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Missing) != 0 {
		t.Errorf("missing = %d, want 0 (spaced format should be accepted)", len(report.Missing))
	}
}

func TestCheckThink_MissingThink(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "missing.go")
	src := `package example

// CreateUser 建立使用者
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func CreateUser() {
	println("no think here")
}

// DeleteUser 刪除使用者
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func DeleteUser() {
	println("also missing")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}
	if report.Scanned != 2 {
		t.Errorf("scanned = %d, want 2", report.Scanned)
	}
	if len(report.Missing) != 2 {
		t.Fatalf("missing = %d, want 2", len(report.Missing))
	}
	if report.Missing[0].Name != "CreateUser" {
		t.Errorf("missing[0].Name = %q, want CreateUser", report.Missing[0].Name)
	}
	if report.Missing[1].Name != "DeleteUser" {
		t.Errorf("missing[1].Name = %q, want DeleteUser", report.Missing[1].Name)
	}
}

func TestCheckThink_NoGenerated(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nogen.go")
	src := `package example

// ManualFunc 手寫的函式
func ManualFunc() {
	println("no @ai:generated, should not be checked")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}
	if report.Scanned != 0 {
		t.Errorf("scanned = %d, want 0 (no @ai:generated)", report.Scanned)
	}
	if len(report.Missing) != 0 {
		t.Errorf("missing = %d, want 0", len(report.Missing))
	}
}

func TestCheckThink_Method(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "method.go")
	src := `package example

type Svc struct{}

// Get 讀取
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func (s *Svc) Get() {
	println("method without think")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Missing) != 1 {
		t.Fatalf("missing = %d, want 1", len(report.Missing))
	}
	if report.Missing[0].Kind != "method" {
		t.Errorf("kind = %q, want method", report.Missing[0].Kind)
	}
	if report.Missing[0].Name != "(*Svc).Get" {
		t.Errorf("name = %q, want (*Svc).Get", report.Missing[0].Name)
	}
}

func TestCheckThink_Mixed(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "mixed.go")
	src := `package example

// Good 有 think 的
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func Good() {
	//@ai:think intent=測試用
	println("ok")
}

// Bad 缺 think 的
// @ai:generated by=claude-opus-4-6 date=2026-06-18
func Bad() {
	println("nope")
}

// Manual 沒有 @ai:generated
func Manual() {
	println("skip")
}
`
	if err := os.WriteFile(path, []byte(src), 0644); err != nil {
		t.Fatal(err)
	}

	report, err := CheckThink(path)
	if err != nil {
		t.Fatal(err)
	}
	if report.Scanned != 2 {
		t.Errorf("scanned = %d, want 2", report.Scanned)
	}
	if len(report.Missing) != 1 {
		t.Fatalf("missing = %d, want 1", len(report.Missing))
	}
	if report.Missing[0].Name != "Bad" {
		t.Errorf("missing[0].Name = %q, want Bad", report.Missing[0].Name)
	}
}

func TestFormatThinkReport_NoMissing(t *testing.T) {
	report := &ThinkReport{Filename: "test.go", Scanned: 3}
	out := FormatThinkReport(report)
	if !strings.Contains(out, "all 3 AI-generated funcs have @ai:think") {
		t.Errorf("unexpected output: %s", out)
	}
}

func TestFormatThinkReport_WithMissing(t *testing.T) {
	report := &ThinkReport{
		Filename: "test.go",
		Scanned:  2,
		Missing: []ThinkResult{
			{Name: "Foo", Kind: "func", Line: 10},
		},
	}
	out := FormatThinkReport(report)
	if !strings.Contains(out, "1/2") {
		t.Errorf("should show 1/2 missing: %s", out)
	}
	if !strings.Contains(out, "[WARN]") {
		t.Errorf("should use [WARN] label: %s", out)
	}
}

func TestWriteLostIntentReport(t *testing.T) {
	origToday := todayISO
	todayISO = func() string { return "2026-06-18" }
	defer func() { todayISO = origToday }()

	dir := t.TempDir()
	hypDir := filepath.Join(dir, ".hyp")

	report := &ThinkReport{
		Filename: "controllers/user.go",
		Scanned:  3,
		Missing: []ThinkResult{
			{Name: "CreateUser", Kind: "func", Line: 42},
			{Name: "(*Svc).Delete", Kind: "method", Line: 78},
		},
	}

	if err := WriteLostIntentReport(hypDir, report); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(hypDir, "lostintent.md"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	if !strings.Contains(content, "# Lost Intent Report") {
		t.Error("missing title")
	}
	if !strings.Contains(content, "controllers/user.go") {
		t.Error("missing filename section")
	}
	if !strings.Contains(content, "| 42 | func CreateUser |") {
		t.Error("missing CreateUser entry")
	}
	if !strings.Contains(content, "| 78 | method (*Svc).Delete |") {
		t.Error("missing Delete entry")
	}
	if !strings.Contains(content, "warning") {
		t.Error("should mention warning")
	}
}

func TestWriteLostIntentReport_Merge(t *testing.T) {
	origToday := todayISO
	todayISO = func() string { return "2026-06-18" }
	defer func() { todayISO = origToday }()

	dir := t.TempDir()
	hypDir := filepath.Join(dir, ".hyp")

	report1 := &ThinkReport{
		Filename: "a.go", Scanned: 1,
		Missing: []ThinkResult{{Name: "FuncA", Kind: "func", Line: 10}},
	}
	if err := WriteLostIntentReport(hypDir, report1); err != nil {
		t.Fatal(err)
	}

	report2 := &ThinkReport{
		Filename: "b.go", Scanned: 1,
		Missing: []ThinkResult{{Name: "FuncB", Kind: "func", Line: 20}},
	}
	if err := WriteLostIntentReport(hypDir, report2); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(filepath.Join(hypDir, "lostintent.md"))
	content := string(data)

	if !strings.Contains(content, "## a.go") {
		t.Error("should preserve a.go section")
	}
	if !strings.Contains(content, "## b.go") {
		t.Error("should add b.go section")
	}
}

func TestWriteLostIntentReport_UpdateRemovesFixed(t *testing.T) {
	origToday := todayISO
	todayISO = func() string { return "2026-06-18" }
	defer func() { todayISO = origToday }()

	dir := t.TempDir()
	hypDir := filepath.Join(dir, ".hyp")

	report1 := &ThinkReport{
		Filename: "a.go", Scanned: 1,
		Missing: []ThinkResult{{Name: "FuncA", Kind: "func", Line: 10}},
	}
	if err := WriteLostIntentReport(hypDir, report1); err != nil {
		t.Fatal(err)
	}

	reportFixed := &ThinkReport{Filename: "a.go", Scanned: 1}
	if err := WriteLostIntentReport(hypDir, reportFixed); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(filepath.Join(hypDir, "lostintent.md"))
	content := string(data)

	if strings.Contains(content, "## a.go") {
		t.Error("fixed file should be removed from report")
	}
	if !strings.Contains(content, "Nothing to report") {
		t.Error("empty report should show 'nothing to report'")
	}
}

func TestCheckThink_RejectsNonGo(t *testing.T) {
	_, err := CheckThink("test.txt")
	if err == nil {
		t.Error("should reject non-.go files")
	}
}
