// @ai:generated by=claude-opus-4-6 date=2026-06-18
// @ai:purpose 檢查 AI 生成的 func 是否包含 //@ai:think 意圖註解
package annotation

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// ThinkResult 單一缺失 @ai:think 的函式紀錄
type ThinkResult struct {
	Name string // "CreateUser" 或 "(*UserService).GetUser"
	Kind string // "func" 或 "method"
	Line int
}

// ThinkReport 單一檔案的 @ai:think 檢查報告
type ThinkReport struct {
	Filename string
	Missing  []ThinkResult
	Scanned  int
}

// CheckThink 掃描 Go 檔案，找出有 @ai:generated 但函式體內缺少 //@ai:think 的 func。
func CheckThink(filename string) (*ThinkReport, error) {
	if filepath.Ext(filename) != ".go" {
		return nil, fmt.Errorf("only .go files are supported: %s", filename)
	}

	info, err := os.Lstat(filename)
	if err != nil {
		return nil, fmt.Errorf("cannot stat file: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("symbolic links are not supported: %s", filename)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse error: %w", err)
	}

	report := &ThinkReport{Filename: filename}

	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Body == nil {
			continue
		}

		if !docHasGenerated(fd.Doc) {
			continue
		}

		report.Scanned++

		kind := "func"
		name := fd.Name.Name
		if fd.Recv != nil && len(fd.Recv.List) > 0 {
			kind = "method"
			recv := exprToString(fd.Recv.List[0].Type)
			name = "(" + recv + ")." + fd.Name.Name
		}

		bodyStart := fset.Position(fd.Body.Lbrace).Offset
		bodyEnd := fset.Position(fd.Body.Rbrace).Offset

		if !bodyHasThink(f.Comments, fset, bodyStart, bodyEnd) {
			report.Missing = append(report.Missing, ThinkResult{
				Name: name,
				Kind: kind,
				Line: fset.Position(fd.Pos()).Line,
			})
		}
	}

	return report, nil
}

// docHasGenerated 檢查 doc comment 是否包含 @ai:generated
func docHasGenerated(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if strings.HasPrefix(text, "@ai:generated") {
			return true
		}
	}
	return false
}

// bodyHasThink 檢查函式體範圍內的註解是否包含 @ai:think
func bodyHasThink(comments []*ast.CommentGroup, fset *token.FileSet, bodyStart, bodyEnd int) bool {
	for _, cg := range comments {
		for _, c := range cg.List {
			pos := fset.Position(c.Pos()).Offset
			if pos <= bodyStart || pos >= bodyEnd {
				continue
			}
			text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if strings.HasPrefix(text, "@ai:think") {
				return true
			}
		}
	}
	return false
}

// FormatThinkReport 格式化 @ai:think 檢查報告為終端輸出
func FormatThinkReport(report *ThinkReport) string {
	if report == nil || len(report.Missing) == 0 {
		return fmt.Sprintf("\n[unintent] %s: all %d AI-generated funcs have @ai:think ✓\n",
			report.Filename, report.Scanned)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("\n[unintent] %s: %d/%d AI-generated funcs missing @ai:think\n",
		report.Filename, len(report.Missing), report.Scanned))

	for _, m := range report.Missing {
		sb.WriteString(fmt.Sprintf("  [WARN] %s %s (line %d) — missing @ai:think\n", m.Kind, m.Name, m.Line))
	}

	return sb.String()
}

// WriteLostIntentReport 將缺失報告寫入 .hyp/lostintent.md
func WriteLostIntentReport(hypDir string, report *ThinkReport) error {
	if report == nil {
		return nil
	}

	if err := os.MkdirAll(hypDir, 0755); err != nil {
		return fmt.Errorf("cannot create %s: %w", hypDir, err)
	}

	outPath := filepath.Join(hypDir, "lostintent.md")

	existing := readExistingLostIntent(outPath)

	merged := mergeLostIntent(existing, report)

	content := renderLostIntentMD(merged)

	return os.WriteFile(outPath, []byte(content), 0644)
}

// lostIntentEntry 表示 lostintent.md 中的一筆紀錄
type lostIntentEntry struct {
	Filename string
	Missing  []ThinkResult
	Scanned  int
}

// readExistingLostIntent 讀取既有的 lostintent.md 並解析各檔案區段。
// 格式有限度解析：以 "## " 開頭識別檔案區段，以 "| " 開頭的表格列解析函式。
func readExistingLostIntent(path string) []lostIntentEntry {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	var entries []lostIntentEntry
	var current *lostIntentEntry

	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "## ") {
			if current != nil {
				entries = append(entries, *current)
			}
			fname := strings.TrimPrefix(line, "## ")
			fname = strings.TrimSpace(fname)
			current = &lostIntentEntry{Filename: fname}
			continue
		}
		if current == nil {
			continue
		}
		if !strings.HasPrefix(line, "| ") || strings.HasPrefix(line, "| Line") || strings.HasPrefix(line, "|---") {
			continue
		}
		parts := strings.Split(line, "|")
		if len(parts) < 4 {
			continue
		}
		lineStr := strings.TrimSpace(parts[1])
		kindName := strings.TrimSpace(parts[2])
		var lineNum int
		fmt.Sscanf(lineStr, "%d", &lineNum)

		kind := "func"
		name := kindName
		if strings.HasPrefix(kindName, "method ") {
			kind = "method"
			name = strings.TrimPrefix(kindName, "method ")
		} else if strings.HasPrefix(kindName, "func ") {
			name = strings.TrimPrefix(kindName, "func ")
		}

		current.Missing = append(current.Missing, ThinkResult{
			Name: name, Kind: kind, Line: lineNum,
		})
	}
	if current != nil {
		entries = append(entries, *current)
	}
	return entries
}

// mergeLostIntent 合併既有紀錄與新報告（同檔名覆蓋、無缺漏則移除）
func mergeLostIntent(existing []lostIntentEntry, report *ThinkReport) []lostIntentEntry {
	var result []lostIntentEntry

	found := false
	for _, e := range existing {
		if e.Filename == report.Filename {
			found = true
			if len(report.Missing) > 0 {
				result = append(result, lostIntentEntry{
					Filename: report.Filename,
					Missing:  report.Missing,
					Scanned:  report.Scanned,
				})
			}
			continue
		}
		result = append(result, e)
	}

	if !found && len(report.Missing) > 0 {
		result = append(result, lostIntentEntry{
			Filename: report.Filename,
			Missing:  report.Missing,
			Scanned:  report.Scanned,
		})
	}

	return result
}

// renderLostIntentMD 將所有紀錄渲染為 markdown
func renderLostIntentMD(entries []lostIntentEntry) string {
	var sb strings.Builder

	sb.WriteString("<!-- auto-generated by hyp chkcomment --unintent -->\n")
	sb.WriteString("# Lost Intent Report\n\n")
	sb.WriteString("> AI-generated functions missing `//@ai:think` — lint warning, not violation.\n")
	sb.WriteString(fmt.Sprintf("> Last updated: %s\n", todayISO()))

	if len(entries) == 0 {
		sb.WriteString("\nAll AI-generated functions have `@ai:think`. Nothing to report.\n")
		return sb.String()
	}

	total := 0
	for _, e := range entries {
		total += len(e.Missing)
		sb.WriteString(fmt.Sprintf("\n## %s\n\n", e.Filename))
		sb.WriteString("| Line | Function |\n")
		sb.WriteString("|------|----------|\n")
		for _, m := range e.Missing {
			sb.WriteString(fmt.Sprintf("| %d | %s %s |\n", m.Line, m.Kind, m.Name))
		}
	}

	sb.WriteString(fmt.Sprintf("\n---\n\n**Total: %d AI-generated function(s) missing `@ai:think`.**\n", total))

	return sb.String()
}
