//go:build windows

// @ai:generated by=claude-opus-4-8 date=2026-06-15
package contract

import (
	"time"

	"golang.org/x/sys/windows"
)

// processCPUTime 回傳目前行程累計的 CPU 時間（kernel + user）。
// 用於在請求前後取樣求差，估算單次交換消耗的 CPU 時間（行程層級，循序模式下近似於該請求）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func processCPUTime() time.Duration {
	var creation, exit, kernel, user windows.Filetime
	if err := windows.GetProcessTimes(windows.CurrentProcess(), &creation, &exit, &kernel, &user); err != nil {
		return 0
	}
	// Filetime 以 100ns 為單位
	k := int64(kernel.HighDateTime)<<32 | int64(kernel.LowDateTime)
	u := int64(user.HighDateTime)<<32 | int64(user.LowDateTime)
	return time.Duration((k + u) * 100)
}
