//go:build !windows

// @ai:generated by=claude-opus-4-8 date=2026-06-15
package contract

import (
	"syscall"
	"time"
)

// processCPUTime 回傳目前行程累計的 CPU 時間（user + system）。
// 用於在請求前後取樣求差，估算單次交換消耗的 CPU 時間（行程層級，循序模式下近似於該請求）。
// @ai:generated by=claude-opus-4-8 date=2026-06-15
func processCPUTime() time.Duration {
	var ru syscall.Rusage
	if err := syscall.Getrusage(syscall.RUSAGE_SELF, &ru); err != nil {
		return 0
	}
	utime := time.Duration(int64(ru.Utime.Sec))*time.Second + time.Duration(int64(ru.Utime.Usec))*time.Microsecond
	stime := time.Duration(int64(ru.Stime.Sec))*time.Second + time.Duration(int64(ru.Stime.Usec))*time.Microsecond
	return utime + stime
}
